### ISSUE TITLE
Support for Annotation Property in ontology

### ISSUE THREAD

**Issue by skomlaebri** [ontop/ontop#105]
Currently we support annotation properties present in the mappings, but we ignore annotation properties present in the ontology.

**Comment by Lanvin2219** [comment]
Hello,

I have a problem with the mapping.

:{text} a :Animal ; rdfs:label {annotation} .

This gives me a error message "The below list of predicates is unknown by the ontology : - http://www.w3.org/2000/01/rdf-schema#label"

It seems correct to me.

**Comment by skomlaebri** [comment]
Hi,
thank you for reporting the issues. 
The first mapping is not working since rdfs:label is not defined in the ontology, you can temporally solve the issue adding rdfs:label in your ontology. From Protege go on the Annotation property hierarchy tab and add the property rdfs:label even it is already present.

**Comment by Lanvin2219** [comment]
Thank you ! 
It works but it puts the rdfs:label as a Data property instead of an Annotation property.

**Comment by skomlaebri** [comment]
Fixed in 39b85c2
