### ISSUE TITLE
Group by

### ISSUE THREAD

**Issue by eugenesiow** [ontop/ontop#109]
Hi,

I'm trying to run a query like this:
```sql
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX iotsn: <http://iot.soton.ac.uk/smarthome/sensor#>
PREFIX iot: <http://purl.oclc.org/NET/iot#>

SELECT (avg(?val) as ?sval) ?hours
WHERE {
  ?instant time:inXSDDateTime ?date.
  ?obs ssn:observationSamplingTime ?instant;
  	ssn:observedBy iotsn:environmental1;
    ssn:observationResult ?snout.
  ?snout ssn:hasValue ?obsval.
  ?obsval a iot:InternalTemperatureValue;
    iot:hasQuantityValue ?val.
  FILTER (?date > "2012-07-20T00:00:00"^^xsd:dateTime && ?date < "2012-07-21T00:00:00"^^xsd:dateTime)
} GROUP BY (hours(xsd:dateTime(?date)) as ?hours)
```

This is a line in the error message I'm getting:
```
org.openrdf.query.QueryEvaluationException: Operation not supported: Group (hours)
```

I've tried with `GROUP BY ?date` and `GROUP BY ?val` as well changing the select accordingly but I get the same error.

Thanks!

I was testing with ontop-distribution-1.6.1.

**Comment by bcogrel** [comment]
Aggregation is currently not supported, we are working on adding this feature to the next **major** release (not version 1.18 but 3.0).

**Comment by eugenesiow** [comment]
Thanks for the clarification!

**Comment by KMax** [comment]
Hi @bcogrel! The group by still isn't supported, am I right?

Just run a query through Protege plugin and got:
```
it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL GROUP BY is not supported yet
```

**Comment by bcogrel** [comment]
Hi,

Indeed aggregates are not yet supported but are among our top priorities for 2019. 

Best,
Benjamin
