### ISSUE TITLE
No data source to select in the mapping manager

### ISSUE THREAD

**Issue by Lanvin2219** [ontop/ontop#112]
Protege-5.0.0-beta-24
Ontop OBDA Protégé plugin 1.17.1

I'm referring to 'Ontop Mappings' tab.

The connection parameters in the 'Datasource manager' tab seem to be correct : the test connection returns "Connection is OK".

https://www.youtube.com/watch?v=KHtlARfex4c

When I watched the demo (even though it's a different version), I noticed at 10 minutes and 50 seconds that Mariano was selecting a datasource that I couldn't with my version.

**Comment by ghxiao** [comment]
Hi, we have removed the option of data-source selection in the latest version. 

The reason is that Ontop does not really support query answering over multiple data-sources by itself. 
If you have more than one datasource there, the protege-plugin cannot work properly.
The drop list there caused many confusions. 

The change was made in issue #89

**Comment by Lanvin2219** [comment]
Thanks a lot !

**Comment by Lanvin2219** [comment]
The reason I was looking for a data source selection is because when I try to create a mapping, there's a warning telling me to select a data source to proceed.

**Comment by skomlaebri** [comment]
Hi, this is bug that we already known and will be solved in the next version of ontop. 
In the meanwhile to avoid the problem, after you have set the datasource values in Datasource manager, click on "Test connection", before moving to the mapping manager.

**Comment by Lanvin2219** [comment]
I tested the connection and it was OK.

**Comment by skomlaebri** [comment]
You need to follow this step (only for the first time in which you create a datasource) 
Open Protege, load your ontology if you already have it or create a new ontology, go to ontop mapping, create the datasource, click on "Test connection", move to mapping manager to create a new mapping.

**Comment by Lanvin2219** [comment]
Thank you !
