### ISSUE TITLE
Driver class not appearing in the selection bar of the datasource editor

### ISSUE THREAD

**Issue by Lanvin2219** [ontop/ontop#113]
I added a JDBC driver in the Preferences.

jTDS
Class Name : net.sourceforge.jtds.jdbc.Driver
Status : ready

Then, in the 'Ontop Mappings' tab (under Datasource manager), I cannot see it in the suggestions.

**Comment by ghxiao** [comment]
Hi,

The options of jdbc Driver list are predefined. Those drivers in the list are what officially support. If it is not in the list, you can just manually input it there.

Note that jTDS is not among the official  supported JDBC Drivers. 
As far as I remember, there is some known issue with Ontop.

If you want to use a MSSQL database, I would suggest you use the official JDBC drivers from Miscrosoft.

**Comment by Lanvin2219** [comment]
Thanks again !
