### ISSUE TITLE
Mapping result

### ISSUE THREAD

**Issue by Lanvin2219** [ontop/ontop#115]
Hello,

I've succeeded in creating a mapping with mapping manager.

:{language_name} a :language .

SELECT language_name FROM dbo.language

I wanted to create languages in my ontology with this mapping and I thought that the mapping I made would create some individuals of the language class but it didn't.

I may have misunderstood what the mapping is supposed to do.

**Comment by skomlaebri** [comment]
Hi,
the mappings can be used to generate individuals using materialization, but this is not their main purpose. Once you have created your mappings, and started the reasoner, triples are generated  on-the-fly  and you can query your data using SPARQL. Have a look here at the tutorial https://github.com/ontop/ontop/wiki/Easy-Tutorial:-Using-Ontop-from-Protege.
If you need to generate the individuals in your class this can be done from Protege going to the menu ontop > Materialize triples > Add individuals to current ontology.
