### ISSUE TITLE
ontop R2RML support outside of Protégé

### ISSUE THREAD

**Issue by JensPiegsa** [ontop/ontop#116]
I'm currently evaluating ontop for our usage scenario. We develop a web application that is going to query different relational databases mapped to RDF via R2RML (SPARQL endpoint). R2RML should be provided from the end user via our web frontend.

The R2RML support of ontop within Protégé is described here:

* https://github.com/ontop/ontop/wiki/ObdalibRdb2rdf#r2rml-tools-in--ontop-

Now, I wonder whether ontop supports R2RML separately from Protégé and where to start?

**Comment by ghxiao** [comment]
Hi, if I understand correctly, you want to use ontop as a Java API and put it into your application. Our API supports R2RML. 

To do so, you can follow the example 

https://github.com/ontop/ontop-api-examples/blob/master/src/main/java/org/semanticweb/ontop/examples/books/QuestSesame_R2RML_Example.java

**Comment by ghxiao** [comment]
If you just want to setup a SPARQL endpoint using R2RML files. You can convert the R2RML file into ontop mapping first by command line.

https://github.com/ontop/ontop/wiki/OntopCLI#ontop-mapping-to-obda

**Comment by JensPiegsa** [comment]
Thanks for your fast reply. That looks promising, I'll try both.

**Comment by seralf** [comment]
Hi is the schema for the database example provided somewhere? I'd like to reproduce the example using different JDBC drivers, in order to make some test (for example using SQLite)
