### ISSUE TITLE
Is it possible to map classes instead of individuals ?

### ISSUE THREAD

**Issue by Lanvin2219** [ontop/ontop#118]
:{name} a owl:Class .

SELECT name from database

I don't know why this isn't working.

**Comment by skomlaebri** [comment]
You cannot define the classes in the mappings, but you can use them.
So an accepted mapping would be
:author/1 a :{name} .
SELECT name from database

**Comment by Lanvin2219** [comment]
It works if the class :{name} exists, correct ?

**Comment by skomlaebri** [comment]
Hi, it can work also if the class does not exist if you use a correct absolute URI

**Comment by Lanvin2219** [comment]
Thank you !
