### ISSUE TITLE
The below list of predicates is unknown by the ontology

### ISSUE THREAD

**Issue by Lanvin2219** [ontop/ontop#119]
Hi, 

I tried a little mapping like this 

:{ID} a :Sector ; :code {Code}^^xsd:decimal .

select "ID", "Code" from database

And I got this message even though I have the DataProperty well defined : 

ERROR : The below list of predicates is unknown by the ontology:
ontology#code

When I try to recreate it, I get : 

"Entity already exists : ontology#code"

In the turtle file, I already have : 

":code a owl:DatatypeProperty ." 

Can you please help me ?

**Comment by skomlaebri** [comment]
Can you send us ontology and mapping, so we can reproduce the problem?

**Comment by Lanvin2219** [comment]
I tried to recreate the problem and I can't anymore. It works. Really strange.

Thank you for helping !
