### ISSUE TITLE
Rendering and editing of mappings in Protege 4 can only be done using the URI's

### ISSUE THREAD

**Issue by marianormuro** [ontop/ontop#12]
This is a big issue for the usual pattern in which ontologies are constructed. Usually, URI's for classes and Properties are non-readable machine-oriented, making mappings for this would be cumbersome for a person.

The GUI should be extended to allow rendering and editing using the alternative's available in protege (by rdfs:label for example, or other custom annotation properties).

**Comment by ghxiao** [comment]
close it for the moment since we don't have a concrete idea.

**Comment by marianormuro** [comment]
oh I know about this, if you want we can discuss it tomorrow and re-open
it. Its not hard I think

On Wed, May 13, 2015 at 4:35 PM, Guohui Xiao <notifications@github.com>
wrote:

> close it for the moment since we don't have a concrete idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ontop/ontop/issues/12#issuecomment-101807192>.
>



-- 

Mariano Rodriguez Muro
http://www.rodriguez-muro.com
https://w3-connections.ibm.com/profiles/html/profileView.do?uid=3G3860897

Research Staff, IBM Research
IBM T.J. Watson research center
Yorktown heights, NY. USA
+1-914-945-2607

home: mariano.muro@gmail.com
work: mrodrig@us.ibm.com
