### ISSUE TITLE
Special alphabet encoding

### ISSUE THREAD

**Issue by Lanvin2219** [ontop/ontop#121]
Hi,

I mapped a Continent table and I noticed that languages like Japanese and Hebrew returned question marks ("??????"@jp for example) whereas special characters in Latin alphabet were rendered correctly ("Sør-Amerika"@no g.e.)

How to print the correct Japanese or Hebrew characters ?

Thanks.

**Comment by ghxiao** [comment]
Hi,

There are many factors crossing different layers affecting encoding. 

What is your OS ?  
What is your database? What is the encoding used in your database?
How did you use ontop? From protege or from command line?
These values ?????? are from database or from the ontology file?

In practice, we always try to use UTF8 encoding in all places which avoid most encoding problems.

**Comment by Lanvin2219** [comment]
Thanks for answering.

OS : Ubuntu 16.04 LTS 32 bits
Database : SQL Server
Ontop : from Protégé

The values are fine in the database and when I tested the query with the Mapping editor, it was also fine.

The problem occurred when I tried to get the values with a SPARQL query.

SELECT ?continent ?label WHERE {
?continent a :Continent;
rdfs:label ?label.
}
