### ISSUE TITLE
Enabling streaming for query answering and materialization

### ISSUE THREAD

**Issue by bcogrel** [ontop/ontop#122]
Setting the JDBC connection in streaming mode is very important for materializing large RDF graphs but could also be more generally interesting for handling queries with large answer sets.

Unfortunately, such a configuration of the JDBC connection is DB-specific so we need a new abstraction for allowing it.

Currently, AFAIK, the streaming mode is only working with PostgreSQL in the materialization mode.

This feature is a frequent user request.

**Comment by mjb95** [comment]
The 1.18.1 release has a "--no-streaming" flag on the ontop materialize command line help menu (which suggests that it does stream by default), however it doesn't look like this is the case at all as the generated triple file is 0 bytes in size until the process finishes.

Is this a bug?

**Comment by dbilid** [comment]
Hello,

why is this an issue, since the user can modify the JDBC methods Connection.setAutoCommit (through QuestOWLConnection) and Statement.setFetchSize (through QuestOWLStatement)?

I have tested that and "streaming" answers seem to be working for MySQL, PostgreSQL and DB2 by setting these two methods accordingly.

**Comment by bcogrel** [comment]
Starting from 4.0.0-beta-2 (now in the `version4` branch), streaming is enabled by default both for query answering and materialization. It is parametrized by the key `jdbc.fetchSize`, which can be overridden in the properties file.

The methods `setFetchSize(...)` have been removed.

Internally, the JDBC statement are now created and initialized by a  `JDBCStatementInitializer`. The implementation of this class is injected, allowing for instance PostgreSQL to have a different implementation.
