### ISSUE TITLE
deployment jdbc drivers webapp

### ISSUE THREAD

**Issue by bertvannuffelen** [ontop/ontop#126]
Dear,

how to deploy jdbc drivers in a running webapp environment?

kr,

Bert

**Comment by JensPiegsa** [comment]
In our project we deployed the MySQL connector JAR file in the same way one would deploy a WAR.

To make the connector available to the application in case of WildFly, one has to declare a dependency in the deployment descriptor (WEB-INF/jboss-deployment-structure.xml):

```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.0">
	<deployment>
		<dependencies>
			<module name="deployment.mysql-connector-java-5.1.37.jar" />
		</dependencies>
	</deployment>
</jboss-deployment-structure>
```

(see: https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6/html/Development_Guide/chap-Class_Loading_and_Modules.html#Dynamic_Module_Naming1)

**Comment by bertvannuffelen** [comment]
Hi,

it seems that when deploying it as global dependency in tomcat libs this library is picked up. And hence it works.

kr,

Bert
