### ISSUE TITLE
Adding a set of static triples not present in the relational database

### ISSUE THREAD

**Issue by JensPiegsa** [ontop/ontop#130]
I managed to access our database content through SPARQL over the Java API like shown here:
https://github.com/ontop/ontop-api-examples/blob/master/src/main/java/org/semanticweb/ontop/examples/books/QuestSesame_R2RML_Example.java

Now I face the need to add some static triples not present in the relational database. A workaround looks like:

```
[
    rr:logicalTable       [
        rr:sqlQuery  "SELECT 'Kurze Beschreibung' AS lang_de, 'Short Description' AS lang_en FROM any_table LIMIT 1;"
    ];
    rr:subjectMap         [
        rr:template  "http://dd.rdf#shortDescription" ; rr:termType rr:IRI
    ] ;
    rr:predicateObjectMap [
        rr:objectMap [ rr:column "lang_de" ; rr:language "de" ; rr:termType rr:Literal ; rr:datatype xsd:string ] ;
        rr:predicate dd:propertyLabel
    ] ;
    rr:predicateObjectMap [
        rr:objectMap [ rr:column "lang_en" ; rr:language "en" ; rr:termType rr:Literal ; rr:datatype xsd:string ] ;
        rr:predicate dd:propertyLabel
    ]
] .
```

Are there better ways to insert additional triples to the `SesameVirtualRepo`?
Both targets — ABox and TBox — may be of interest here.

Or execute SPARQL queries over multiple sources?

**Comment by JensPiegsa** [comment]
To make it more "static" I now use [`rr:constant`](https://www.w3.org/TR/r2rml/#constant) and rewrote the above R2RML snippet:

    [
        rr:logicalTable [
            rr:sqlQuery "SELECT 1 FROM INFORMATION_SCHEMA.TABLES LIMIT 1;"
        ] ;
        rr:subjectMap [
            rr:constant "http://dd.rdf#shortDescription"
        ] ;
        rr:predicateObjectMap [
            rr:predicateMap [ rr:constant dd:propertyLabel ] ; 
            rr:objectMap [ rr:constant "Kurze Beschreibung" ; rr:language "de" ]
        ] ;
        rr:predicateObjectMap [
            rr:predicateMap [ rr:constant dd:propertyLabel ] ;
            rr:objectMap [ rr:constant "Short Description" ; rr:language "en" ]
        ]
    ] .

which can be written more concise using the constant shortcut properties (`rr:subject`, `rr:predicate`):

    [
        rr:logicalTable [
            rr:sqlQuery "SELECT 1 FROM INFORMATION_SCHEMA.TABLES LIMIT 1;"
        ] ;
        rr:subject "http://dd.rdf#shortDescription" ;
        rr:predicateObjectMap [
            rr:predicate dd:propertyLabel ; 
            rr:objectMap [ rr:constant "Kurze Beschreibung" ; rr:language "de" ]
        ] ;
        rr:predicateObjectMap [
            rr:predicate dd:propertyLabel ;
            rr:objectMap [ rr:constant "Short Description" ; rr:language "en" ]
        ]
    ] .

This looks quite ok, but raises two small issues regarding the SQL statement:

* the `it.unibz.krdb.obda.parser.SQLQueryDeepParser` complains about the query not being simple enough: 

    > The following query couldn't be parsed. This means Quest will need to use nested subqueries (views) to use this mappings. This is not good for SQL performance, specially in MySQL. Try to simplify your query to allow Quest to parse it. If you think this query is already simple and should be parsed by Quest, please contact the authors.
SQLQueryDeepParser "The following query couldn't be parsed."

* indeed trying to make it simpler fails, because the valid statement `SELECT 1;` is rejected

**Comment by skomlaebri** [comment]
Hi,
there are 3 possibilities you can follow:
1. To improve the performance, you can add classes, properties and individuals to the ontology.
For example:
`<owl:DatatypeProperty rdf:about="http://dd.rdf#shortDescription" 
<rdfs:label>Kurze Beschreibung@de</rdfs:label>
</owl:DatatypeProperty> `
2. You can write the triple as
``` [
    rr:logicalTable [
        rr:sqlQuery "SELECT 1 FROM INFORMATION_SCHEMA.TABLES;"
    ] ;
    rr:subject "http://dd.rdf#shortDescription" ;
    rr:predicateObjectMap [
        rr:predicate dd:propertyLabel ; 
        rr:objectMap [ rr:constant "Kurze Beschreibung" ; rr:language "de" ]
    ] ;
    rr:predicateObjectMap [
        rr:predicate dd:propertyLabel ;
        rr:objectMap [ rr:constant "Short Description" ; rr:language "en" ]
    ]
] .
```
3. You can use SPARQL federation to execute SPARQL queries, having two endpoints: one with ontop and one with a traditional triplestore where you can add the additional triples.

**Comment by ghxiao** [comment]
Hi @JensPiegsa, i am closing the issue now but free feel to reopen the issue if you still have problem
