### ISSUE TITLE
deployment on tomcat7 - exception 

### ISSUE THREAD

**Issue by bertvannuffelen** [ontop/ontop#132]
Dear,

I have the workbench properly deploy, and I see the ontop dedicated configuration.
However when trying to create repository, I get the following exception:

javax.servlet.ServletException: javax.servlet.ServletException: org.openrdf.repository.config.RepositoryConfigException: Unsupported repository type: obda:OntopRepository
	org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:116)
	org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:136)
	org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:104)
	org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:222)
	org.openrdf.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:151)
	org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:119)
	org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:131)
	org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:136)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:63)

kr,

Bert

**Comment by bertvannuffelen** [comment]
I did the following check:

vagrant@vagrant:/var/lib/tomcat7/webapps/openrdf-workbench$ cd WEB-INF/lib/
vagrant@vagrant:/var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib$ jar -tf ontop-distribution-1.18.0.jar |grep sesame
it/unibz/inf/ontop/sesame/
it/unibz/inf/ontop/sesame/SesameHelper.class
it/unibz/inf/ontop/sesame/SesameRDFIterator.class
it/unibz/inf/ontop/sesame/SesameStatement.class
it/unibz/inf/ontop/sesame/SesameStatementIterator.class
vagrant@vagrant:/var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib$ jar -tf ontop-distribution-1.18.0.jar |grep Sesmae
vagrant@vagrant:/var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib$ jar -tf ontop-distribution-1.18.0.jar |grep Sesame
it/unibz/inf/ontop/sesame/SesameHelper.class
it/unibz/inf/ontop/sesame/SesameRDFIterator.class
it/unibz/inf/ontop/sesame/SesameStatement.class
it/unibz/inf/ontop/sesame/SesameStatementIterator.class
it/unibz/inf/ontop/owlrefplatform/core/translator/SesameConstructTemplate.class

And I expected to see the class 
 ontop/quest-sesame/src/main/java/it/unibz/inf/ontop/sesame/SesameRepositoryFactory.java

being there because this is the only class that binds the configuration (which is present) with code according to your ontop project.

kr,

Bert

**Comment by bertvannuffelen** [comment]
I backtracked to release 17 and then I get for the same deployment strategy a better respons.
It seems that the whole release 18.0 should be tested whether it is completely build and packaged.

kr,

Bert

**Comment by ghxiao** [comment]
Dear @bertvannuffelen 

We are investigating the issue.  This is also related to #125

**Comment by skomlaebri** [comment]
Hi, 
we made some changes to the release.
You can try the new version from sourceforge at [ontop-1.18.0/ontop-jetty-bundle-1.18.0.1.zip] (https://sourceforge.net/projects/ontop4obda/files/ontop-1.18.0/ontop-jetty-bundle-1.18.0.1.zip/download) or at [ontop-1.18.0/ontop-sesame-webapps-1.18.0.1.zip](https://sourceforge.net/projects/ontop4obda/files/ontop-1.18.0/ontop-sesame-webapps-1.18.0.1.zip/download)

**Comment by bertvannuffelen** [comment]
Hi,

I quickly fired it up in the docker and it seems to work now.
I will do some more testing in the next days.

kr,

Bert

2016-06-07 18:31 GMT+02:00 skomlaebri <notifications@github.com>:
