### ISSUE TITLE
Test ontop-protege with SQLite

### ISSUE THREAD

**Issue by arnikz** [ontop/ontop#133]
Hi,

I have an SQLite database and wanted to test it with the latest [Protege v.5.0.0 + -ontop- bundle](https://sourceforge.net/projects/ontop4obda/files/ontop-1.18.0/ontop-protege-bundle-1.18.0.zip) on Mac OS X (v10.11.2). I'm aware that SQLite is not yet in the list of supported [RDBMS](https://github.com/ontop/ontop/wiki/ObdalibPluginJDBC). The JDBC driver for SQLite can be found [here](https://github.com/xerial/sqlite-jdbc %28sources%29, https://bitbucket.org/xerial/sqlite-jdbc/downloads/sqlite-jdbc-3.8.11.2.jar). I took the following steps:
- Create an example.db

```
CREATE TABLE person (
    pid INTEGER PRIMARY KEY,
    full_name TEXT
);

INSERT INTO person VALUES (1, 'John Smith');
INSERT INTO person VALUES (2, 'Marry Smith');
INSERT INTO person VALUES (3, 'Adam Doe');
```
- Configure Protege to work with SQLite db: Preferences -> JDBC Drivers
  Description: sqlite
  Class Name: org.sqlite.JDBC
  Driver File (jar): sqlite-jdbc-3.8.11.2.jar
- Configure Datasource manager:
  Connection URL: jdbc:sqlite:/path/example.db 
  Database Username:
  Database Password:
  Driver Class: org.sqlite.JDBC
  [Test Connection] -> Connection is OK
- Create mappings in the Mappings manager.
  Target (Triples Template): :Person-{pid} a :Person
  Source (SQL Query): SELECT pid FROM person
  [Test SQL Query] -> no result set
  Protege logs the following error into stdout: SQLite JDBC: inconsistent internal state

Could you please help?

**Comment by ghxiao** [comment]
Hi,

We don't have much experience with SQLite. Could you paste the whole log from protege?

**Comment by arnikz** [comment]
Hi @ghxiao, there is nothing else in the error log than "SQLite JDBC: inconsistent internal state".

**Comment by ghxiao** [comment]
Hi, it is still helpful if you paste the whole log because then I will know when/where the exception is thrown.

**Comment by skomlaebri** [comment]
You probably still need to turn on the debug mode. You can do that inside Protege folder Protege/conf/logback.xml and modify the root level from info to debug.

**Comment by bcogrel** [comment]
Test on an ancient version of Ontop. Using #134 to keep track of the wish to support SQLite.
