### ISSUE TITLE
Docker Ontop

### ISSUE THREAD

**Issue by bertvannuffelen** [ontop/ontop#135]
Dear,

the messages have been reporting are in the context of creating a docker for Ontop.
The first version is now publicly available on 
https://github.com/Informatievlaanderen/OSLO/tree/master/docker-ontop

For now it contains release 1.17.0 as this release is fine. I will update to the recent release after the deployment critical issues have been fixed.

kr,

Bert

**Comment by ghxiao** [comment]
Hi @bertvannuffelen , 

Have you tested ontop 1.18.0.1?

**Comment by bertvannuffelen** [comment]
Hi,

yes we did. It is now running in the tomcat environment.

You can find the docker on docker hub at tenforce/docker-ontop

kr,

Bert

2016-06-21 9:07 GMT+02:00 Guohui Xiao <notifications@github.com>:

**Comment by ghxiao** [comment]
Thanks. 

It seems that https://github.com/Informatievlaanderen/OSLO/tree/master/docker-ontop still uses 1.17 . Could you update the repository?

**Comment by ghxiao** [comment]
Hi again. It seems that https://github.com/bertvannuffelen/docker-ontop is the latest repository.

Btw, what is the license of the docker configuration files?  It would be great if they are also under Apache 2.

Cheers,

**Comment by bertvannuffelen** [comment]
Hi,

that was my intend to use Apache2

Bert
