### ISSUE TITLE
Add RDF

### ISSUE THREAD

**Issue by Lanvin2219** [ontop/ontop#136]
Hi,

I tried to add some RDF triples (Turtle file) into different repositories and every time I got an error. Here they are :

**Ontop In-Memory RDF Store**

HTTP ERROR 500

Problem accessing /openrdf-workbench/repositories/3/add. Reason:

    Failed to upload data: org.openrdf.repository.RepositoryException: Connection does not have an active transaction.

**Ontop Virtual RDF Store**

HTTP ERROR 500

Problem accessing /openrdf-workbench/repositories/1/add. Reason:

    Failed to upload data: org.openrdf.repository.RepositoryException

It works when I add into a classic "In Memory Store" repository.

**Comment by skomlaebri** [comment]
Hi,
thanks for reporting the problem, this feature is not supported by ontop.

**Comment by Lanvin2219** [comment]
Thanks for the answer !
