### ISSUE TITLE
implicit database constraints

### ISSUE THREAD

**Issue by PaulZH** [ontop/ontop#139]
ontop allows the user to supply a list of primary and foreign keys in the initialization of quest.
I see instructions for doing this in Protégé, in using the OWL and Sesame API's but not in the context of the SPARQL endpoint.

Is this not supported?

**Comment by ghxiao** [comment]
Hi, your observation is right. This configuration in SPARQL endpoint is not implemented yet.

In fact, we have a plan to upgrade sesame library and sparql endpoint (#84)

**Comment by bcogrel** [comment]
Can be done with the new endpoint (https://ontop-vkg.org/guide/cli.html#ontop-endpoint).

RDF4J workbench is not maintained anymore.
