### ISSUE TITLE
sparql completely supported ?

### ISSUE THREAD

**Issue by bertvannuffelen** [ontop/ontop#142]
Dear,

I using ontop 18.0.1 with mssql.
I have a the following query  (generated by elda tool -mentions  api call)

SELECT ?item ?p
WHERE {
?item ?p http://my.test.com/mytesturi . 
}  OFFSET 0 LIMIT 10

which causes problems in the translation. Removing the offset fixes the problem.
It seems hence that limits are not properly translated. 

Also it seems that the isBlank case is also not translated.
Is there a list available of functions that are not supported yet?

kr,

Bert

**Comment by skomlaebri** [comment]
Hi!
Here the list of supported sparql functions: 
https://github.com/ontop/ontop/wiki/OntopSPARQLFunctions
Expressions inside BOUND, isIRI, isURI, isBLANK, isLITERAL, STR are not supported. 
Other limitations can be seen here https://github.com/ontop/ontop/wiki/ObdalibIssues.
We are aware of the problem with limit and mssql, it has been reported here : https://github.com/ontop/ontop/issues/131.
The suggested workaround for the moment is to add, if possible, an order by.
in your example:
SELECT ?item ?p
WHERE {
?item ?p http://my.test.com/mytesturi . 
}
ORDER BY ?item
OFFSET 0 LIMIT 10
