### ISSUE TITLE
upgrade to more recent sesame / rdf4j release

### ISSUE THREAD

**Issue by bertvannuffelen** [ontop/ontop#143]
Dear,

In connection with my previous bug report, a suggestion: the sesame 2.7.x release is a rather old release. I suggest to consider an upgrade to the latest release rdf4j.org

kr,

Bert

**Comment by ghxiao** [comment]
Indeed this is our plan:
https://github.com/ontop/ontop/issues/84

**Comment by ghxiao** [comment]
The next release will target the latest release of rdf4j
