### ISSUE TITLE
ONTOP With Large Data

### ISSUE THREAD

**Issue by rac021** [ontop/ontop#147]
Hi,
I'm using ONTOP API in a java project to generate triples from postgres database and have the following code :

```
try (   QuestOWL reasoner  = factory.createReasoner(ontology, config) ;
        QuestOWLConnection conn  = reasoner.getConnection() ;
        QuestOWLStatement st  = conn.createStatement() ;
        QuestOWLResultSet rs  = st.executeTuple(query) ;   )
{
      int columnSize = rs.getColumnCount() ;

      while ( rs.nextRow() )  {

        for (int idx = 1; idx <= columnSize; idx++)  {

               OWLObject binding = rs.getOWLObject(idx) ;        
                ...
                ...
        }
      }   
}
```

 I wonder how ONTOP behave with a very large volume of data..
 Do I expect problems like OutOfMemoryError ?

 A way to stream data from database ?

 Regards. 

 R

**Comment by skomlaebri** [comment]
Out-of-memory error can happen with very large volume of data. We still do not have a way to stream data from database, issue #122 has already been opened regarding this subject.

**Comment by iwharrison** [comment]
Any idea, timewise, as to when streaming will be available for Oracle database drivers?

**Comment by skomlaebri** [comment]
I'm sorry but  I cannot provide a date. We want to support it, but at the moment it is not between our priorities.

**Comment by dbilid** [comment]
I think that if you modify the code as:
        QuestOWL reasoner  = factory.createReasoner(ontology, config) ;
        QuestOWLConnection conn  = reasoner.getConnection() ;
        **conn.setAutoCommit(false);**
        QuestOWLStatement st  = conn.createStatement() ;
        **st.setFetchSize(1000);**
        QuestOWLResultSet rs  = st.executeTuple(query) ;

"streaming" answers will be enabled

**Comment by rac021** [comment]
Does questOWLStatement.setFetchSize works ?

**Comment by ghxiao** [comment]
Hi @rac021 , it is not working yet. We did some investigation and found that different JDBC drivers behavior differently (I don't remember the details now). So we probably could not guarantee the right behavior following the proposal  of @dbilid .

**Comment by rac021** [comment]
Thank you @ghxiao  
For the moment I hack my own "streamer" by playing with LIMIT - OFFSET in the OBDA files. 
Waiting for the version of ONTOP that supports it.

**Comment by bcogrel** [comment]
As mentioned in #122, streaming is now activated by default in the `version4` branch. It is still very fresh and needs to be further tested. It is based on the novel `jdbc.fetchSize` property in replacement of the `setFetchSize(...)` method (which has been removed).

We are now working on also making the novel SPARQL endpoint "stream-compliant".

I am now closing this old issue but feel free to re-open it.
