### ISSUE TITLE
Failed to sparql query with sum aggregation

### ISSUE THREAD

**Issue by ZuoMatthew** [ontop/ontop#149]
Hi, I tried ontop api example and after the first success with book ODBA example, I modified the q1.rq file to add a sum aggregation as below:
PREFIX : <http://meraka/moss/exampleBooks.owl#>
SELECT (sum(?edition) as ?e)
WHERE { ?x a :Book; :title ?title; :genre ?genre; :writtenBy ?y; :hasEdition ?z.
		 ?y a :Author; :name ?author.
		 ?z a :Edition; :editionNumber ?edition
}
then the program failed with "Caused by: it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL", would you please help me find the problem as the documents of ontop indicate the support of sum aggregation. Thank you in advance.

**Comment by skomlaebri** [comment]
Hi, ontop is not supported aggregation at the moment, we are working on it and it needs major refactoring to be supported properly.

**Comment by ZuoMatthew** [comment]
Thank you! Is there any plan for ontop to support such aggregations?

**Comment by skomlaebri** [comment]
yes sure it's current ongoing work, it will most probably appear in the next release.

**Comment by ZuoMatthew** [comment]
It's a good news!!! I tried morph-rdb today and it supports aggregation, as notop has great documents and apis, I am still looking forward to your next release and would try it then. Thank you again!
