### ISSUE TITLE
ontop-cli  - teiid TEIID10001

### ISSUE THREAD

**Issue by obkhan** [ontop/ontop#150]
When attempting using the teiid JDBC connection from ontop-cli, the below is recieved:

SEVERE: Could not create connection
org.teiid.jdbc.TeiidSQLException: TEIID10001 java.security.NoSuchAlgorithmException: DiffieHellman KeyPairGenerator not available

on further inspection the ontop-cli command has:

-Djava.ext.dirs="${ONTOP_HOME}/lib/:${ONTOP_HOME}/jdbc/" it.unibz.inf.ontop.cli.Ontop $@

The error goes away and the connection works after hardcoding the java "ext" folder 

-Djava.ext.dirs="/usr/java/_jdk1.x.x_x_/jre/lib/ext:${ONTOP_HOME}/lib/:${ONTOP_HOME}/jdbc/" it.unibz.inf.ontop.cli.Ontop $@

please refer to the following for an explanation
http://peterttseng.blogspot.com/2008/09/be-careful-when-setting-javaextdirs-to.html

**Comment by obkhan** [comment]
closing - I think this has been fixed looking at the latest version in github

**Comment by ghxiao** [comment]
Indeed. It has been resolved in #141
