### ISSUE TITLE
FILTER on string equals with strings containing numbers

### ISSUE THREAD

**Issue by PaulZH** [ontop/ontop#154]
Query

`select * where {
  ?straat a <http://data.vlaanderen.be/ns/adres#StraatNaam> .
  ?straat <http://data.vlaanderen.be/ns/adres#geografischeNaam> ?naam.
  ?straat <http://mu.semte.ch/vocabularies/core/uuid> ?uuid.
  FILTER (str(?uuid) = 'straatnaam-1')
}
ORDER BY ?uuid`

This returns any result where string ?uuid contains 'straatnaam-1' e.g. "straatnaam-1", "straatnaam-10", "straatnaam-11", "straatnaam-110", ....

I just want the result where ?uuid equals "straatnaam-1", which I think I am asking.

**Comment by skomlaebri** [comment]
Hi,
can you provide the log file, so we can see how your query has been translated into SQL?
Thanks

**Comment by PaulZH** [comment]
Are these to be found at $HOME/.aduna/openrdf-sesame (on Linux) ?

**Comment by PaulZH** [comment]
The translation is
`
SELECT *
FROM (
SELECT 
   1 AS "straatQuestType", NULL AS "straatLang", (CAST ('http://data.vlaanderen.be/id/straatnaam/' as varchar(8000)) + CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(QVIEW1.StraatNaamID AS VARCHAR(8000)), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D') as varchar(8000))) AS "straat", 
   3 AS "naamQuestType", 'de' AS "naamLang", CAST(QVIEW2.Straatnaam_DEU AS VARCHAR(8000)) AS "naam", 
   3 AS "uuidQuestType", NULL AS "uuidLang", (CAST ('straatnaam-' as varchar(8000)) + CAST(QVIEW1.StraatNaamID as varchar(8000))) AS "uuid"
 FROM 
(SELECT StraatID AS StraatNaamID, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'NLD') AS Straatnaam_NDL, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'FRA') AS Straatnaam_FRA, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'DEU') AS Straatnaam_DEU FROM Straat) QVIEW1,
(SELECT StraatID AS StraatNaamID, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'NLD') AS Straatnaam_NDL, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'FRA') AS Straatnaam_FRA, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'DEU') AS Straatnaam_DEU FROM Straat) QVIEW2,
(SELECT StraatID AS StraatNaamID, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'NLD') AS Straatnaam_NDL, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'FRA') AS Straatnaam_FRA, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'DEU') AS Straatnaam_DEU FROM Straat) QVIEW3
WHERE 
QVIEW1.StraatNaamID IS NOT NULL AND
(QVIEW1.StraatNaamID = QVIEW2.StraatNaamID) AND
QVIEW2.Straatnaam_DEU IS NOT NULL AND
(QVIEW1.StraatNaamID = QVIEW3.StraatNaamID)
UNION ALL
SELECT 
   1 AS "straatQuestType", NULL AS "straatLang", (CAST ('http://data.vlaanderen.be/id/straatnaam/' as varchar(8000)) + CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(QVIEW1.StraatNaamID AS VARCHAR(8000)), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D') as varchar(8000))) AS "straat", 
   3 AS "naamQuestType", 'nl' AS "naamLang", CAST(QVIEW2.Straatnaam_NDL AS VARCHAR(8000)) AS "naam", 
   3 AS "uuidQuestType", NULL AS "uuidLang", (CAST ('straatnaam-' as varchar(8000)) + CAST(QVIEW1.StraatNaamID as varchar(8000))) AS "uuid"
 FROM 
(SELECT StraatID AS StraatNaamID, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'NLD') AS Straatnaam_NDL, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'FRA') AS Straatnaam_FRA, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'DEU') AS Straatnaam_DEU FROM Straat) QVIEW1,
(SELECT StraatID AS StraatNaamID, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'NLD') AS Straatnaam_NDL, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'FRA') AS Straatnaam_FRA, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'DEU') AS Straatnaam_DEU FROM Straat) QVIEW2,
(SELECT StraatID AS StraatNaamID, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'NLD') AS Straatnaam_NDL, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'FRA') AS Straatnaam_FRA, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'DEU') AS Straatnaam_DEU FROM Straat) QVIEW3
WHERE 
QVIEW1.StraatNaamID IS NOT NULL AND
(QVIEW1.StraatNaamID = QVIEW2.StraatNaamID) AND
QVIEW2.Straatnaam_NDL IS NOT NULL AND
(QVIEW1.StraatNaamID = QVIEW3.StraatNaamID)
UNION ALL
SELECT 
   1 AS "straatQuestType", NULL AS "straatLang", (CAST ('http://data.vlaanderen.be/id/straatnaam/' as varchar(8000)) + CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(QVIEW1.StraatNaamID AS VARCHAR(8000)), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D') as varchar(8000))) AS "straat", 
   3 AS "naamQuestType", 'fr' AS "naamLang", CAST(QVIEW2.Straatnaam_FRA AS VARCHAR(8000)) AS "naam", 
   3 AS "uuidQuestType", NULL AS "uuidLang", (CAST ('straatnaam-' as varchar(8000)) + CAST(QVIEW1.StraatNaamID as varchar(8000))) AS "uuid"
 FROM 
(SELECT StraatID AS StraatNaamID, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'NLD') AS Straatnaam_NDL, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'FRA') AS Straatnaam_FRA, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'DEU') AS Straatnaam_DEU FROM Straat) QVIEW1,
(SELECT StraatID AS StraatNaamID, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'NLD') AS Straatnaam_NDL, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'FRA') AS Straatnaam_FRA, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'DEU') AS Straatnaam_DEU FROM Straat) QVIEW2,
(SELECT StraatID AS StraatNaamID, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'NLD') AS Straatnaam_NDL, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'FRA') AS Straatnaam_FRA, (SELECT Naam FROM Straatnaam WHERE Straatnaam.StraatID = Straat.StraatID AND Straatnaam.TaalISOCode = 'DEU') AS Straatnaam_DEU FROM Straat) QVIEW3
WHERE 
QVIEW1.StraatNaamID IS NOT NULL AND
(QVIEW1.StraatNaamID = QVIEW2.StraatNaamID) AND
QVIEW2.Straatnaam_FRA IS NOT NULL AND
(QVIEW1.StraatNaamID = QVIEW3.StraatNaamID)
) SUB_QVIEW
ORDER BY SUB_QVIEW."uuid"
`

**Comment by skomlaebri** [comment]
Clearly the SQL is  wrong, can you attach the complete log?
Thanks

**Comment by PaulZH** [comment]
I have more insight.

If the source value is a string then a filter works and can be seen in the generated SQL

`CAST(QVIEW2.Straatnaam_NDL AS VARCHAR(8000)) AS "naam"`

becomes using a filter

`'Vijverstraat' AS "naam"`

While the uuid field is composed as a concatenation.

 (CAST ('straatnaam-' as varchar(8000)) + CAST(QVIEW1.StraatNaamID as varchar(8000))) AS "uuid"

and a filter doesn't seem to influence that.

**Comment by PaulZH** [comment]
[the log file](http://mbx.cm/t/N2NVY)

**Comment by PaulZH** [comment]
The idea is now to add the concatenation in a view on the db. This should solve the issue. Or is there a workaround with the current approach trying to filter on a property of which the value is composed in the mapping.
`rr:predicateObjectMap [
    rr:predicate mu:uuid;
    rr:objectMap [
    rr:template "adres-{AdresID}" ;
    rr:termType rr:Literal
    ]
   ]
 ;   `

**Comment by skomlaebri** [comment]
Hi,
thanks for reporting the problem.
The other solution is, if you can modify  mapping and query, to create a new data property filtering only on the column
Example:
rr:predicateObjectMap [ rr:predicate :uuidValue; rr:objectMap [ rr:column "AdresID" ] ] ;

select * where { ?straat a <http://data.vlaanderen.be/ns/adres#StraatNaam> . ?straat <http://data.vlaanderen.be/ns/adres#geografischeNaam> ?naam. 
<http://mu.semte.ch/vocabularies/core/uuid> ?uuid .
?uuid <http://example.com/uuidValue> ?uuidv. FILTER (?uuidv = '1') } ORDER BY ?uuid

**Comment by bcogrel** [comment]
The relevant parts of Ontop have been significantly refactored since the time this issue has been raised, so this issue is probably gone.

If it still persists, feel free to re-open it.
