### ISSUE TITLE
Selecting "Get expansion this UCQ..." doesn't show the query expansion

### ISSUE THREAD

**Issue by johardi** [ontop/ontop#155]

**Comment by skomlaebri** [comment]
Can you provide an example?
At the moment we know that "Get expansion this UCQ..." does not return a result when the query is failing.

**Comment by johardi** [comment]
I have the mappings for each GroceryItem subclass and I could run the query. But as you can see, I didn't get the query expansion other than the original query. 

<img width="1277" alt="screen shot 2016-11-02 at 4 02 20 pm" src="https://cloud.githubusercontent.com/assets/5062950/19950637/f180ea54-a115-11e6-9cb9-a5543572ba69.png">

PS. You can have download the artifacts (h2, .owl, .obda) from [here](https://github.com/protegeproject/ontop-tutorial/wiki/Grocery-Tutorial).

**Comment by kontchakov** [comment]
Hi Josef

In this case, the rewriting (in the sense of DL) of the query absolutely correctly coincides with the original query. The various subclasses are handled on the level of T-mappings, which compile the class/property hierarchy into the user mappings. This makes the unfolded SQL more compact.

I assume that the generated SQL will contain a disjunction over various types of grocery items.

Best
Roman

**Comment by johardi** [comment]
Oww I see. I forgot about the T-mappings. Is there a case where this option would be useful?

**Comment by ghxiao** [comment]
If you have (tree witness) rewriting on, you can see the difference.
