### ISSUE TITLE
Issue: Syntax Error in Mapping Manager

### ISSUE THREAD

**Issue by samithaj** [ontop/ontop#156]
I followed the tutorial in https://github.com/ontop/ontop/wiki/Easy-Tutorial:-Using-Ontop-from-Protege and succesfully connected the database("Connection is OK when I press Test Connection button). But it gives me a syntax error for ontology mappings ("Syntax error: no viable alternative at input '.' Location: line 6 column 46). I tried with other expressions and found no luck. A screenshot is attached herewith presenting the error.
[image](http://i.imgur.com/7wRkJLs.jpg)

**Comment by ghxiao** [comment]
Could you try the following snippet? 

```
:book{bk_code} a :Book ; :bookTitle {bk_title} .
``` 

Otherwise, can send you mapping file to us?

**Comment by samithaj** [comment]
Now a different [error](http://i.imgur.com/gYHBkrz.png)
[books.owl](http://pastebin.com/hMj2v0UM)
[books.obda](http://pastebin.com/AuXAZWyM)

**Comment by ghxiao** [comment]
It seems that the prefixes of classes and properties are not synced. You just need to restart protege.

**Comment by samithaj** [comment]
Got it to working by changeing Active ontology Tab -> Ontology prefixes to our ontology IRI which was http://my.org/books#  , noticed that the path for our entities and the error has different IRI values. Maybe mention this in tutorial ?? (totally new to protégé that's why we missed this in first place)
Great tool ,thanks for helping !!
