### ISSUE TITLE
H2 Locate function not supported

### ISSUE THREAD

**Issue by zacharywhitley** [ontop/ontop#157]
The H2 LOCATE function is not supported. The equivalent POSITION function is supported.

**Comment by skomlaebri** [comment]
Hi,
both functions are currently not supported, or better a view will be generated and no optimization will be applied on it

**Comment by ZacharyWhitley** [comment]
Thanks. I noticed a warning when I used the LOCATE function so I tried the POSITION function to see if maybe only one was supported and I didn't recall seeing the same warning message with POSITION. Maybe I missed something.

**Comment by bcogrel** [comment]
Does not cause the creation of a black-box view anymore (see test https://github.com/ontop/ontop/commit/3c03b30ff5509c8504d84d25173ab7107e534ced)
