### ISSUE TITLE
Export to R2RML

### ISSUE THREAD

**Issue by peterjohnlawrence** [ontop/ontop#158]
When using xport to R2RML, if the mapping includes a rr:predicateMap, it gets exported as a rr:predicate instead.

For example, if mapping is :{x} :{y} {z} then the mapping is

:x rr:predicate :{x}

It should be instead

:x rr:predicateMap [ a rr:predicateMap ; rr:template :{x} ; rr:term rr:IRI ]

**Comment by ghxiao** [comment]
We need to fix OBDAMappingTransformer

**Comment by ghxiao** [comment]
Fixed by #162
