### ISSUE TITLE
OntopPRO generates duplicates resolving sparql query

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#163]
Hi, I am using the prepared bundle which contains Protege 5.0.0 and Ontop OBDA Protege plugin 1.18.0.
I'm experimenting unexpected results when I perform a sparql query. For example, in my ontology there is a class which represents a category and there is another class which represents an object that is related to a category. Basically I have the following relation:
`:Object :hasCategory :Category`
When I make the following sparql query
```
SELECT * WHERE { 
    ?category rdf:type :Category .
}
```
I expect that the results came from the database table where Category entities are stored. However, the results include this table and the table where Object entities are stored, creating a new Category for each Object. This fact generates duplicated results. I've checked the SQL translated query and it consists of the following:

```
SELECT 
   1 AS "sQuestType", NULL AS "sLang", ('http://www.example.com/ontology#category' || REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(QVIEW1."IDCATEGORY" AS VARCHAR(4000)), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS "s"
 FROM 
"SCHEMA"."OBJECT" QVIEW1
WHERE 
QVIEW1."IDCATEGORY" IS NOT NULL
UNION ALL
SELECT 
   1 AS "sQuestType", NULL AS "sLang", ('http://www.example.com/ontology#category' || REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(QVIEW1."IDCATEGORY" AS VARCHAR(4000)), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS "s"
 FROM 
"SCHEMA"."CATEGORY" QVIEW1
WHERE 
QVIEW1."IDCATEGORY" IS NOT NULL
```

It looks like categories are being created from object data and then from their own table. The UNION ALL clause causes duplicated results. Is correct this behaviour?

Note: This is a simplified case of the problem I am experimenting, my real  ontology is bigger.

**Comment by skomlaebri** [comment]
Hi,
can you tell us also how your mappings for :Category and :Object looks like?

**Comment by fanavarro** [comment]
Hi skomlaebri.
The mappings are similar to the following:

```
mappingId	Category
target		:category{IDCATEGORY} a :Category . 
source		SELECT IDCATEGORY
			FROM CATEGORY 

mappingId	Object
target		:object{IDOBJECT} a :Object ; :hasCategory :category{IDCATEGORY} .
source		SELECT IDOBJECT, IDCATEGORY
			FROM OBJECT 
```
I am going to develop this little test case in order to check if the behaviour I'm experimenting with the whole ontology occurs here too.

Thanks.

**Comment by fanavarro** [comment]
Hi all, I've develop the previous test case but the issue is not happening. I'm checked out that the problem appears when I use subclasses. The issue appear in the following test case:

The ontology is the following:
```
:Category
:Object
    :Object1
    :Object2
```
Where sibling classes are disjoined.

In the database are CATEGORY, OBJECT1 and OBJECT2 tables (OBJECT1 and OBJECT2 have the same structure with IDOBJECT and IDCATEGORY).

The mappings are the following:
```
mappingId	Category
target		:category{IDCATEGORY} a :Category . 
source		SELECT IDCATEGORY FROM Category 

mappingId	Object1
target		:object1{IDOBJECT} a :Object1 ; :hasCategory :category{IDCATEGORY} . 
source		SELECT IDOBJECT, IDCATEGORY FROM OBJECT1

mappingId	Object2
target		:object2{IDOBJECT} a :Object2 ; :hasCategory :category{IDCATEGORY} . 
source		SELECT IDOBJECT, IDCATEGORY FROM OBJECT2
```

In the database there are the following data:
CATEGORY TABLE:
![imagen](https://cloud.githubusercontent.com/assets/11376639/20960652/c24bf69a-bc61-11e6-9571-8d174599164c.png)

OBJECT1 TABLE:
![imagen](https://cloud.githubusercontent.com/assets/11376639/20960580/6bbbd7a0-bc61-11e6-9c05-68e49190ca52.png)

OBJECT2 TABLE:
![imagen](https://cloud.githubusercontent.com/assets/11376639/20960606/8e5de096-bc61-11e6-8346-eff1b060ba1e.png)

```
Then, when run the query
PREFIX : <http://www.semanticweb.org/fabad/ontologies/2016/11/untitled-ontology-52#>

select * where {
	?category a :Category .
} order by ?category
```
I get the following results, which are duplicated:
![imagen](https://cloud.githubusercontent.com/assets/11376639/20960751/3498cfa2-bc62-11e6-9cf3-e84bb5a61332.png)

Am I making any mistake?
Thanks in advance.

**Comment by skomlaebri** [comment]
Hi,
the redundant information is given by the fact that in your ontology you defined :hasCategory with range :Category. So I would expect that the information is extracted three times (from IDCATEGORY in Category, in OBJECT1 and in OBJECT2). If you want to avoid the duplicates you can use the select distinct in your sparql query.
You can also try  adding foreign keys to your tables for example 
ALTER TABLE OBJECT2
ADD FOREIGN KEY (IDCATEGORY) 
REFERENCES CATEGORY(IDCATEGORY) OBJECT1 
to allow ontop to do further optimizations

**Comment by fanavarro** [comment]
The issue has been solved by adding foreign keys to the database. In this case the problem was caused by the bad design of the database. Ontop works perfectly.

Thank you for your quick answer.
