### ISSUE TITLE
Protege - OnTop : Mappings are not effective when queried in SPARQL in Protege

### ISSUE THREAD

**Issue by SahilTrinity** [ontop/ontop#164]
1. I made 3 mappings in Protege under the OnTop mappings tab, all of them being almost similar in structure to each other, except that they talked about different columns and classes. When i fire SPARQL queries , I get results as if only the first mapping was present. Why does that happen ?

2. If this information helps : I deleted the first mapping to see if the result gets affected, but it didn't.  Am I supposed to do anything else other than saving the project for the query to execute using the lastest mappings ?

Thanks
Sahil Mathur
Trinity College, Dublin

**Comment by ghxiao** [comment]
Try restart the reasoner by "stop" and "start"? To make the changes effective, one needs to restart the Ontop reasoner.

**Comment by SahilTrinity** [comment]
Worked. Thanks a lot :-)
