### ISSUE TITLE
Problem with decimal formats

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#166]
Hi. I am having troubles with the mapping of a data property, whose range is xsd:decimal.
When I run a sparql query to retrieve these values, ontop fails. I've checked the generated SQL query and I have seen something like:

```
SELECT 
   3 AS "nombreClienteQuestType", NULL AS "nombreClienteLang", CAST(CAST('ELECTROINSA. SAL' AS VARCHAR(4000)) AS VARCHAR(4000)) AS "nombreCliente", 
   3 AS "descripcionArticuloQuestType", NULL AS "descripcionArticuloLang", CAST(CAST('ARTICULO 1001' AS VARCHAR(4000)) AS VARCHAR(4000)) AS "descripcionArticulo", 
   3 AS "tarifaAplicadaQuestType", NULL AS "tarifaAplicadaLang", CAST(CAST('3' AS VARCHAR(4000)) AS VARCHAR(4000)) AS "tarifaAplicada", 
   5 AS "valorPvpQuestType", NULL AS "valorPvpLang", CAST(4,5 AS VARCHAR(4000)) AS "valorPvp"
 FROM 
(SELECT 1 from dual) tdummy
```

As you can see, in the last line of the select statement, ontop includes (...)CAST(4,5 AS VARCHAR(4000))(...), managing the number "4.5"  as two different parameters to CAST. So it looks like the database is configured to use a comma (,) as decimal separator instead of a dot (.). This causes wrong queries.

I am not showing my complete ontology or mappings due to its complexity, but I'd want to know if this is a known issue or if I could configure ontop to manage it.

The database is oracle 11g, the column type is NUMBER(38,12), the datatype range is xsd:decimal. I have tried to make a minimal example, but I have not achieve that the generated SQL query includes the CAST statement, which is the point where it fails. However, I am getting results as "60,5"^^xsd:decimal, which includes the comma as decimal separator.

Thanks you very much.

**Comment by skomlaebri** [comment]
Hi, this is not a known issue. We need a minimal example to understand what is generating the problem (ontology and mappings only with the classes and properties involved). The fact that in your SQL generator appears the number "4,5" instead of a column name, makes me assume that you inserted this value on purpose in your mapping. Can you show us the related part from your mappings?

**Comment by fanavarro** [comment]
Hi skomlaebri, thanks for responding. 

I've discovered that the appearing of the number "4,5" is due to there is an individual in the ongology, so the final query is adding it. This is correct. However, ontop sparql queries are returning decimal numbers with a comma instead of a dot. These numbers are mapped to a datatype property whose range is xsd:decimal. This type must have a dot as decimal separator.

Filters are working with these values, but I'm wonder that if I could configure the presentation format in order to show a dot instead a comma as decimal separator.

Thanks!

**Comment by skomlaebri** [comment]
Hi, it is not possible to configure the presentation format in ontop. 
If you have access to the database I would suggest you change the global location of your database to change the format from comma to dot. Check [here](https://docs.oracle.com/cd/B19306_01/server.102/b14225/ch3globenv.htm) for more information

**Comment by fanavarro** [comment]
Thanks for your answer skomlaebri, I'll change the format in the database.
