### ISSUE TITLE
Sparql with join does not generate SQL translation and does not show results

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#168]
Hi Ontop team.
I have several mapping in my project that are not very orthodox due to the database structure... I'm modeling items, prices and clients who buy these items at a certain price. Each item has three prices and each client has a "rate", which is a number from 1 to 3 indicating what price is applied. The database has the following tables and columns:
Table ITEM contains:
![imagen](https://cloud.githubusercontent.com/assets/11376639/21561399/741890a6-ce6c-11e6-96b5-06aa79d8b145.png)

Table CLIENT contains:
![imagen](https://cloud.githubusercontent.com/assets/11376639/21561410/95c7296a-ce6c-11e6-922e-c040d0927c78.png)

The schema of the ontology is the following:
![imagen](https://cloud.githubusercontent.com/assets/11376639/21561475/43707120-ce6d-11e6-81c3-adc4f3bcaa03.png)

The class Client has a name and a rate.
The class Item has a name.
The class RateItemPrice represents a price of an item in a specific rate. It has an item, a rate and a price.
The class Rate represents the possible rates (in this case we have 3 rates).

The mappings are the following:
```
Client
    Template
         :client{IDCLIENT} a :Client ; :hasName {NAME} ; :hasRate :rate{RATE} . 
    SQL
        SELECT IDCLIENT, NAME, RATE FROM CLIENT
```

```
Item
    Template
        :item{IDITEM} a :Item ; :hasName {NAME} . 
    SQL
        SELECT IDITEM, NAME FROM ITEM
```

```
RateItemPrice
    Template
        :rate1 a :Rate . 
        :rate2 a :Rate .
        :rate3 a :Rate .

        :rate_item_price1_{IDITEM} a :RateItemPrice ; :hasRate :rate1 ; :hasPrice {PRICE1} . 
        :rate_item_price2_{IDITEM} a :RateItemPrice ; :hasRate :rate2 ; :hasPrice {PRICE2} .
        :rate_item_price3_{IDITEM} a :RateItemPrice ; :hasRate :rate3 ; :hasPrice {PRICE3} .
    SQL
        SELECT IDITEM, PRICE1, PRICE2, PRICE3 FROM ITEM
```

In the mapping of RateItemPrice I'm creating :rate1, :rate2 and :rate3 by hand without database information because I don't have a table indicating the possible rates, I have to infer this from the number of price columns from ITEM table.

Then, if I want to obtain the specific price of an item for a client, I make the following sparql query:
```
select * where {
	?client a :Client .
	?client :hasRate ?rate .
	?rip a :RateItemPrice .
	?rip :hasRate ?rate .
        ?rip :hasPrice ?price .
}
```
which has no results. Moreover, when I try to get the generated SQL for this query, I get an empty window:
![imagen](https://cloud.githubusercontent.com/assets/11376639/21561733/e45c473c-ce70-11e6-9ab8-260e470f8fbc.png)

However, if I make the following query:
```
select ?name ?rate where {
	?client a :Client .
	?client :hasRate ?rate .
	?client :hasName ?name .
}
```

I obtain:
![imagen](https://cloud.githubusercontent.com/assets/11376639/21561663/e65d4ef6-ce6f-11e6-8285-555499944345.png)

And, if I make this:
```
select ?rip ?rate where {
	?rip a :RateItemPrice .
	?rip :hasRate ?rate .
}
```
I obtain
![imagen](https://cloud.githubusercontent.com/assets/11376639/21561678/28705a18-ce70-11e6-8f56-0eb9b8ded08c.png)

So it looks like the rate uri's obtained in the last two queries are the same, but the first one  is not able to perform the join between Client and RateItemPrice rates.

Why is happening this? I suspect that this occurs due to the database design but, could I achieve this by using another approach?

Thank you very much in advance.

**Comment by fanavarro** [comment]
I have been debugging the application. I think the problem is the unfolding of the program after rewriting (getUnfolding method from QuestStatement class) on the line
`programAfterUnfolding = getUnfolding(programAfterRewriting);`
After that line, programAfterUnfolding does not have any rule.

In the class DatalogUnfolder, the method public int computePartialEvaluation(List<CQIE> workingList) is called. Working list only have one element that is deleted and readded several times in the method until `private List<CQIE> computePartialEvaluation(List<Term> currentTerms, CQIE rule, int[] resolutionCount, Stack<Integer> termidx, boolean parentIsLeftJoin)` returns a null result which provokes the end of the loop, maintaining workingList empty. After that, the program tries to generate the SQL query with the empty workingList, which generates an empty SQL.

I do not have the enough knolewdge about how Ontop is programmed in order to fix this. Even, I don't know if this is the expected behaviour.

Thanks in advance again.

**Comment by tirrolo** [comment]
Hi Francisco.

Note that "|:rate1" never unifies with the template ":rate{RATE}", since 
in OBDA theory the alphabet used for URI templates is disjoint with the 
set of database values (that is, no instantiation for {RATE} will ever 
correspond to that "1" hard-coded in the template).|

Hence, the sets of solution mappings for the BGP

|{ ?client :hasRate ?rate . ?rip :hasRate ?rate . }|

is always empty, regardless the data instance, given your mappings.
||

One solution that it's very close to the spirit of your mappings is to 
split the RateItemPrice mapping and use SQL fixed-value columns, e.g.

hasRateItemPrice1

Template
        :rate{RATE} a Rate.
        :rate_item_price1_{IDITEM} a :RateItemPrice ; :hasRate 
:rate{RATE} ; :hasPrice {PRICE1} .

SQL
         SELECT IDITEM, PRICE1, 1 AS RATE FROM ITEM

hasRateItemPrice2

Template
         :rate{RATE} a Rate.
         :rate_item_price2_{IDITEM} a :RateItemPrice ; :hasRate 
:rate{RATE} ; :hasPrice {PRICE2} .

SQL
         SELECT IDITEM, PRICE2, 2 AS RATE FROM ITEM

Etc.

For the sql queries I used a mysql syntax to express fixed-values 
columns. I don't know what is the syntax for your specific RDBMS.

I am not sure if ontop fully supports fixed-values columns, though. My 
colleagues working in the implementation might be more helpful in this 
point.

Regards.

**Comment by fanavarro** [comment]
Thanks for your answer Tirrolo.

I did not know that a hard-coded template does not match with another that comes from the database even if the final string is the same. It works by using literals in the SQL query so thanks for your suggestion.

Regards,
Francisco Abad.
