### ISSUE TITLE
Is possible to hide the information about database connection  in obda file?

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#171]
Hello ontop team,

I'm wondering if it would be possible to encrypt the password in the obda file generated by OntopPro. For now, the information about the database connection (user, pass, url and driver) is stored in this file without any kind of security so, people that can see the file could make connections directly to the database.
Is there any mechanism to avoid this?

Thanks.

**Comment by ghxiao** [comment]
Hi,

For the current version of Ontop, we don't have any way to hide connection information. 

We are working a new way of modeling connection information by separating them into a property file so that the user can handle these files differently.

**Comment by fanavarro** [comment]
Thanks for your reply, ghxiao.
I'll wait for the next version then.

Cheers.
