### ISSUE TITLE
Ontop export to r2rml interpreting <template1> a <template2> incorrectly

### ISSUE THREAD

**Issue by peterjohnlawrence** [ontop/ontop#172]
In cases where the target includes a patterns such as {template1} a {template2} . or {template1} rdf:type {template2} . the Ontop export to r2rml will incorrectly create the r2rml:predicateObjectMap as follows. Bold highlights the problem area

  rr:predicateObjectMap [
      rdf:type rr:PredicateObjectMap ;
      rr:objectMap [
          rdf:type rr:ObjectMap ;
          rdf:type rr:TermMap ;
          rr:datatype rdfs:Class ;
          **rr:template "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" ;**
          rr:termType rr:IRI ;
        ] ;
      **rr:predicate rdf:type ;**
    ] ;
 
 The correct mapping is as follows (bold to indicate the corrected values)
 
  r2rml:predicateObjectMap [
      rdf:type r2rml:PredicateObjectMap ;
      r2rml:objectMap [
          rdf:type r2rml:ObjectMap ;
          rdf:type r2rml:TermMap ;
          **r2rml:template "http://inova8.com/ref/def/subdomain/{SDOM}" ;**
          r2rml:termType r2rml:IRI ;
        ] ;
      **r2rml:predicate rdf:type  ;**
    ] ;

**Comment by skomlaebri** [comment]
Same as issue #204 .
