### ISSUE TITLE
How to select charset in OntopPro

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#174]
### Description

I'm getting the following message when I start the Ontop reasoner in Protege:
```
Level:       ERROR
Time:        1486123041029
Message:     An error occurred during reasoning: Lexical error at line 5, column 16.  Encountered: "\u00d1" (209), after : "".
net.sf.jsqlparser.parser.TokenMgrError
StackTrace:  
    net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:1703)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:10313)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3_13(CCJSqlParser.java:7573)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_163(CCJSqlParser.java:7617)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_71(CCJSqlParser.java:6504)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_386(CCJSqlParser.java:6593)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_346(CCJSqlParser.java:6632)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_347(CCJSqlParser.java:6381)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_304(CCJSqlParser.java:6709)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_243(CCJSqlParser.java:7221)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_157(CCJSqlParser.java:6716)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_69(CCJSqlParser.java:6900)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_3_16(CCJSqlParser.java:7251)
    net.sf.jsqlparser.parser.CCJSqlParser.jj_2_16(CCJSqlParser.java:5888)
    net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1040)
    net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1033)
    net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:75)
    net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:55)
    net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
    it.unibz.inf.ontop.sql.api.ParsedSQLQuery.<init>(ParsedSQLQuery.java:88)
    it.unibz.inf.ontop.parser.SQLQueryShallowParser.parse(SQLQueryShallowParser.java:30)
    it.unibz.inf.ontop.utils.MappingParser.getRealTables(MappingParser.java:62)
    it.unibz.inf.ontop.owlrefplatform.core.Quest.setupRepository(Quest.java:548)
    it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.prepareQuestInstance(QuestOWL.java:271)
    it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.prepareReasoner(QuestOWL.java:452)
    it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.init(QuestOWL.java:148)
    it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.<init>(QuestOWL.java:174)
    it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLFactory.createReasoner(QuestOWLFactory.java:107)
    it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLFactory.createReasoner(QuestOWLFactory.java:92)
    it.unibz.inf.ontop.protege.core.OntopOWLFactory.createReasoner(OntopOWLFactory.java:34)
    it.unibz.inf.ontop.protege.core.OntopOWLFactory.createReasoner(OntopOWLFactory.java:21)
    org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20)
    org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:427)
    org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:382)
    java.lang.Thread.run(Thread.java:745)
```
This is happening because there is a column in the database whose name contains a special character (Ñ). I think that this is a charset encoding problem so I wonder if there is a way to specify it in Ontop or Quest.
### Steps to Reproduce

1. Create a table whose columns contains special characters. For example, a table called "PERSONA" with the following columns:
![imagen](https://cloud.githubusercontent.com/assets/11376639/22591394/976e4776-ea14-11e6-8585-0c56a678e041.png)

2. Create a new ontology with the class "Persona" and with the data type properties "tieneApellidos", "tieneNombre" and "tieneAño".

3. Create the mappings between PERSONA table and Persona class:
![imagen](https://cloud.githubusercontent.com/assets/11376639/22591832/daf41d70-ea16-11e6-9508-d5bb260054d5.png)

4. Start the reasoner

**Expected behavior:** The reasoner should start and keep active.

**Actual behavior:** Reasoner initialization failed and it throws the exception shown in the description of the issue.

**Reproduces how often:** This issue is happening when the letter "Ñ" appears in the source (SQL query) of the mapping. The reasoner can initialize without problems when the mapping is the following:
![imagen](https://cloud.githubusercontent.com/assets/11376639/22591950/952fa8b2-ea17-11e6-9bff-8a9b3b5803c3.png)

### Versions

I'm using Protege 5.0.0 with OntopPro 1.18.0, which were downloaded with the Ontop + Protege bundle. The database is Oracle 11g.

**Comment by skomlaebri** [comment]
Thanks for reporting the problem. The issue appears with "Ñ" uppercase, we need to update our version of JSQLParser to solve the problem, it will be modified for the next release.

**Comment by skomlaebri** [comment]
As a temporary solution, it seems that adding quotes around the column name does not generate the problem. Try using as source query SELECT ID, NOMBRE, APELLIDO, to_char("AÑO_NACIMIENTO", 'YYYY-MM-DD')  AS "AÑO_NACIMIENTO" FROM PERSONA .

**Comment by fanavarro** [comment]
Thanks @skomlaebri. The temporary solution works perfectly, I do not have any problem by adding the quotes to the SQL part of the mappings.
Should I wait for the next release, in which this will be completely fixed, to close this issue?

**Comment by bcogrel** [comment]
I am closing the issue since it is old and the JSQLParser version has been updated in the meantime. 

Feel free to re-open it if the problems persists.
