### ISSUE TITLE
Query manager inside the Ontop SPARQL tab shows duplicated entries

### ISSUE THREAD

**Issue by Piiit** [ontop/ontop#175]
### Description

The query manager inside the Ontop SPARQL tab shows duplicated entries. That is, it loads the *.q file, but does not empty the list before inserting it a second time.
![auswahl_056](https://cloud.githubusercontent.com/assets/6096063/22628619/4c086b58-ebd7-11e6-9a9d-80f0c9ffdf20.jpg)
 

### Steps to Reproduce

1. Click on the menu: File > Open recent... and choose any owl file there 
2. Repeat step no. 1, and answer the dialog "...open ontology in the current window" with yes
3. Go to the tab "Ontop SPARQL"

NB: Also File > Open... with any other owl file (if a q-file is present) has the same effect.

**Expected behavior:** Their should be exactly those entries that are present in the *.q file inside the Query Manager

**Actual behavior:** see screenshot above, duplicate entries exist

**Reproduces how often:** Happens every time

### Versions

Which version of Ontop are you using and in which setting (Protege, SPARQL endpoint, Cli, Java API, ...)
Protege Desktop Version 5.0.0, Build  
Java: JVM 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13  Memory: 466M 
Language: de, Country: DE 
Framework: Apache Software Foundation (1.7)  
OS: linux (4.4.9-040409-generic) 
Processor: x86-64
Plugin: HermiT (1.3.8.413) 
Plugin: Existential Query (2.0.0) 
Plugin: SWRLTab Protege 5.0+ Plugin (1.0.3) 
Plugin: matrix (4.0.0) 
Plugin: OWLViz (5.0.3) 
Plugin: Cellfie Protege 5.0+ Plugin (2.0.0) 
Plugin: OntoGraf (2.0.3) 
Plugin: DL Query (3.0.1) 
Plugin: OWLAPI RDF Library (2.0.2) 
Plugin: Ontop OBDA Protégé plugin (1.18.1.SNAPSHOT) 
Plugin: Browser View (OWLDoc) (3.0.3) 
Plugin: Explanation Workbench (3.0.0) 
Plugin: Protege SPARQL Plugin (2.0.1) 
Plugin: OWL Code Generation Plug-in (2.0.0) 
OWL API Version: 4.2.5.20160517-0735

**Comment by kontchakov** [comment]
Fixed with 478b0a660f6f1e98e660d9c75bcce5d4a7bd5f72.
