### ISSUE TITLE
Not compatible with Apache Drill JDBC

### ISSUE THREAD

**Issue by Dedli** [ontop/ontop#176]
### Description

I want to query Apache Drill, but the SQL Queries are not valid for Apache Drill when starting the Reasoner. It queries for  "TABLE_SCHEMA like 'MASTER'" and should query for "TABLE_SCHEMA like 'MYSQL.MASTER'"

### Steps to Reproduce

1. Import the Apache Drill JDBC (from <DRILL_ROOT>/jars/jdbc-driver/drill-jdbc-all-<version>.jar) into Ontop Plugin for Protegé 5.0.1
2. Configure the JDBC Driver in Datasource Manager (Connection URL: jdbc:drill:drillbit=localhost Username: admin, Password: <SECRET>, Driver class: org.apache.drill.jdbc.Driver )
3. Create a Mapping for existing ontology
4. Start the Reasoner
5. Reasoner Failed

**Expected behavior:** starting the Reasoner successfully

**Actual behavior:** Reasoner failed with:  ERROR OWLReasonerManager    An error occurred during reasoning: it.unibz.inf.ontop.model.OBDAException: java.lang.RuntimeException: Definition not found for table 'mysql.master.tb_books'..

**Reproduces how often:** Happend every time.

### Versions

Ontop Version: 1.18.0
Apache Drill: 1.9.0
JAVA Version: 1.8.0_121
OS: Ubuntu 16.04.1 LTS

**Comment by ghxiao** [comment]
Hi @Dedli ,

We are not supporting Apache Drill yet. We were investigating Drill and we realized supporting Drill is not a trivial task as the JDBC interface of Drill does not provide enough metadata for ontop.
