### ISSUE TITLE
Ontop SPARQL query showing results of previous mappings that were removed  & similar for Materialize Query

### ISSUE THREAD

**Issue by SahilTrinity** [ontop/ontop#177]
There were different updates in mappings under the mapping manager subtab under Ontop mappings tab. But later they were deleted. The reasoner was re-started, the project was saved (all PnC of these 2 things), but the query still shows the previous mappings and previous versions of scopings done for indentifiers (e.g {<http://xyz.org>_classId_}.

The same issue is observed when you choose Materialize Triples in OnTop drop down list on the menu bar. The generated file contains triples from deleted mappings. 

### Steps to Reproduce

1. create a simple ontology, object/data properties
2. connect to a relational database, create mappings under the mapping manager tab
3. keep saving (not save as) the project. modify the mappings slightly. e.g :something :mapsTo :somethingElse can be changed to :somethingElse :mapsTo :something
4. run a sparql query e.g SELECT * WHERE {:x :mapsTo :y}
5. Materialize Query - from the Ontop drop down list in the menu bar.

**Expected behavior:** shows output based on the last saved mapping. 

**Actual behavior:** shows both the output based on current mapping and its previous version. 

**Reproduces how often:** [Yes]

### Attached material
<img width="713" alt="screen shot 2017-02-16 at 11 07 07 a m" src="https://cloud.githubusercontent.com/assets/24457662/23019004/44af8f76-f438-11e6-8d9e-6c76df807931.png">

### Versions

Protege 5.0 + plugin V2.0.0
Ontop OBDA Protege plugin V1.18.0
Protege SPARQL plugin V2.0.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by skomlaebri** [comment]
Hi,
we have an open issue with syncronizing the reasoner #103 . When you do some changings to the mappings, make sure to stop and restart the reasoner otherwise the update will not have effect.

**Comment by SahilTrinity** [comment]
Hey,

Thanks, but as mentioned in my query, I already did that. The restarting does give me results from the new mapping, but it strangely also provides me the results from it previous iteration.
