### ISSUE TITLE
materialization not working for limit rows

### ISSUE THREAD

**Issue by wdduncan** [ontop/ontop#184]
### Description
[Description of the issue]

Using ontopcli, when is specify a query that limits rows, all rows are materialize. I am using ontop-distribution-1.18.0.1 and a MySQL community edition database.

My odba file has the following mapping:
mappingId	patient
target		patient:{STUDY_ID} rdf:type obo:OHD_0000012 ; rdfs:label {label}^^xsd:string .
source		select STUDY_ID, patient_name(STUDY_ID) as label from demographics order by STUDY_ID limit 50

### Steps to Reproduce

1. [First Step]
ontop materialize -d jdbc/mysql-connector-java-5.1.31-bin.jar -o out.owl -t NDPBRN.owl -m vdw.obda

**Expected behavior:** [What you expect to see]

I expect that only the fist 50 patients would be materialized.

**Actual behavior:** [What actually happens]

All patients are materialzed.

**Reproduces how often:** [Does it happen every time?]

Every time.

### Attached material

Informations about the attachments (ontology, mappings and queries that are necessary to reproduce the problem)
Provide the log file (more information on how to obtain it in the guidelines)

### Versions

Which version of Ontop are you using and in which setting (Protege, SPARQL endpoint, Cli, Java API, ...)

ontop-distribution-1.18.0.1 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ghxiao** [comment]
"ORDER BY" and "LIMIT" in the mappings  are ignored by ontop now. We need to see how to support them. It won't be an trivial extension.
