### ISSUE TITLE
ontopcli - ontop bootstrap?

### ISSUE THREAD

**Issue by wdduncan** [ontop/ontop#185]
The documentation is unclear on what ontop bootstrap does in the ontopcli.

Questions:

1. What you mean by bootstrap?
2. What format should the base uri have? 
Should it be:
 ontop bootstrap -b http://example.com ...

**Comment by ghxiao** [comment]
1. bootstrapping is to generate ontologies and mappings out of an existing database following the principle of W3C direct mapping specification: https://www.w3.org/TR/rdb-direct-mapping/

2. base iri can be an arbitrary IRI. You example works
