### ISSUE TITLE
ontopcli - ontop materialize creates punned classes

### ISSUE THREAD

**Issue by wdduncan** [ontop/ontop#186]
### Description

When I use ontopcli to materialize the triples, the output includes individuals with same URIs as my class names. That is, the classes have been punned as individuals.

Usng ontop-distribution-1.18.0.1 and MySQL community edition.

### Steps to Reproduce

ontop materialize -d jdbc/mysql-connector-java-5.1.31-bin.jar -o out.owl -t NDPBRN.owl -m vdw.obda
[vdw.obda.txt](https://github.com/ontop/ontop/files/887801/vdw.obda.txt)

[NDPBRN.owl.txt](https://github.com/ontop/ontop/files/887805/NDPBRN.owl.txt)
[out.owl.txt](https://github.com/ontop/ontop/files/887806/out.owl.txt)

**Reproduces how often:** [Does it happen every time?]

Every time

### Attached material

Informations about the attachments (ontology, mappings and queries that are necessary to reproduce the problem)
Provide the log file (more information on how to obtain it in the guidelines)

### Versions

Which version of Ontop are you using and in which setting (Protege, SPARQL endpoint, Cli, Java API, ...)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ghxiao** [comment]
Can you give an example of IRI in your file?

I don't see any problem in your mapping. It might be from the original ontology.

**Comment by wdduncan** [comment]
In the attached file see:

line 6240: <http://purl.obolibrary.org/obo/OBI_0000070> rdf:type owl:Class ;
line 16031: <http://purl.obolibrary.org/obo/OBI_0000070> rdf:type owl:NamedIndividual ;

[out.owl.txt](https://github.com/ontop/ontop/files/888363/out.owl.txt)

**Comment by fanavarro** [comment]
Hi, this is happening to me too.
I resolved it by modifying the method runWithSingleFile of OntopMaterialize.java in ontop-cli (the method I was using). Before I add the QuestOWLIndividualAxiom to the materialized ontology, I check if the uri of the subject of the axiom exists as a class or as a property in the ontology, in which case I do not add the axiom to the materialized ontology.

It would be great if things like these could be parameterized. I hope my comment can be helpful.

Greetings,
Fran.

**Comment by ghxiao** [comment]
@fanavarro Hi good know that you already have a solution. Do you want to make a pull request?

**Comment by fanavarro** [comment]
Hi @ghxiao. My solution was a quick fix that only affects to onto-cli module. I think I'd have to find a better solution for this by modifying the QuestMaterializer class in order to perform the same actions from the different modules. I'd try to implement it this morning.

**Comment by fanavarro** [comment]
Hi again @ghxiao , I've discovered that this behavior is provoked by the option  "setQueryingAnnotationsInOntology" set as true in the Quest reasoner used by the materializer. I've submitted a pull request (#189) with this option set as false. Only one line has changed and it fix this issue and #183. Is there any reason to set this option as true in the materialization process?

**Comment by ghxiao** [comment]
Fixed by #189
