### ISSUE TITLE
running build-release.sh

### ISSUE THREAD

**Issue by wdduncan** [ontop/ontop#187]
After I run the build-release.sh script (in the repo) where are the new build files placed?

I also would like to build the development version of ontop-cli. I tried running the following from the ontop-cli directory:

mvn bundle:bundle

The terminal printed out the message:

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ontop-cli 1.18.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-bundle-plugin:3.0.1:bundle (default-cli) @ ontop-cli ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.415 s
[INFO] Finished at: 2017-04-01T12:57:40-04:00
[INFO] Final Memory: 23M/332M
[INFO] ------------------------------------------------------------------------

But where is the ontop are the new files created?

**Comment by ghxiao** [comment]
The bundles are placed in the directory of quest-distribution
