### ISSUE TITLE
ontopro

### ISSUE THREAD

**Issue by fabioguilherme** [ontop/ontop#191]
Hello, i´m having some problems creating some sparql querys.
Using this query:
PREFIX : <http://www.ship.org#>
select * where{
	?i a :Ship ; :hasCountry ?country ; :shipImo ?imo ; :hasOwner ?owners .
}
 I get results on ontop sparql and on sparql query.
But if i specify the values for the type of class, i only get results in sparql query.
Why i´m having this results?

**Comment by skomlaebri** [comment]
Hi the problem will be solved in the next release

**Comment by fabioguilherme** [comment]
hey, can you tell when it will be the next release?
