### ISSUE TITLE
Ontop reasoner unable to find column name

### ISSUE THREAD

**Issue by CorentinK** [ontop/ontop#192]
Hello,

When i run the ontop reasoner this error message appears:

![error ontop](https://cloud.githubusercontent.com/assets/29048168/26559797/b340f094-44a9-11e7-8f42-46a87125a460.jpg)

Even though the SQL query seems to work perfectly. I think it is because in my table, the variable observationId include an uppercase "I" that the reasoner cannot deal with.

Do you have any solutions or suggestions? knowing that I cannot change anything in the database.

Many thanks by advance,

Kind regards,

Corentin Kuster

**Comment by ghxiao** [comment]
Hi,

Which database engine are you using?

Could you copy/paste that particular mapping?

**Comment by CorentinK** [comment]
Hi,

I work with InnoDB as storage engine for MySQL database.

The mapping:

target		usa:{observationId} a usa:AbsoluteScore ; dul:hasRegionDataValue {value}^^xsd:double . 
source		SELECT numericvalue.* FROM numericvalue,observation,series,sensorclassifier WHERE numericvalue.observationId = observation.observationId AND observation.seriesId = series.seriesId AND series.procedureId = sensorclassifier.sensorId AND sensorclassifier.classifierLabel = 'observationType' AND sensorclassifier.classifierValue= 'AbsoluteScore'

Regards,

Corentin

**Comment by kontchakov** [comment]
Hi Corentin

Try using 
target	usa:{observationId} a usa:AbsoluteScore ; dul:hasRegionDataValue {value}^^xsd:double .
source	SELECT numericvalue.observationId as observationId,  numericvalue.value as value  FROM numericvalue,observation,series,sensorclassifier WHERE numericvalue.observationId = observation.observationId AND observation.seriesId = series.seriesId AND series.procedureId = sensorclassifier.sensorId AND sensorclassifier.classifierLabel = 'observationType' AND sensorclassifier.classifierValue= 'AbsoluteScore'

(i.e., expand * in the query with appropriate column aliases).

Best
Roman

**Comment by CorentinK** [comment]
Hi Roman,

I tried with your recommandation but I still get the same error message "Unable to find column name for variable: observationId".

Corentin

**Comment by ghxiao** [comment]
Hi @CorentinK ,

This might be related to ansi-mode. Give it a try

https://github.com/ontop/ontop/wiki/ObdalibPluginJDBC#ansi-mode-quotes-and-mysql

**Comment by CorentinK** [comment]
Hi @ghxiao,

I have tried with and without the ANSI mode and it does not seems to make any difference. Apart from changing my column name, I do not know how to fix this problem.

Corentin

**Comment by CorentinK** [comment]
Hi all,

Here is the error log

> Error in mapping with id: MAPID-393492294b454a4cbded04a58d848069#6ad5c35d3a07464aa8caff632074a02b 
>  Description: Unable to find column name for variable: observationid 
> Mapping: [SELECT numericvalue."observationId", numericvalue."value" FROM numericvalue, observation, series, sensorclassifier WHERE numericvalue.observationId = observation.observationId AND observation.seriesId = series.seriesId AND series.procedureId = sensorclassifier.procedureId AND sensorclassifier.classifierLabel = 'observationType' AND sensorclassifier.classifierValue = 'AbsoluteScore' ==> [http://www.semanticweb.org/corentin/ontologies/2016/11/urban_sustainability_assessment#AbsoluteScore(URI("http://www.semanticweb.org/corentin/ontologies/2016/11/urban_sustainability_assessment#absolutescore/{}/",observationId))]]
> 
> 	at it.unibz.inf.ontop.utils.Mapping2DatalogConverter.constructDatalogProgram(Mapping2DatalogConverter.java:133) ~[na:na]
> 	at it.unibz.inf.ontop.owlrefplatform.core.QuestUnfolder.setupInVirtualMode(QuestUnfolder.java:96) ~[na:na]
> 	at it.unibz.inf.ontop.owlrefplatform.core.Quest.setupRepository(Quest.java:609) ~[na:na]
> 	... 12 common frames omitted

What is the "Mapping2DatalogConverter" used for? Can the issue come from there?

Best regards,

Corentin

**Comment by skomlaebri** [comment]
Hi,  can you send us the complete log file? Here the instruction on how to obtain it https://github.com/ontop/ontop/wiki/BugReport#how-to-generate-the-log-file

**Comment by CorentinK** [comment]
Hi,

Here is a sample of the log file.   Crtl+F and "MAPID-AbsoluteScore" to spot the mapping issue.

[protege.txt](https://github.com/ontop/ontop/files/1054441/protege.txt)

Corentin

**Comment by kontchakov** [comment]
Hi Corentin

Thanks for the log. Unfortunately, it does not contain the most interesting fragment - the metadata information. Guohui will e-mail you instruction on how to obtain that.

Best
Roman

**Comment by skomlaebri** [comment]
Hi @CorentinK, can you try [this version](https://drive.google.com/open?id=0B4ugqY9z55RwdWc0aDdxVXJMWDQ) of the ontop plugin and see if it works?
To run it you need to substitute the ontop jar file (it.unibz.inf.ontop.protege-1.18.0.jar) in the folder _plugins_ of Protege with the one that I just sent to you (the location of the folder can vary based on your Protege version and operating system).

If it still does not work, please send us the debug information. 
To unable the debug mode in Protege follow these steps:

You should go to the folder _conf_ of Protege and modify the line of the _logback.xml_ file from ```<root Level="info">``` to ```<root Level ="debug">```
When you restart Protege you will have more information in the command line, that can be useful to understand the problem.
You can send us the generated log file from Protege starting from _Window -> Show log... -> Show log file -> protege.log_

**Comment by CorentinK** [comment]
Hi,

It seems to work with this new version of the plugin. No error message. Thanks a lot!

Here is  the more detail log file of the error in case you still wanted to work on the issue.
[log error.txt](https://github.com/ontop/ontop/files/1058535/log.error.txt)

Thank you very much for your help!

Corentin

**Comment by ghxiao** [comment]
Perfect! The issue was actually already fixed by @kontchakov some time ago in a separate branch.
The fix will be included in the next stable release.
