### ISSUE TITLE
Cannot Install teiid Eclipse Plugin

### ISSUE THREAD

**Issue by lilylakshi** [ontop/ontop#193]
I was following instructions on https://github.com/ontop/ontop/wiki/teiid and it does not install successfully. Eclipse Install New Software dialog says 'Cannot perform operation. Computing alternate solutions, may take a while'. Tried this with Eclipse 4.4 as well as Eclipse 4.6.

I get this error while using the teiid zip file 'teiid-designer-8.0.0.Final-v20121212-1505-H1987.zip' while using the web link does not display any available plugins.

Any help regarding this is much appreciated.

**Comment by skomlaebri** [comment]
Hi,  the guide is old and not updated, I would suggest you to contact  Teiid support  for the correct  installation.

**Comment by lilylakshi** [comment]
Thanks!
