### ISSUE TITLE
Receiving Generated SQL Queries

### ISSUE THREAD

**Issue by lilylakshi** [ontop/ontop#194]
May I please know if there is a way to receive the generated SQL queries when SPARQL queries are input? I want to use those SQL queries in my own application before sending them to the database.

Any help is much appreciated.

**Comment by skomlaebri** [comment]
If you are using Protégé you can obtain the SQL with a right click on your SPARQL query in the query editor ( get sql translation).

**Comment by lilylakshi** [comment]
Thanks! I was wondering if I could have the SQL translation programmatically.

**Comment by ghxiao** [comment]
@lilylakshi 

Hi, yes, you can get the SQL translation programmatically using the API of Ontop.

You can find a sample class here: https://github.com/ontop/ontop-api-examples/blob/master/src/main/java/org/semanticweb/ontop/examples/books/QuestOWL_OBDA_Example.java

I modified the sample code a little as below for your needs:

```java
try (QuestOWL reasoner = factory.createReasoner(ontology, config);
             QuestOWLConnection conn = reasoner.getConnection();
             QuestOWLStatement st = conn.createStatement();
        ) {
            String sqlQuery = st.getUnfolding(sparqlQuery);
            System.out.println();
            System.out.println("The input SPARQL query:");
            System.out.println("=======================");
            System.out.println(sparqlQuery);
            System.out.println();

            System.out.println("The output SQL query:");
            System.out.println("=====================");
            System.out.println(sqlQuery);

            QuestOWLResultSet rs = st.executeTuple(sparqlQuery);

            int columnSize = rs.getColumnCount();
            while (rs.nextRow()) {
                for (int idx = 1; idx <= columnSize; idx++) {
                    OWLObject binding = rs.getOWLObject(idx);
                    System.out.print(ToStringRenderer.getInstance().getRendering(binding) + ", ");
                }
                System.out.print("\n");
            }
            rs.close();
        }
```

**Comment by lilylakshi** [comment]
Thanks very much!
