### ISSUE TITLE
Duplicate atoms after rewriting affect final query size

### ISSUE THREAD

**Issue by dbilid** [ontop/ontop#195]
Hello,

I have come across a strange behaviour. You can test it with query 02.q from LUBM benhcmark you have here: https://github.com/ontop/iswc2014-benchmark

The datalog program that is given as input to the TreeWitnessRewriter is:

> ans1(x,y,z) :- http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateStudent(x), http://swat.cse.lehigh.edu/onto/univ-bench.owl#University(y), http://swat.cse.lehigh.edu/onto/univ-bench.owl#Department(z), http://swat.cse.lehigh.edu/onto/univ-bench.owl#member(z,x), http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf(z,y), http://swat.cse.lehigh.edu/onto/univ-bench.owl#undergraduateDegreeFrom(x,y)

and the output of the rewriting is:

> ans1(x,y,z) :- http://swat.cse.lehigh.edu/onto/univ-bench.owl#undergraduateDegreeFrom(x,y), http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateStudent(x), http://swat.cse.lehigh.edu/onto/univ-bench.owl#University(y), http://swat.cse.lehigh.edu/onto/univ-bench.owl#member(z,x), http://swat.cse.lehigh.edu/onto/univ-bench.owl#Department(z), http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateStudent(x), http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf(z,y), http://swat.cse.lehigh.edu/onto/univ-bench.owl#Department(z), http://swat.cse.lehigh.edu/onto/univ-bench.owl#University(y)

The output has been modified by duplicating the atoms for GraduateStudent, Department and University (no tree witnesses exist for this query), so I guess it is equivalent to the initial one. The problem is that this has an impact to the produced query after the unfolding. The final SQL query has 16 unions. If I just remove the duplicate atoms after rewriting, for example with this code before computePartialEvaluation in DatalogUnfolder:

`
		for (CQIE q : workingSet){
                        Set<Function> existingAtoms=new HashSet<Function>();
			for(int i=0;i<q.getBody().size();i++){
				if(!existingAtoms.add(q.getBody().get(i))){
					q.getBody().remove(i);
					i--;
				}
			}
		}`
The final query has only 4 unions and the number of answers is the same.

Best,
Dimitris

**Comment by ghxiao** [comment]
Hi Dimitris,

This sounds like the redundancy self-join elimination optimization is not fired. We will have a look.
