### ISSUE TITLE
the SQL script to generate the full IMDB database doesn't work

### ISSUE THREAD

**Issue by jesushd12** [ontop/ontop#198]
Hello I'm trying to reproduce the IMDB example but the link to the SQL script to generate the full IMDB database (requires a postgres database) doesn't work. 

Grettings

**Comment by ghxiao** [comment]
I confirm that the link obdavm.inf.unibz.it/mo/ does not work now. 
I checked that the files are still safe on the server. 
We will contact our IT support to figure out what is the problem.

**Comment by jesushd12** [comment]
Thanks !

**Comment by ghxiao** [comment]
Check again. It was due to a misconfiguration after upgrading the version of Apache server.

**Comment by jesushd12** [comment]
Yes, it worked. Thank you very much.
