### ISSUE TITLE
Is it possible to Enable Query Ontology Annotations in sesame workbench?

### ISSUE THREAD

**Issue by jesushd12** [ontop/ontop#201]
Hi, 
I'm using sesame workbench  with the ontop + jetty 8.1.9 bundle. I would like to know if it is possible to enable query ontology annotations as in protege plugin.

For example, the following query works well in Protege because I enabled the query ontology annotations in Ontop Preferences, but I haven't been enable to make it work in the Sparql endpoint. 

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mon: <http://localhost/ontologias/OntologiaMomentosV3#>
SELECT DISTINCT ?x0  WHERE {
  ?x0 rdf:type mon:Hoteles.
  ?x0 mon:se_encuentra_en ?x1.
  ?x1 rdfs:label "Ciudad Guayana"@es.
}

Grettings,

**Comment by skomlaebri** [comment]
Hi,
currently it is not possible to modify the preferences in the sesame workbech. It will be available soon with our next major release.
Cheers,
Sarah
