### ISSUE TITLE
Issues with unfolding the query into SQL

### ISSUE THREAD

**Issue by RaniRaven** [ontop/ontop#202]
I understood I had issue with trying to query literal over object.
[test - Copy.owl.txt](https://github.com/ontop/ontop/files/1161635/test.-.Copy.owl.txt)
[test - Copy.obda.txt](https://github.com/ontop/ontop/files/1161634/test.-.Copy.obda.txt)

Now there are several issues 
[1] trying to query with
PREFIX : <http://unit.hamama/test#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select ?x
where {
    ?x a :organization_name.
}

returns 
"SELECT 
   1 AS `xQuestType`, NULL AS `xLang`, CONCAT('http://unit.hamama/test#organization_name-', REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(QVIEW1.`name`, ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS `x`
 FROM 
`mycheck`.`virtual_organization` QVIEW1
WHERE 
QVIEW1.`name` IS NOT NULL"

which does not make much sense.

[2] However ,
trying to do this query 

PREFIX : <http://unit.hamama/test#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select ?x
where {
    ?x a :organization_name.
    ?x :name "xxy".
}

Does not return any results.

**Comment by skomlaebri** [comment]
Hi,
the first query is our correct translation of the sparql query in SQL.The replace functions are used to guarantee that the generated iri will be a valid iri. They are used to remove spaces or invalid symbols from the data. If you are using the api, it is possible to set the replace to false.

The second query does not return any result because you did not define the :name property inside your mapping. So the query cannot have any solution.

**Comment by RaniRaven** [comment]
Can you please explain how do I define the property ?
I followed every sample I could, and nothing helps.
There is the mapping :organization_name/{name} a :organization_name
I've checked it, and I cannot find any difference from all the other examples.
there is :name as data property ...
I cannot find what is wrong there.

**Comment by skomlaebri** [comment]
You should modify the mapping as:
 :organization_name/{name} a :organization_name; :name "{name}" .
select name from virtual_organization

otherwise  the ontop reasoner cannot know the value to assign to :name property

**Comment by RaniRaven** [comment]
Nor protege neither the obda model in java code will not take this format.
I cannot fix this issue, no matter what I try.

**Comment by skomlaebri** [comment]
you probably just have to add a space  before the semicolum
:organization_name/{name} a :organization_name ; :name "{name}" .

**Comment by RaniRaven** [comment]
ok, now that worked.
but still running the simple sparql query 
PREFIX : <http://unit.hamama/test#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?x
where {
    ?x a :organization_name; :name "xxy".
} 

doesn't return anything, and is not translated to any sql query.

**Comment by skomlaebri** [comment]
Please post the debug log, so I can see what is happening.

**Comment by RaniRaven** [comment]
ok, I had to restart the reasoner, and it is working now, just that this sparql query
PREFIX : <http://unit.hamama/test#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?x
where {
    ?x a :organization_name. ?x :name "xxy".
} 

is translated into this sql -
SELECT 
   1 AS `xQuestType`, NULL AS `xLang`, CONCAT('http://unit.hamama/test#organization_name/', REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST('xxy' AS CHAR(8000) CHARACTER SET utf8), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS `x`
 FROM 
`mycheck`.`virtual_organization` QVIEW1,
`mycheck`.`virtual_organization` QVIEW2
WHERE 
(QVIEW1.`name` = 'xxy') AND
(QVIEW2.`name` = 'xxy')
this seems rather inefficient, when I was trying to do a very simple thing.
why using 2 views for this

**Comment by skomlaebri** [comment]
I need the log to know what is going on, it could be an error in the mapping. Did you modify the mapping that you already have or did you just create a new one?

**Comment by Rani-Yaro** [comment]
I modified the mapping. I can create a new one also.
Although, I must say, that I haven't met this notation you offered any way in the documentation.

**Comment by RaniRaven** [comment]
I modified it and this is the error I am getting while trying to execute the query 
it.unibz.inf.ontop.model.OBDAException: Error executing SQL query: 
The last packet successfully received from the server was 515,316,829 milliseconds ago.  The last packet sent successfully to the server was 515,316,835 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
SQL query:
 SELECT 
   1 AS `xQuestType`, NULL AS `xLang`, CONCAT('http://unit.hamama/test#organization_name/', REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST('xxy' AS CHAR(8000) CHARACTER SET utf8), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS `x`
 FROM 
`mycheck`.`virtual_organization` QVIEW1,
`mycheck`.`virtual_organization` QVIEW2
WHERE 
(QVIEW1.`name` = 'xxy') AND
(QVIEW2.`name` = 'xxy')

###################################################
##    Debugging information (for the authors)    ##
###################################################

	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLStatement.executeTuple(QuestOWLStatement.java:110)
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:194)
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:161)
	at it.unibz.inf.ontop.protege.gui.action.OBDADataQueryAction$1.run(OBDADataQueryAction.java:152)


Note that the query produced is very weird -
SELECT 
   1 AS `xQuestType`, NULL AS `xLang`, CONCAT('http://unit.hamama/test#organization_name/', REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST('xxy' AS CHAR(8000) CHARACTER SET utf8), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS `x`
 FROM 
`mycheck`.`virtual_organization` QVIEW1,
`mycheck`.`virtual_organization` QVIEW2
WHERE 
(QVIEW1.`name` = 'xxy') AND
(QVIEW2.`name` = 'xxy')

As I do not understand how it was created or what does it mean select null and 1 as something.

**Comment by skomlaebri** [comment]
Hi, 
to generate the log file and send it to us:
Enable Protege log. You should go to the folder conf of Protege and modify the line of the logback.xml file from `<root Level="info">` to `<root Level ="debug">`. When you restart Protege you will have more information in the command line, that can be useful to understand the problem. You can send us the generated log file from Protege starting from Window -> Show log... -> Show log file -> protege.log

The SQL query is in this form, because it is used internally by ontop to generate the SPARQL results.

Does your table mycheck.virtual_organization have primary keys? If they are missing it could create problem in the performance.

**Comment by Rani-Yaro** [comment]
[protege_log.txt](https://github.com/ontop/ontop/files/1184745/protege_log.txt)
[org_test.obda.txt](https://github.com/ontop/ontop/files/1184750/org_test.obda.txt)
[org_test.owl.txt](https://github.com/ontop/ontop/files/1184751/org_test.owl.txt)

I've added a new test with only one table and 2 entities, this time I've put both the logs and obda/owl files.
It seems that now things are working but the optimization/reduction of the query.
In this sample, a rather simple query (to my eyes at least) :
PREFIX : <http://www.testing.org#>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

select ?y
where {
  ?x a :Organization.
  ?x:name "IRS".
  ?y :member ?x.
  ?y a :Person.
}

Is interpreted as the following SQL (which contains many views and is not reducted), can I understand why (cause I probably do something wrong here)
SELECT 
   1 AS "yQuestType", NULL AS "yLang", ('http://www.testing.org#Person/' || REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(qview3."person_name", ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS "y"
 FROM 
(SELECT DISTINCT organization_name FROM mytest.person_in_organization) qview1,
(SELECT DISTINCT organization_name FROM mytest.person_in_organization) qview2,
"mytest"."person_in_organization" qview3,
(SELECT DISTINCT person_name FROM mytest.person_in_organization) qview4
WHERE 
(qview1.organization_name = 'IRS') AND
(qview2.organization_name = 'IRS') AND
(qview3."organization_name" = 'IRS') AND
qview3."person_name" IS NOT NULL AND
(qview3."person_name" = qview4.person_name)

**Comment by kontchakov** [comment]
Removing DISTINCT from view definitions should help.

Roman

**Comment by Rani-Yaro** [comment]
It doesn't
 this is what I get after removing the distinct
SELECT 
   1 AS "yQuestType", NULL AS "yLang", ('http://www.testing.org#Person/' || REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(qview3."person_name", ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS "y"
 FROM 
"mytest"."person_in_organization" qview1,
"mytest"."person_in_organization" qview2,
"mytest"."person_in_organization" qview3,
"mytest"."person_in_organization" qview4
WHERE 
(qview1."organization_name" = 'IRS') AND
(qview2."organization_name" = 'IRS') AND
(qview3."organization_name" = 'IRS') AND
qview3."person_name" IS NOT NULL AND
(qview3."person_name" = qview4."person_name")

And more over, it seems like synchronization of the reasoner ain't working at all, I've to stop it and start it again.
I'm using the ontop reasoner last version.
It seems to me like I'm not operating something correctly, cause this is the very basic case, and I can't believe the optimizations are not working at all.
 BTW, why distinct has a problem ?

**Comment by skomlaebri** [comment]
Hi,
distinct is not currently supported by ontop. The best approach is to keep the mappings simple and add the distinct in the sparql query. I think your problem is you are not using the primary keys in your "mytest"."person_in_organization" table. Is that the case?  Use the primary key to build IRIs  so that you don't have to join to retrieve a non-primary key column.
Build the mappings as 
```
:Person/{id} a :Person ; :name {person_name}^^rdfs:Literal  ; :member :Organization/{organization_name} .
select id,  person_name, organization_name from mytest.person_in_organization

:Organization/{id} a :Organization ; :name {organization_name}^^rdfs:Literal . 
select id,  organization_name from mytest.person_in_organization
```

**Comment by Rani-Yaro** [comment]
That's because the model I present does not have a primary-key.
Is primary key a necessary element is order to have the optimization.
A graph can be represented by a set of edges & nodes, or solely by  a set of edges.
Given (a,b),(a,d),(b,c) may represent a graph containing 4 nodes, and 3 edges in this case.
Such a graph may be represented in RDB format of table containing only 2 columns of the format 
from_node, to_node, or may have some columns representing properties.
How do you offer to map such a table to ontop, cause there is no id column, and no PK at all ?

Does the optimization depend on the existence   of primary key ?
I am also wondering about your above suggestion, as a table may not contain more than one PK, how the mapping you offered can even work.

**Comment by Rani-Yaro** [comment]
Any answer to the above ?
Maybe a pointer to the code which should be changed to deal with this ?

**Comment by skomlaebri** [comment]
Hi,
yes primary key are necessary for the optimization.
About the mapping above that I suggested. The primary key is on the id column and that is enough to make the optimization work.

**Comment by RaniRaven** [comment]
I am sorry, but I do not understand.
Do I have to have an id column ? Cause I already showed that it doesn't work even with the id column, I am getting 2 views, and wrong SQL query. 
I've tried it also with myid column, etc, and still the same issue.
Can I have a reference which is working ?

**Comment by skomlaebri** [comment]
The id column (in my example above) is the primary key of the table organization_name. It is not enough to rename the column name to id to make it work, the primary key is needed in the database.
You can check our start up example in the wiki https://github.com/ontop/ontop/wiki/Easy-Tutorial%3A-Using-Ontop-from-Protege

**Comment by bcogrel** [comment]
Closing since not updated during the last 6 months. If needed, feel free to reopen it.
