### ISSUE TITLE
Getting double view for simple sparql in SQL translation

### ISSUE THREAD

**Issue by RaniRaven** [ontop/ontop#203]
This seems wrong -
for the mapping 
:org/{id} a :organization_name ; :name {name}^^rdfs:Literal . 
to
select name as id, name from virtual_organization

the sparql :
PREFIX : <http://unit.hamama/test#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?x
where {
    ?x a :organization_name. ?x :name "xxy".
} 

translates to :
SELECT 
   1 AS `xQuestType`, NULL AS `xLang`, CONCAT('http://unit.hamama/test#org/', REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST('xxy' AS CHAR(8000) CHARACTER SET utf8), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS `x`
 FROM 
`mycheck`.`virtual_organization` QVIEW1,
`mycheck`.`virtual_organization` QVIEW2
WHERE 
(QVIEW1.`name` = 'xxy') AND
(QVIEW2.`name` = 'xxy')

At first I thought this is due to the fact that the same property is used as ID, but it seems like there is no way to write any query without this view duplication.

I also cannot figure out why in the select there is the specific value rather than the QVIEW.name, cause
with this optimization, there is not need for the FROM.

**Comment by RaniRaven** [comment]
BTW, removing the literal condition,

PREFIX : <http://unit.hamama/test#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?x
where {
    ?x a :organization_name.
} 
we get :
SELECT 
   1 AS `xQuestType`, NULL AS `xLang`, CONCAT('http://unit.hamama/test#org/', REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(QVIEW1.`name`, ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D')) AS `x`
 FROM 
`mycheck`.`virtual_organization` QVIEW1
WHERE 
QVIEW1.`name` IS NOT NULL

which is perfect

**Comment by skomlaebri** [comment]
In the second query you are using a single  mapping that's why there is no join involved.  Closed as same issue as  #202
