### ISSUE TITLE
 Description: Error in identifying column name "ed_code", please check the query source in the mappings.

### ISSUE THREAD

**Issue by suxiaoheng** [ontop/ontop#208]
recently, I followed the tutorial(https://github.com/ontop/ontop/wiki/Easy-Tutorial%3A-Using-Ontop-API-from-Eclipse) to learn how to use Quest with OWLAPI. I did not modify any thing here. But error occured like "Description: Error in identifying column name "wr_code", please check the query source in the mappings.". I was confused. How can I solve this issue.

**Comment by skomlaebri** [comment]
Hi, how did you install the database? Did you use the prebundled h2 or did you use the script (and in which database?). It could be the case that you don't need the quotes around wr_code and the other columns and table in the .obda file

**Comment by suxiaoheng** [comment]
thanks for a reply. I used the prebundled h2. I thought the problem lied in configuration of h2 DB.  I modified the url in obda file. But now the new problem occurs. " it.unibz.krdb.obda.model.OBDAException: java.lang.RuntimeException: Failed on importing database metadata!". I posted the log info below.
![image](https://user-images.githubusercontent.com/14047341/30747066-a108240c-9fde-11e7-9948-1208af50dc1d.png)

**Comment by skomlaebri** [comment]
If you are using the bundle you should modify the jdbc url as defined [here](https://github.com/ontop/ontop/wiki/Easy-Tutorial%3A-Using-Ontop-from-Protege) so:
Connection URL: jdbc:h2:tcp://localhost/./books
Database Username: sa
Database Password: (empty)
Driver class: org.h2.Driver
don't add the DATABASE_TO_UPPER parameter

**Comment by skomlaebri** [comment]
The connection url in the download file looks like jdbc:h2:tcp://localhost/books;DATABASE_TO_UPPER=FALSE
you should substitute it with jdbc:h2:tcp://localhost/./books

**Comment by ghxiao** [comment]
@suxiaoheng do you some have problems with issue?

**Comment by ghxiao** [comment]
@suxiaoheng Archived for the moment. Fell free to reopen it if needed.
