### ISSUE TITLE
Is Quest reasoner thread-safe?

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#209]
Hello, I'd like to use Ontop in a web application. In this scenario several users could access to Quest reasoner at the same time so I'm wondering if the reasoner is thread-safe or not when different users use the same instance.

Thanks for your attention,
Fran Abad.

**Comment by bcogrel** [comment]
Hi, yes in version 3, the Ontop query engine is expected to be thread-safe. 
Therefore, any concurrency issue should now be considered as a bug.

PS: we do not call our query engine Quest anymore (it ended up with version 1).

**Comment by fanavarro** [comment]
Thanks for your quick answer, @bcogrel. I will try to migrate to version 3.
