### ISSUE TITLE
Duplicate attribute name due to error parsing SQL

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#211]
Hi, I'm using ontop in my project and I have decided to update it from 1.18 to 3.0.0-beta-1 version. I downloaded the protege bundle in order to try the new version but it threw an error (duplicate attribute name) when I tried to start the reasoner. The ontology and the mapping files works on the previous version. 

I have downloaded the API examples and I have modified one of them in order to use my ontology and mappings and to be able to debug the code. I've figured out that the bug is in the function extract of the class SelectQueryAttributeExtractor. The conflictive mapping has the following SQL query:

```
SELECT ALMAES001.IDART,
     ALMAES001.CODART,
     ALMAES001.IDFAMI,
     ALMAES001.DESCRIP,
     ALMAES001.DESCRII,
     ALMAES001.MEDIDA,
     ALMAES001.DESCUENTO,
     ALMAES001.UNIDADES,
     ALMAES001.UDSENV,
     ALMAES001.IDTIPIVA,
     ALMAES001.UPC,
     ALMAES001.PVP1, ALMAES001.PVP2, ALMAES001.PVP3, ALMAES001.PVP4, ALMAES001.PVP5,
     to_char(ALMAES001.FECALTA,'YYYY-MM-DD') AS FECALTA,
     to_char(ALMAES001.FECBLO,'YYYY-MM-DD') AS FECBLO,
     ALMAES001.STCMIN,
     ALMAES001.STCMAX,
     ALMAES001.PUNRUP,
     ALMAES001.UBICACION,
     ALMAES001.IDCTACOMPRA,
     ALMAES001.IDCTAVENTA,
     ALESFO001.PRECIOFINAL
	             
FROM ALMAES001
LEFT JOIN ALESFO001 ON ALMAES001.IDART = ALESFO001.IDART
```
It has a left join clause, which are not supported. Because of this, the method "extract" catch the exception and try to parse the SQL in order to retrieve the name of the columns:
```

    public ImmutableList<QuotedID> extract(String sql) throws InvalidSelectQueryException {

        try {
            ImmutableMap<QualifiedAttributeID, Variable> attrs = sqae.parse(sql).getAttributes();

            return attrs.keySet().stream()
                    .filter(id -> id.getRelation() == null)
                    .map(id -> id.getAttribute())
                    .collect(ImmutableCollectors.toList());
        }
        catch (Exception e) {
            final ImmutableList.Builder<QuotedID> attributes = ImmutableList.builder();

            // COULD NOT PARSE - do a rough approximation

            int start = sql.toLowerCase().indexOf("select") + "select".length();
            // might be a good idea to surround FROM with whitespaces
            int end = sql.toLowerCase().indexOf("from");
            if (end == -1)
                throw new InvalidSelectQueryException("Error parsing SQL query: Couldn't find FROM clause", sql);

            String projection = sql.substring(start, end).trim();

            // remove all brackets
            while (projection.matches("\\([^\\(]*\\)"))
                projection = projection.replaceAll("\\([^\\(]*\\)", "");

            for (String col : projection.split(",")) {
                // TODO: AS should be treated as optional
                String[] components = AS.split(col);
                String columnName = components[components.length - 1].trim();

                // ROMAN (25 Jan 2017): do not understand the purpose
                // split on spaces that are not inside single quotes
                // if (columnName.contains(" "))
                //    columnName = columnName.split("\\s+(?![^'\"]*')")[1].trim();

                // get only the column name (but not the qualifier table name)
                // eg: table.column -> column
                if (columnName.contains("."))
                    columnName = columnName.substring(columnName.lastIndexOf(".") + 1);

                QuotedID attribute = idfac.createAttributeID(columnName);
                attributes.add(attribute);
            }

            return attributes.build();
        }
```
Firstly it retrieves the text between select and from, which is supposed to be the column names. Then, for each element separated by a comma (which is supposed to be a column name), if it has spaces, it keeps only the last complete word and if it has a dot (".") then it performs a substring in order to keep only the text after the dot, else return the element. This method fails with the line "to_char(ALMAES001.FECALTA,'YYYY-MM-DD') AS FECALTA," because when it splits by commas, we have the following two elements "to_char(ALMAES001.FECALTA" and "'YYYY-MM-DD') AS FECALTA". The first element produces FECALTA according to the dot rule and the second element produces the same according to the rule of keeping the last word when there are more than one. Because of this "FECALTA" is added twice and the exception is thrown.

Is there any quick fix to avoid this behaviour?

Thanks in advance,
Fran Abad.

**Comment by fanavarro** [comment]
Hi @skomlaebri. I've sent a pull request with a possible solution.

**Comment by ghxiao** [comment]
@fanavarro Thanks a lot for the quick fix! We also have a fix from @kontchakov . We are evaluating both two solutions now.

**Comment by skomlaebri** [comment]
Hi, thanks for reporting the problem we used the more general bugfix of  @kontchakov to solve the issue.
