### ISSUE TITLE
Bug in TypeExtractor when expression appears.

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#214]
Hi, I'm moving my application from 1.18.1 to 3.0.0-beta-2-SNAPSHOT. I've have a function to materialize the triples and I've found an error at getCastTypeFromSubRule function in TypeExtractor class. This function is the following:
```

    /**
     * Extracts the cast type of one projected variable
     * from the body atom that provides it.
     */
    private static TermType getCastTypeFromSubRule(
            Term term,
            ImmutableList<Function> bodyDataAtoms,
            Map<Predicate, ImmutableList<TermType>> alreadyKnownCastTypes) {

        if (term instanceof Variable) {
            Variable variable = (Variable) term;

            for (Function bodyDataAtom : bodyDataAtoms) {

                List<Term> arguments = bodyDataAtom.getTerms();
                for (int i = 0; i < arguments.size(); i++) {
                    /**
                     * Finds the position of the variable in the current body atom
                     */
                    if (arguments.get(i).equals(variable)) {

                        // i is not final...
                        final int index = i;

                        return Optional.ofNullable(alreadyKnownCastTypes.get(bodyDataAtom.getFunctionSymbol()))
                                .map(types -> types.get(index)).orElseThrow(() -> new IllegalStateException("No type could be inferred for " + term));

                    }
                }
            }

            throw new IllegalStateException("Unbounded variable: " + variable);
        }
        else if (term instanceof Expression) {
            Expression expression = (Expression) term;
            ImmutableList<Optional<TermType>> argumentTypes = expression.getTerms().stream()
                    .map(t -> getCastTypeFromSubRule(t, bodyDataAtoms, alreadyKnownCastTypes))
                    .map(Optional::of)
                    .collect(ImmutableCollectors.toList());

            return expression.getOptionalTermType(argumentTypes)
                    .orElseThrow(() -> new IllegalStateException("No type could be inferred for " + term));
        }
        else {
            throw new IllegalStateException("The type should already be for a non-variable - non-expression term (was " + term + ")");
        }
    }

```

The problem appears when term is an Expression. In my case, the following expression:
`SUBSTR3(CCC1f0f1f2f0f1f2f0f1f2m81,5,8)`
In this case, the application goes through the following code code:
```
else if (term instanceof Expression) {
            Expression expression = (Expression) term;
            ImmutableList<Optional<TermType>> argumentTypes = expression.getTerms().stream()
                    .map(t -> getCastTypeFromSubRule(t, bodyDataAtoms, alreadyKnownCastTypes))
                    .map(Optional::of)
                    .collect(ImmutableCollectors.toList());

            return expression.getOptionalTermType(argumentTypes)
                    .orElseThrow(() -> new IllegalStateException("No type could be inferred for " + term));
        }
```
This code extracts the terms inside the expression, in my case "CCC1f0f1f2f0f1f2f0f1f2m81", "5" and "8". Then, the function getCastTypeFromSubRule is called again for each of these terms. In this function, when a term is not a variable nor an expression, an IllegalStateException is thrown. In my case, "5" and "8" are ValueConstants so that the exception is thrown. The type of the ValueConstants is already defined inside ValueConstant object.

I could insert code to deal with ValueConstant type in the function but I do not know if this will cause other bugs in the entire application. On the other hand I do not know if the correct behaviour would be to return the type that the expression returns (in this case SUBSTR function returns an string) instead of the types of each argument of the expression.

Thanks for your attention,
Fran Abad.

**Comment by bcogrel** [comment]
Hi Fran,

Thanks for reporting it! Actually I also experienced it recently in an experimental branch. Yes, it should not throw an IllegalStateException when the term is a Constant.

I quickly fixed it, I am now running the tests. I will let you know when it will be merged in the version3 branch.

**Comment by fanavarro** [comment]
Hi @bcogrel, thanks for your quick response!

I have fixed it by adding another else-if clause to deal with ValueConstant:
```

        else if(term instanceof ValueConstant){
        	ValueConstant valueConstant = (ValueConstant) term;
        	TermType termType = TypeFactoryImpl.getInstance().getTermType(valueConstant.getType());
        	return termType;
        }

```
The materialization of my ontology works fine now, but I think that your solution will more comprehensive.

Thanks again!
Fran Abad.

**Comment by bcogrel** [comment]
As you can see, I actually did the same :)
