### ISSUE TITLE
Bug obtaining the datatypes of variables.

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#216]
Hi, I found a bug a month ago in the file MappingDataTypeCompletion.java, concretely in the following function:

```
   private static Map<String, List<IndexedPosition>> createIndex(List<Function> body) {
        Map<String, List<IndexedPosition>> termOccurenceIndex = new HashMap<>();
        for (Function a : body) {
            List<Term> terms = a.getTerms();
            int i = 1; // position index
            for (Term t : terms) {
                if (t instanceof Variable) {
                    Variable var = (Variable) t;
                    List<IndexedPosition> aux = termOccurenceIndex.get(var.getName());
                    if (aux == null)
                        aux = new LinkedList<>();
                    aux.add(new IndexedPosition(a, i));
                    termOccurenceIndex.put(var.getName(), aux);
                    i++; // increase the position index for the next variable
                } else if (t instanceof FunctionalTermImpl) {
                    // NO-OP
                } else if (t instanceof ValueConstant) {
                    // NO-OP
                } else if (t instanceof URIConstant) {
                    // NO-OP
                }
            }
        }
        return termOccurenceIndex;
    }
```
The problem occurs when there are terms that are not variables (for example, a constant). In this case, the iterator "i" is not incremented, which causes a shift between the pointer and the position of the terms in the list of terms. I proposed the fix #213, which consist of the increment of i in all cases.

I copy the text I wrote in the pull request for explanatory reasons:

> There was a bug obtaining the data type of the variables.
> 
> The application creates an index based on IndexedPosition object. This object have the property "pos", which indicates the index of a variable in a list of terms. The program iterates over all terms in the list and it checks if the term is a variable. If there exist constants in the list of terms, the pointer that iterates the list of terms was not updated. For instance, if we have the following terms:
> var1 var2 const1 var3
> Then the created index was:
> var pos
> var1 0
> var2 1
> var3 2
> 
> This causes an error when var3 is accessed via terms.get(2) due to this position is occupied by "const1". What i've done to fix this is to increment the iterator for each term in the list and not only when the term is a variable.

Cheers,
Fran.

**Comment by skomlaebri** [comment]
Thanks for the contribution, your changes have been merged with version3.
