### ISSUE TITLE
Test supported built in SPARQL 1.1 functions

### ISSUE THREAD

**Issue by skomlaebri** [ontop/ontop#229]
Enable and check tests for SPARQL compliance .

**Comment by joshuabezaleel** [comment]
Does this mean that Ontop already supported [SPARQL 1.1](https://www.w3.org/TR/sparql11-overview/)?

**Comment by bcogrel** [comment]
No, Ontop does not fully support SPARQL 1.1 yet (e.g. aggregation and property paths are not yet supported). However, when we look at a SPARQL specification, we always consider the latest one. Features are added bit by bit.

**Comment by joshuabezaleel** [comment]
May we know which specification of the SPARQL 1.1 that are already supported and which aren't? 
Thank you very much, Benjamin and team! :)

**Comment by bcogrel** [comment]
SPARQL compliance tests related to currently supported SPARQL functions are supported. 

The list of supported functions still needs to be documented, but there is a dedicated issue for that https://github.com/ontop/ontop/issues/34.

Regarding the SERVICE clause, Ontop does not support it in its current design, as it cannot be delegated to an RDBMS (which is unaware of SPARQL).
