### ISSUE TITLE
ansSQ1 appears when selecting all properties of an individual

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#237]
Hello, I'm trying to get all properties that an individual has, so I wrote the following query:
```
select distinct ?p ?o where {
  <http://www.basecia.es/ontologia#cliente43000001> ?p ?o .
}
```
This query returns all entries related to the individual <http://www.basecia.es/ontologia#cliente43000001>, for example:
```
----------------------------------------------
p => rdf:type
o => <http://www.basecia.es/ontologia#EmpresaBloqueada>
----------------------------------------------
p => <http://www.basecia.es/ontologia#tienePorcentajeDescuentoEmpresa>
o => 0
----------------------------------------------
p => <http://www.basecia.es/ontologia#tieneNombreComercialCliente>
o => NOMBRE EMPRESA, SL
----------------------------------------------
p => <http://www.basecia.es/ontologia#tieneEmail>
o => hmurcia@hmurcia.es
----------------------------------------------
```
Among others. However, the following entry is appearing too:
```
----------------------------------------------
p => <ansSQ1>
o => <NOMBRE EMPRESA, SL>
----------------------------------------------
```
I do not have any property in my ontology with that name. I have tried to develop a test case but it is not appearing with simple ontologies. The database that I'm using is not very well built and I had to develop complex mappings to adapt it to the ontology. I'm almost sure that this is the reason of this bug but, in what cases could appear "ansSQ1" in the results of a query? I'm attaching the log of the application at debug level. I think the problem is in the mapping step. The line 12207 of the log shows a mapping whose URI is ansSQ1.

I'm using the current version3 branch.

I will try to find out why ansSQ1 is there by debugging. I'll write if I find the problem.

Cheers,
Fran.

[salida.txt](https://github.com/ontop/ontop/files/1491129/salida.txt)

**Comment by fanavarro** [comment]
I've seen that the "ansSQ1" appears in the function transform of DefaultMappingTransformer class. It looks like this:
```
@Override
    public OBDASpecification transform(OBDASpecInput specInput, Mapping mapping, DBMetadata dbMetadata, Ontology ontology,
                                       TBoxReasoner tBox)
            throws MappingException, DBMetadataExtractionException {
        Mapping factsAsMapping = factConverter.convert(ontology, mapping.getExecutorRegistry(),
                settings.isOntologyAnnotationQueryingEnabled(), mapping.getMetadata().getUriTemplateMatcher());
        Mapping mappingWithFacts = mappingMerger.merge(mapping, factsAsMapping);
        Mapping eqFreeMapping = eqFreeRewriter.rewrite(mappingWithFacts, tBox, ontology.getVocabulary(), dbMetadata);
        Mapping sameAsOptimizedMapping = sameAsInverseRewriter.rewrite(eqFreeMapping, dbMetadata);
        Mapping canonicalMapping = mappingCanonicalRewriter.rewrite(sameAsOptimizedMapping, dbMetadata);
        Mapping saturatedMapping = mappingSaturator.saturate(canonicalMapping, dbMetadata, tBox);
        Mapping normalizedMapping = mappingNormalizer.normalize(saturatedMapping);

        return specificationFactory.createSpecification(normalizedMapping, dbMetadata, tBox, ontology.getVocabulary());
    }
}
```
I've checked if the strings that represent the mappings contains "ansSQ1" and I've obtained the following:
```
factsAsMapping.toString().contains("ansSQ1") -> false
mappingWithFacts.toString().contains("ansSQ1") -> false
eqFreeMapping.toString().contains("ansSQ1") -> true
sameAsOptimizedMapping.toString().contains("ansSQ1") -> true
canonicalMapping.toString().contains("ansSQ1") -> true
saturatedMapping.toString().contains("ansSQ1") -> true
normalizedMapping.toString().contains("ansSQ1") -> true
```
So it looks like "eqFreeRewriter" is adding the "ansSQ1". This rewriting operation can be disabled by writing "ontop.optimizeEquivalences=false" in the properties file . In this case, I've obtained this:
```
factsAsMapping.toString().contains("ansSQ1") -> false
mappingWithFacts.toString().contains("ansSQ1") -> false
eqFreeMapping.toString().contains("ansSQ1") -> false
sameAsOptimizedMapping.toString().contains("ansSQ1") -> false
canonicalMapping.toString().contains("ansSQ1") -> true
saturatedMapping.toString().contains("ansSQ1") -> true
normalizedMapping.toString().contains("ansSQ1") -> true
```
As you can see, now "ansSQ1" is added by "mappingCanonicalRewriter". I think the problem is in the function convertMappingRules of the class Datalog2QueryMappingConverter because it is the common function that is called by "mappingCanonicalRewriter" and "eqFreeRewriter". I've tried to debug it, but is very difficult due to the existence of many lambda functions and recursive calls.

Do you need any extra information?

Thanks in advance,
Fran.

**Comment by juliencorman** [comment]
Hello Francisco,

Indeed, there seems to be an issue when converting a mapping from one internal format (Datalog-like) to another (Intermediate Query).
Thank you very much for pointing at it.
I don't think I need extra information for now.

I'll keep you informed.

Regards,
Julien

**Comment by juliencorman** [comment]
Hello,

I did not manage to reproduce the bug.
Could you send us the mapping file and ontology ?

Thanks,
Julien

**Comment by fanavarro** [comment]
Hi @juliencorman, thanks for your answer. I'm attaching the files in this message (mappings.obda and ontology.owl). The query that includes the ansSQ1 is:
`select distinct ?p ?o where {  <http://www.basecia.es/ontologia#cliente43000001> ?p ?o .}`

Regards,
Fran.
[files.zip](https://github.com/ontop/ontop/files/1555094/files.zip)

**Comment by juliencorman** [comment]
Thanks,

"ansSQ1" is an internal predicate used by Ontop for subqueries.
I fixed a problem with mapping saturation, which made "ansSQ1" a possible binding for ?p.
The fix is on branch "bugfix/datalogToIQMappingConversion".

Could you check on your side whether the unwanted binding has disappeared ?
Note that I renamed "ansSQ1" to "ontopSubquery". So if the problem persists (it should not), you'll have "ontopSubquery" as an unwanted binding for ?p.

Regards,
Julien

**Comment by fanavarro** [comment]
Hi @juliencorman. Now it works as expected, no "ansSQ1" neither "ontopSubquery" in the results.

Great job, thanks! Should we close this issue now or we have to wait until it has merged into the master branch?

Thanks again,
Fran.
