### ISSUE TITLE
fix the documentation regarding metamapings

### ISSUE THREAD

**Issue by martinrezk** [ontop/ontop#26]
say that a mapping of the form

`{id} a :Student`

is wrong, since  {id} has no prefix, and

`:{id}  :prop  {myprop}`

{myprop} will be regarded as an object

https://babbage.inf.unibz.it/trac/obdapublic/wiki/ObdalibObdaTurtlesyntax#Turtlesyntaxfortargetinmappings

**Comment by ghxiao** [comment]
already fixed
