### ISSUE TITLE
R2RML import fails for BSBM dataset

### ISSUE THREAD

**Issue by mchaloupka** [ontop/ontop#261]
### Description

I have created an R2RML mapping file which can be used for BSBM (Berlin SPARQL Benchmark) dataset. I tried to import it and although it says that the file was imported, it fails to continue. It does not show the mappings (only count is visible at bottom). Also, it is not possible to save the mapping.

### Steps to Reproduce

1. Open Protége with Ontop plugin
2. Fill in database information
3. Try to import the mapping file

**Expected behavior:** I expect to see the mappings in UI and to be able to save them.

**Actual behavior:** The mappings fails to show, the whole UI is frozen and it is not possible to save the mapping.

**Reproduces how often:** It happens every time.

### Attached material

[log.txt](https://github.com/ontop/ontop/files/1987831/log.txt) - Log from running Protége.
[bsbm.txt](https://github.com/ontop/ontop/files/1987836/bsbm.txt) - The mapping which I tried to import.

### Versions

I have used the Ontop 1.8.1 bundle.

**Comment by ghxiao** [comment]
@mchaloupka,

1. Could you try to use the latest version ontop 3.0.0-beta-2? You can download it from Sourceforge.

2. For the files, you may use directly the following setup of BSBM which we are using for some ongoing paper:
https://github.com/ontop/ontop-examples/tree/master/iswc-2018-optional/obda

**Comment by mchaloupka** [comment]
1. Yes, it generates the same error.

**Comment by ghxiao** [comment]
@mchaloupka problem of R2RML-OBDA file conversion confirmed. we opened another issue #262 to track it.
