### ISSUE TITLE
Missing variables in query response

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#263]
I want to retrieve information from a concrete individual, that it's to say, the individual and all the predicates together with their objects related to that individual. Moreover, I want to retrieve, if exist, the label of the individual and the labels of the objects related with the individual through the predicates. For example, if I want to retrieve the information about the individual whose uri is "http://www.basecia.es/ontologia#proveedor40000003", the following query is constructed:
```
SELECT  ?instance ?predicate_object ?instanceLabel ?object ?objectLabel
WHERE
  { ?instance  ?predicate_object  ?object
    OPTIONAL
      { ?instance  <http://www.w3.org/2000/01/rdf-schema#label>  ?instanceLabel}
    OPTIONAL
      { ?object  <http://www.w3.org/2000/01/rdf-schema#label>  ?objectLabel}
  }
VALUES ?instance { <http://www.basecia.es/ontologia#proveedor40000003> }
```
However, the bindings of the response contain null values for ?object variable when ?predicate_object is a datatype property. I think, for this query, ?object variable should have a value. For instance, a part of the output provided by my application for this query is the following:

```
----------------------------------------------
First row:
    instance => <http://www.basecia.es/ontologia#proveedor40000003>
    predicate_object => <http://www.basecia.es/ontologia#tienePorcentajeDescuentoProveedor>
    instanceLabel => PANADERIA ROMO, S.A
----------------------------------------------
Second row
    instance => <http://www.basecia.es/ontologia#proveedor40000003>
    predicate_object => <http://www.basecia.es/ontologia#tieneCuentaBancaria>
    instanceLabel => PROVEEDOR 3
    objectLabel => ES4204870009252007000992
    object => <http://www.basecia.es/ontologia#cuenta_bancaria_proveedor40000003>
----------------------------------------------
```
As you can see, the first row does not contain ?object variable since ?predicate_object is a data type property. However, the second row contains the ?object variable and their label correctly.
I'm expecting that, at least, each row contains ?instance  ?predicate_object  and ?object variables.

### Attached material
[files.zip](https://github.com/ontop/ontop/files/2034489/files.zip)
I'm attaching a zip file with my ontology and their mappings. If you need something else just tell me.

### Versions
I'm using an updated (2018-24-5) version of Ontop API version3 branch in a Java application.

**Comment by fanavarro** [comment]
Hi, I'm debugging and the problem could be in the bindingLiftOptimizer used in reformulateIntoNativeQuery from QuestQueryProcessor class. Before this optimizer is applied, the intermediate query is the following:
[before.txt](https://github.com/ontop/ontop/files/2035033/before.txt)


Note that lines as `CONSTRUCT [predicate_object, object] [predicate_object/URI1("http://www.basecia.es/ontologia#tieneDireccionInternet"), object/http://www.w3.org/2001/XMLSchema#string(PAGWWWf793m895)]` bind http://www.w3.org/2001/XMLSchema#string(PAGWWWf793m895) to ?object correctly.

After the optimizer is applied, we have this intermediate query:
[after.txt](https://github.com/ontop/ontop/files/2035034/after.txt)

Note that lines as `CONSTRUCT [predicate_object, object, instanceLabel, objectLabel] [predicate_object/URI1("http://www.basecia.es/ontologia#tieneDireccionInternet"), objectLabel/"null", object/http://www.w3.org/2001/XMLSchema#string("null")]` appear, binding null values to ?object.
I'll check the optimizer code for a fix.

Cheers!

**Comment by fanavarro** [comment]
I have not found a solution after a few days dealing with this bug. I'm attaching a minimal example I prepared to debug the application. It includes ontology, mappings, properties and a sql script to recreate the example database. In this case the ontology has two classes: Person and Job, which are related through hasJob relation. Also, Person has the data properties "hasBirthYear" and "hasName", while Job has "hasDescription". Moreover, hasName and hasDescription have been mapped to rdfs:label. When I try to execute the following query:
```
SELECT  ?instance ?predicate_object ?instanceLabel ?object ?objectLabel
WHERE
  { ?instance  ?predicate_object  ?object
    OPTIONAL
      { ?instance  <http://www.w3.org/2000/01/rdf-schema#label>  ?instanceLabel}
    OPTIONAL
      { ?object  <http://www.w3.org/2000/01/rdf-schema#label>  ?objectLabel}
  }
VALUES ?instance { <http://www.semanticweb.org/test#person1> }
```
In ontop SPARQL tab in Protege, an error executing query appears with the following message:
```
it.unibz.inf.ontop.exception.OntopTranslationException: java.lang.IllegalArgumentException: UNION [predicate_object, object] does not appear as a child.

###################################################
##    Debugging information for developers    ##
###################################################

	at it.unibz.inf.ontop.owlapi.connection.impl.DefaultOntopOWLStatement.executeSelectQuery(DefaultOntopOWLStatement.java:90)
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:200)
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:167)
	at it.unibz.inf.ontop.protege.gui.action.OBDADataQueryAction$1.run(OBDADataQueryAction.java:152)
```
Moreover, the following window appears too:
![imagen](https://user-images.githubusercontent.com/11376639/40716248-8d7afd94-6408-11e8-86d4-7ef5362cda9b.png)

On the other hand, when I execute this query from my Java code, ?object variable is null when ?predicate_object is a data type property. The output of my application is the following (note the missing ?object values in several results):
```
instance => <http://www.semanticweb.org/test#person1>
predicate_object => rdf:type
instanceLabel => Person 1
object => <http://www.semanticweb.org/test#Person>
----------------------------------------------
instance => <http://www.semanticweb.org/test#person1>
predicate_object => <http://www.semanticweb.org/test#hasBirthYear>
instanceLabel => Person 1
----------------------------------------------
instance => <http://www.semanticweb.org/test#person1>
predicate_object => <http://www.semanticweb.org/test#hasName>
instanceLabel => Person 1
----------------------------------------------
instance => <http://www.semanticweb.org/test#person1>
predicate_object => rdfs:label
instanceLabel => Person 1
----------------------------------------------
instance => <http://www.semanticweb.org/test#person1>
predicate_object => <http://www.semanticweb.org/test#hasJob>
instanceLabel => Person 1
objectLabel => Job 1
object => <http://www.semanticweb.org/test#job1>
----------------------------------------------
```
Nonetheless, when I comment the line `intermediateQuery = bindingLiftOptimizer.optimize(intermediateQuery);` in method reformulateIntoNativeQuery from QuestQueryProcessor class, the results are correct:
```
instance => <http://www.semanticweb.org/test#person1>
predicate_object => <http://www.semanticweb.org/test#hasJob>
instanceLabel => Person 1
objectLabel => Job 1
object => <http://www.semanticweb.org/test#job1>
----------------------------------------------
instance => <http://www.semanticweb.org/test#person1>
predicate_object => rdf:type
instanceLabel => Person 1
object => <http://www.semanticweb.org/test#Person>
----------------------------------------------
instance => <http://www.semanticweb.org/test#person1>
predicate_object => <http://www.semanticweb.org/test#hasBirthYear>
instanceLabel => Person 1
object => 1989
----------------------------------------------
instance => <http://www.semanticweb.org/test#person1>
predicate_object => <http://www.semanticweb.org/test#hasName>
instanceLabel => Person 1
object => Person 1
----------------------------------------------
instance => <http://www.semanticweb.org/test#person1>
predicate_object => rdfs:label
instanceLabel => Person 1
object => Person 1
----------------------------------------------
```
However, without the lift binding optimization, the query that I showed in my first post is translated into a huge SQL query, provoking a lack of memory error in my database server.
Therefore, the optimization is necessary but, I think there is any kind of error in the process, maybe when removing empty nodes, calculating and propagating null variables.
[minimal_example.zip](https://github.com/ontop/ontop/files/2053641/minimal_example.zip)

**Comment by juliencorman** [comment]
Hello Francisco,

Thank you very much for the detailed illustration, as well as the minimal example.
This is indeed a bug in Ontop Version 3.0.0-beta-2.

We've already rewritten the binding lift optimizer (in a development branch), and the bug does not appear anymore.
So this should be fixed in the next release.

Regards,
Julien

**Comment by fanavarro** [comment]
Thanks for your response, @juliencorman. I'll wait for the next release then.
Thanks for your work,
Francisco Abad.
