### ISSUE TITLE
OBDA disappears when I change the ontology

### ISSUE THREAD

**Issue by BrexLed** [ontop/ontop#282]
Hi,
mapping disappear when I change ontology

### Steps to Reproduce

Open an ontology using Protege and load the dependencies,
Move to another ontology,
Return to the previous ontology,
There is mapping no more.

**Expected behavior:**
I need to work in many ontologies at the same time, when I change I would like to see the appropriate mapping.

**Actual behavior:** 
If I change ontology, the mapping disappear.

**Reproduces how often:** 
Always

### Attached material
If I save after changing the ontology, the OBDA file is overwritten with an empty one.

http://g.recordit.co/GfO49sa1RF.gif

**Comment by ghxiao** [comment]
Hi, we never worked with multiple ontologies in Protege before, and we will look into the issue your reported.

Btw, I like the way you report the bug via GIF. This communicates the problem immediately,.

**Comment by Jimflip** [comment]
I have suffered this issue too.  My Ontology has some imports and when I switch to one of those I have lost my work.

**Comment by kontchakov** [comment]
Fixed with 478b0a660f6f1e98e660d9c75bcce5d4a7bd5f72.
