### ISSUE TITLE
`BIND`  with `OPTIONAL` breaks

### ISSUE THREAD

**Issue by SirkoS** [ontop/ontop#283]
### Description

It seems ontop can not handle `BIND` in conjunction with `OPTIONAL`.

### Steps to Reproduce

**Query**
```
SELECT *
WHERE {
  BIND( <http://example.org/Individual1> AS ?source )
  OPTIONAL { ?source rdfs:label ?label . }
}
```

**Expected behavior:** 
expected output is a binding for the respective individual
```
+--------------------------------+----------------+
|              source            |     label      |
+--------------------------------+----------------+
| http://example.org/Individual1 | "testdata"     |
+--------------------------------+----------------+
```

**Actual behavior:**
Error message:
`
Query evaluation error: it.unibz.inf.ontop.exception.OntopReformulationException: it.unibz.inf.ontop.datalog.impl.DatalogProgram2QueryConverterImpl$InvalidDatalogProgramException: No data or composite atom in List()
`

**Reproduces how often:**
always

### Attached material

**Ontology**
*none needed*

**Mapping**
```
[PrefixDeclaration]
ex: http://example.org/
rdfs: http://www.w3.org/2000/01/rdf-schema#
rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#

[MappingDeclaration] @collection [[

mappingId   label
target      ex:Individual{id} rdfs:label {label} .
source      SELECT id, label  FROM "data" 

]]
```
**Database**
```
CREATE TABLE public.data (
    id integer NOT NULL,
    label character varying(10)
);
INSERT INTO public.data VALUES (1, 'testdata');
```

### Versions

**Environment**
* webapp for current ontop as of   70470b1 (branch: version3)
* Apache Tomcat/8.5.14
* PostgreSQL 10.5
* Debian 9.5

### Additional Information

If I use `VALUES` instead of `BIND` it works out just fine:
```
SELECT *
WHERE {
  VALUES ?source { <http://example.org/Individual1> }
  OPTIONAL { ?source rdfs:label ?label . }
}
```

<hr>

While investigating this, I noticed another bug/issue:

Using a query with only optional bindings, results in another error. So given above setup, this query
```
SELECT *
WHERE {
  OPTIONAL { <http://example.org/Individual1> rdfs:label ?l . }
}
```
leads to this error
`Query evaluation error: it.unibz.inf.ontop.exception.OntopReformulationException: java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)`

I would have expected the same result as the aforementioned queries, as I just inline the IRI.

**Comment by bcogrel** [comment]
Dear Sirko,

Thanks a lot for reporting this issue and providing us an example!
Now it should be fixed.

Feel free to reopen the issue if you experience similar issues.

Best,
Benjamin
