### ISSUE TITLE
R2RML mapping: rdf:type as predicate with class template leads to NullPointerException

### ISSUE THREAD

**Issue by yoadey** [ontop/ontop#286]
### Description

In r2rml conversion:
If <template1> rdf:type <template2> should be generated and template1 contains a variable which is also used in template2, a NullPointerException is thrown.

### Steps to Reproduce

1. Create a table TABLE1 with two columns ID and COLUMN
2. Run R2RML parser with following snippet
```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

@prefix test: <http://www.test.com/> .

test:INSTANCE a rr:TriplesMap;
  rr:logicalTable [ rr:tableName "TABLE1"; ];
  rr:subjectMap [
    rr:template "http://www.test.com/{COLUMN}/{ID}";
    rr:class test:testClass;
  ];
  rr:predicateObjectMap [
    rr:predicate rdf:type ;
    rr:objectMap [
      rr:template "http://www.test.com/class/{COLUMN}";
      rr:termType rr:IRI;
    ];
  ];
.
```

**Expected behavior:**

For the table:
```
---------------
| ID | COLUMN |
---------------
|  1 | VAL1   |
|  2 | VAL2   |
---------------
```
It generates triples of the form
`<http://www.test.com/VAL1/1> rdf:type <http://www.test.com/class/VAL1>`
`<http://www.test.com/VAL2/2> rdf:type <http://www.test.com/class/VAL2>`

**Actual behavior:**

Following log errors are written:
```
Error: The source query does not provide the attribute COLUMN (variable COLUMN ) required by the target atom. 
Problem location: source query of the mapping assertion 
[id: mapping--1081215390#46a5210cc79c499894955517c633eedb
target atom: http://www.test.com/HAS_BLND(URI2("http://www.test.com/{}",COLUMN))
source query: SELECT "ID" FROM TABLE1 WHERE "COLUMN" = 'VAL1']

Error: The source query does not provide the attribute COLUMN (variable COLUMN ) required by the target atom. 
Problem location: source query of the mapping assertion 
[id: mapping--1081215390#ba3c6b6ee3064639a3d9471794984214
target atom: http://www.test.com/HAS_BLND(URI2("http://www.test.com/{}",COLUMN))
source query: SELECT "ID" FROM TABLE1 WHERE "COLUMN" = 'VAL2']
```

**Reproduces how often:**

Occurs every time the program is executed.

### Versions

The used Version is 3.0.0-beta-2

### Additional Information

A first analysis showed, that in class MetaMappingExpander the following lines exclude the template values from being retrieved in other templates used for this RDF statement:
```
List<SelectItem> newColumns = queryColumns.values().stream()
    .filter(c -> !templateColumns.contains(c))
    .collect(ImmutableCollectors.toList());
```
If instead of newColumns all queryColumns are taken this error does not occur.

**Comment by bcogrel** [comment]
Thank you for reporting the issue, the problem came from the occurrence of the same column ("COLUMN") in the subject and in the class templates.

The issue has been reproduced and fixed.
