### ISSUE TITLE
Duplicate classes "org.apache.http.conn.ssl.SSLSocketFactory" in different JARs, have different implementations, which leads to semantic conflicts

### ISSUE THREAD

**Issue by HelloCoCooo** [ontop/ontop#288]
Be similar as issue #287,
 
in **ontop-ontop-3.0.0-beta-2** (**\engine\system\sql\owlapi** module), duplicate classes with the same fully-qualified name _**org.apache.http.conn.ssl.SSLSocketFactory**_ are included in two different libraries, i.e., **org.apache.httpcomponents:httpclient-osgi:4.5.2** and **org.apache.httpcomponents:httpclient:4.2.5**.

Similarly, according to _"first declaration wins"_ class loading strategy, only this class in **_org.apache.httpcomponents:httpclient-osgi:4.5.2_** can be loaded, and that in _**org.apache.httpcomponents:httpclient:4.2.5**_ will be shadowed.

Also, by further analyzing, your project expects to invoke method **_<org.apache.http.conn.ssl.SSLSocketFactory: java.net.Socket connectSocket(java.net.Socket,java.net.InetSocketAddress,java.net.InetSocketAddress,org.apache.http.params.HttpParams)>_**  in _**org.apache.httpcomponents:httpclient:4.2.5**_. As it has been shadowed, so that this method defined in **_org.apache.httpcomponents:httpclient-osgi:4.5.2_** is actually forced to be referenced via the following invocation path:
```
<it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl$OntopSQLOWLAPIBuilderMixin: it.unibz.inf.ontop.injection.OntopSQLOWLAPIConfiguration$Builder ontologyFile(java.net.URL)> D:\testcase\TestProject\ontop-ontop-3.0.0-beta-2\engine\system\sql\owlapi\target\classes
<it.unibz.inf.ontop.injection.impl.OntopMappingOntologyBuilders$StandardMappingOntologyBuilderFragment: it.unibz.inf.ontop.injection.OntopMappingOntologyConfiguration$Builder ontologyFile(java.net.URL)> D:\cEnvironment\repository\it\unibz\inf\ontop\ontop-mapping-owlapi\3.0.0-beta-2\ontop-mapping-owlapi-3.0.0-beta-2.jar
<org.apache.http.impl.client.cache.AsynchronousValidationRequest: void run()> D:\cEnvironment\repository\org\apache\httpcomponents\httpclient-cache\4.2.5\httpclient-cache-4.2.5.jar
<org.apache.http.impl.client.cache.CachingHttpClient: org.apache.http.HttpResponse revalidateCacheEntry(org.apache.http.HttpHost,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext,org.apache.http.client.cache.HttpCacheEntry)> D:\cEnvironment\repository\org\apache\httpcomponents\httpclient-cache\4.2.5\httpclient-cache-4.2.5.jar
<org.apache.http.impl.client.CloseableHttpClient: org.apache.http.HttpResponse execute(org.apache.http.HttpHost,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext)> 
<org.apache.http.impl.client.CloseableHttpClient: org.apache.http.client.methods.CloseableHttpResponse execute(org.apache.http.HttpHost,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext)> 
<org.apache.http.impl.client.AbstractHttpClient: org.apache.http.client.methods.CloseableHttpResponse doExecute(org.apache.http.HttpHost,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext)> 
<org.apache.http.impl.client.DefaultRequestDirector: org.apache.http.HttpResponse execute(org.apache.http.HttpHost,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext)> 
<org.apache.http.impl.client.DefaultRequestDirector: org.apache.http.HttpResponse tryExecute(org.apache.http.impl.client.RoutedRequest,org.apache.http.protocol.HttpContext)> 
<org.apache.http.impl.conn.ManagedClientConnectionImpl: void open(org.apache.http.conn.routing.HttpRoute,org.apache.http.protocol.HttpContext,org.apache.http.params.HttpParams)> 
<org.apache.http.impl.conn.DefaultClientConnectionOperator: void openConnection(org.apache.http.conn.OperatedClientConnection,org.apache.http.HttpHost,java.net.InetAddress,org.apache.http.protocol.HttpContext,org.apache.http.params.HttpParams)> 
<org.apache.http.conn.ssl.SSLSocketFactory: java.net.Socket connectSocket(java.net.Socket,java.net.InetSocketAddress,java.net.InetSocketAddress,org.apache.http.params.HttpParams)>

```
Although both of these two conflicting classes contain the referenced methods (with the same signature), they have different implementations. This issue will not lead to runtime crashes, but it can introduce inconsistent semantic hehavior by changing the control flows and data flows.

**_Workaround solution:_**
A solution to workaround the problem is **_reversing the declaration order_** of these two libraries in pom file. 

Then, according to **_"first declaration wins"_** class loading strategy, class _**org.apache.http.conn.ssl.SSLSocketFactory**_ in _**org.apache.httpcomponents:httpclient:4.2.5**_ can be loaded (the version that **ontop** expects to reference by static analysis).

Dependency tree---
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ ontop-system-sql-owlapi ---
[INFO] it.unibz.inf.ontop:ontop-system-sql-owlapi:jar:3.0.0-beta-2
**....**
[INFO] |  +- it.unibz.inf.ontop:ontop-reformulation-sql:jar:3.0.0-beta-2:compile
[INFO] |  |  \- it.unibz.inf.ontop:ontop-rdb:jar:3.0.0-beta-2:compile
[INFO] |  +- it.unibz.inf.ontop:ontop-mapping-sql-all:jar:3.0.0-beta-2:compile
[INFO] |  |  +- it.unibz.inf.ontop:ontop-mapping-sql-core:jar:3.0.0-beta-2:compile
[INFO] |  |  +- it.unibz.inf.ontop:ontop-mapping-native:jar:3.0.0-beta-2:compile
[INFO] |  |  +- it.unibz.inf.ontop:ontop-mapping-r2rml:jar:3.0.0-beta-2:compile
[INFO] |  |  |  +- org.eclipse.rdf4j:rdf4j-rio-turtle:jar:2.2.2:compile
[INFO] |  |  |  |  +- org.eclipse.rdf4j:rdf4j-rio-datatypes:jar:2.2.2:runtime
[INFO] |  |  |  |  \- org.eclipse.rdf4j:rdf4j-rio-languages:jar:2.2.2:runtime
[INFO] |  |  |  +- eu.optique-project:r2rml-api-core:jar:0.6.0:compile
[INFO] |  |  |  +- eu.optique-project:r2rml-api-rdf4j-binding:jar:0.6.0:compile
[INFO] |  |  |  |  \- org.apache.commons:commons-rdf-rdf4j:jar:0.3.0-incubating:compile
[INFO] |  |  |  |     +- org.apache.commons:commons-rdf-simple:jar:0.3.0-incubating:compile
[INFO] |  |  |  |     +- org.eclipse.rdf4j:rdf4j-repository-api:jar:2.2.2:compile
[INFO] |  |  |  |     +- org.eclipse.rdf4j:rdf4j-rio-ntriples:jar:2.2.2:compile
[INFO] |  |  |  |     +- org.eclipse.rdf4j:rdf4j-rio-nquads:jar:2.1.1:compile
[INFO] |  |  |  |     +- org.eclipse.rdf4j:rdf4j-rio-rdfxml:jar:2.2.2:compile
[INFO] |  |  |  |     +- org.eclipse.rdf4j:rdf4j-rio-trig:jar:2.1.1:compile
[INFO] |  |  |  |     +- org.eclipse.rdf4j:rdf4j-rio-jsonld:jar:2.1.1:compile
[INFO] |  |  |  |     +- org.eclipse.rdf4j:rdf4j-sail-memory:jar:2.1.1:compile
[INFO] |  |  |  |     |  +- org.eclipse.rdf4j:rdf4j-sail-base:jar:2.1.1:compile
[INFO] |  |  |  |     |  +- org.eclipse.rdf4j:rdf4j-sail-inferencer:jar:2.1.1:compile
[INFO] |  |  |  |     |  |  +- org.eclipse.rdf4j:rdf4j-queryparser-serql:jar:2.1.1:runtime
[INFO] |  |  |  |     |  |  \- org.eclipse.rdf4j:rdf4j-sail-model:jar:2.1.1:compile
[INFO] |  |  |  |     |  \- org.eclipse.rdf4j:rdf4j-queryalgebra-evaluation:jar:2.2.2:compile
[INFO] |  |  |  |     |     +- org.eclipse.rdf4j:rdf4j-repository-sparql:jar:2.2.2:compile
[INFO] |  |  |  |     |     |  \- org.eclipse.rdf4j:rdf4j-queryresultio-sparqlxml:jar:2.2.2:compile
[INFO] |  |  |  |     |     \- org.mapdb:mapdb:jar:1.0.8:compile
[INFO] |  |  |  |     \- org.eclipse.rdf4j:rdf4j-repository-sail:jar:2.1.1:compile
[INFO] |  |  |  |        +- org.eclipse.rdf4j:rdf4j-sail-api:jar:2.2.2:compile
[INFO] |  |  |  |        \- org.eclipse.rdf4j:rdf4j-http-client:jar:2.1.1:compile
[INFO] |  |  |  |           +- org.eclipse.rdf4j:rdf4j-http-protocol:jar:2.1.1:compile
[INFO] |  |  |  |           \- org.eclipse.rdf4j:rdf4j-queryresultio-api:jar:2.2.2:compile
[INFO] |  |  |  \- eu.optique-project:r2rml-api-jena-binding:jar:0.6.0:compile
[INFO] |  |  |     +- org.apache.commons:commons-rdf-jena:jar:0.3.0-incubating:compile
[INFO] |  |  |     |  +- org.apache.jena:jena-osgi:jar:3.1.1:compile
[INFO] |  |  |     |  |  +- _**org.apache.httpcomponents:httpclient-osgi:jar:4.5.2:compile**_
[INFO] |  |  |     |  |  +- org.apache.httpcomponents:httpcore-osgi:jar:4.4.4:compile
[INFO] |  |  |     |  |  +- org.apache.commons:commons-csv:jar:1.3:compile
[INFO] |  |  |     |  |  +- org.apache.thrift:libthrift:jar:0.9.3:compile
[INFO] |  |  |     |  |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  |  |     |  |  \- org.osgi:org.osgi.core:jar:6.0.0:compile
[INFO] |  |  |     |  +- org.apache.servicemix.bundles:org.apache.servicemix.bundles.xerces:jar:2.11.0_1:compile
[INFO] |  |  |     |  |  \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  |  |     |  \- com.github.andrewoma.dexx:collection:jar:0.6:compile
[INFO] |  |  |     \- org.apache.jena:jena-core:jar:3.1.1:compile
[INFO] |  |  |        +- org.apache.jena:jena-iri:jar:3.1.1:compile
[INFO] |  |  |        +- xerces:xercesImpl:jar:2.11.0:compile
[INFO] |  |  |        +- commons-cli:commons-cli:jar:1.3:compile
[INFO] |  |  |        \- org.apache.jena:jena-base:jar:3.1.1:compile
[INFO] |  |  |           \- org.apache.jena:jena-shaded-guava:jar:3.1.1:compile
[INFO] |  |  \- com.github.jsqlparser:jsqlparser:jar:1.0:compile
[INFO] |  +- org.apache.tomcat:tomcat-jdbc:jar:9.0.0.M22:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-juli:jar:9.0.0.M22:compile
[INFO] |  \- com.zaxxer:HikariCP:jar:2.6.3:compile
[INFO] +- it.unibz.inf.ontop:ontop-mapping-sql-owlapi:jar:3.0.0-beta-2:compile
[INFO] |  +- it.unibz.inf.ontop:ontop-mapping-owlapi:jar:3.0.0-beta-2:compile
[INFO] |  |  \- it.unibz.inf.ontop:ontop-mapping-core:jar:3.0.0-beta-2:compile
[INFO] |  |     +- org.apache.commons:commons-rdf-api:jar:0.3.0-incubating:compile
[INFO] |  |     \- org.antlr:antlr4-runtime:jar:4.7:compile
[INFO] |  +- net.sourceforge.owlapi:owlapi-api:jar:4.2.8:compile
[INFO] |  |  +- org.tukaani:xz:jar:1.5:compile
[INFO] |  |  +- net.sf.trove4j:trove4j:jar:3.0.3:compile
[INFO] |  |  +- com.google.inject.extensions:guice-multibindings:jar:4.0:compile
[INFO] |  |  \- commons-io:commons-io:jar:2.4:compile
[INFO] |  \- net.sourceforge.owlapi:owlapi-apibinding:jar:4.2.8:compile
[INFO] |     +- net.sourceforge.owlapi:owlapi-impl:jar:4.2.8:compile
[INFO] |     +- net.sourceforge.owlapi:owlapi-parsers:jar:4.2.8:compile
[INFO] |     +- net.sourceforge.owlapi:owlapi-oboformat:jar:4.2.8:compile
[INFO] |     +- net.sourceforge.owlapi:owlapi-tools:jar:4.2.8:compile
[INFO] |     +- net.sourceforge.owlapi:owlapi-fixers:jar:4.2.8:compile
[INFO] |     \- net.sourceforge.owlapi:owlapi-rio:jar:4.2.8:compile
[INFO] |        +- org.openrdf.sesame:sesame-model:jar:2.7.16:compile
[INFO] |        |  \- org.openrdf.sesame:sesame-util:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-api:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-languages:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-datatypes:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-binary:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-n3:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-nquads:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-ntriples:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-rdfjson:jar:2.7.16:compile
[INFO] |        |  \- com.fasterxml.jackson.core:jackson-core:jar:2.2.1:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-rdfxml:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-trix:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-turtle:jar:2.7.16:compile
[INFO] |        +- org.openrdf.sesame:sesame-rio-trig:jar:2.7.16:compile
[INFO] |        +- com.github.jsonld-java:jsonld-java-sesame:jar:0.5.0:compile
[INFO] |        |  \- com.github.jsonld-java:jsonld-java:jar:0.5.0:compile
[INFO] |        |     +- com.fasterxml.jackson.core:jackson-databind:jar:2.3.3:compile
[INFO] |        |     |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.3.0:compile
[INFO] |        |     +- org.apache.httpcomponents:httpclient-cache:jar:4.2.5:compile
[INFO] |        |     +- _**org.apache.httpcomponents:httpclient:jar:4.2.5:compile**_
[INFO] |        |     |  +- org.apache.httpcomponents:httpcore:jar:4.2.4:compile
[INFO] |        |     |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO] |        |     \- org.slf4j:jcl-over-slf4j:jar:1.7.7:compile
**......**
Thank you very much.
Best,
Coco

**Comment by HelloCoCooo** [comment]
Code snippet of **_<org.apache.http.conn.ssl.SSLSocketFactory: java.net.Socket connectSocket(java.net.Socket,java.net.InetSocketAddress,java.net.InetSocketAddress,org.apache.http.params.HttpParams)>_** in _**org.apache.httpcomponents:httpclient-osgi:4.5.2**_ (loaded version):
![q](https://user-images.githubusercontent.com/46306510/55816306-9186ed80-5b24-11e9-8558-04d1b3cc0d92.png)



Code snippet of **_<org.apache.http.conn.ssl.SSLSocketFactory: java.net.Socket connectSocket(java.net.Socket,java.net.InetSocketAddress,java.net.InetSocketAddress,org.apache.http.params.HttpParams)>_** in _**org.apache.httpcomponents:httpclient:4.2.5**_ 
 (shadowed but expected to invoke method):
![w](https://user-images.githubusercontent.com/46306510/55816313-977cce80-5b24-11e9-9bbd-c20b7222a59b.png)


As a result, these conflicting method included in **org.apache.httpcomponents:httpclient:4.2.5** deals with different cases, which changes the control flows and data flows. So being forced to use these methods in **org.apache.httpcomponents:httpclient-osgi:4.5.2** may lead to inconsisitent semantic behaviors.

**Comment by HelloCoCooo** [comment]
May I pull a request to fix it and #287 together?

**Comment by HelloCoCooo** [comment]
@bcogrel May I pull a request to fix it and #287 together?
Thanks for your attention.

**Comment by ghxiao** [comment]
Hi @HelloCoCooo, thanks for your report. It has been more than a year since the release of ontop v3-beta2. At this moment, we are not far from the release of v3-beta3. In the meanwhile, we have updated a lot the versions of the dependencies. Could you have a look at the version3 branch and see similar issues exist?

Btw, how did you find such potential conflicts? Are you using some static code analysis tools?

**Comment by HelloCoCooo** [comment]
@ghxiao 
Thanks for your reply.
I have analyzed the release of v3-beta3 today and found that the reported issues #288 and #287 indeed disappeared in this version.


In commit [eebcbf8](https://github.com/ontop/ontop/commit/eebcbf8e63fd746faf5f0db75c066a53ad20395d), you have exclude org.apache.jena:jena-osgi:jar from ontop, so that this conflict then is erased.
<img width="474" alt="11111111111" src="https://user-images.githubusercontent.com/46306510/56088010-1027b600-5eaa-11e9-84e3-feaa05017ff5.png">

**Comment by HelloCoCooo** [comment]
Now we can consider these issues have been fixed via  [eebcbf8](https://github.com/ontop/ontop/commit/eebcbf8e63fd746faf5f0db75c066a53ad20395d), and I will close #288 and #287 later.

**Comment by HelloCoCooo** [comment]
@ghxiao 
Hi, we combine static analysis and dynamic testing to detect such potencial semantic behaviors changes due to dependency conflicts.
By static analysis we can identify the dependency conflict issues and compare the differences of control flows and data flows between the shadowed method and loaded method (with the same signature).
Then, for the isomerous method pairs, we use test cases to see the impacts of such differences between shadowed method and loaded method on client project's semantic behaviors.

**Comment by ghxiao** [comment]
@HelloCoCooo thanks for checking the latest version!

Sure, I am very interested in the detection method so that in the future we will have a more systematic approach to avoid the issue related to such conflict, which is in general quite subtle and difficult to debug.
