### ISSUE TITLE
protege ontop output appear to be blank

### ISSUE THREAD

**Issue by gokulnath88** [ontop/ontop#293]
I have developed a ontology. When i run the resaoner in Ontop Sparql the output appear to be blank.Kindly guide me

urn:MAPID-1
:{species} a <{calcium}> . 
select "species","calcium" from agr

PREFIX : <http://www.semanticweb.org/murali/ontologies/2018/11/untitled-ontology-31#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT * WHERE {?species a :agr; :calcium ?values}

urn:MAPID-2
:{species} a <{magnesium}> . 
select "species","magnesium" from agr

PREFIX : <http://www.semanticweb.org/murali/ontologies/2018/11/untitled-ontology-31#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT * WHERE {?species a :agr; :magnesium ?values}

**Comment by juliencorman** [comment]
Hello, 

If this is your first experience of Ontop, you may want to follow this tutorial:
https://github.com/ontop/ontop-examples/tree/master/ontop-v3-tutorial

If the problem persists, we will need additional information to reproduce it, namely:
- the mapping file
- the ontology,
- a SQL script that generates a sample database with a schema identical to yours

Regards,
Julien
