### ISSUE TITLE
quotation marks in the SPARQL query

### ISSUE THREAD

**Issue by BrexLed** [ontop/ontop#295]
Dear Ontop Team,

when I try this query in protege it works:

SELECT ?v1 WHERE { 
?v4 a <http://isabox.com/ontologies/atti.owl#Determinazione> .
?v4 <http://isabox.com/ontologies/atti.owl#oggetto> ?v1 .
?v4 <http://isabox.com/ontologies/atti.owl#progressivo-annuale> "64" .
?v4 <http://isabox.com/ontologies/atti.owl#anno-registro-generale> "2018" . }

but, when I use it in the RDF4J workbench I have to remove the quote:

SELECT ?v1 WHERE { 
?v4 a <http://isabox.com/ontologies/atti.owl#Determinazione> .
?v4 <http://isabox.com/ontologies/atti.owl#oggetto> ?v1 .
?v4 <http://isabox.com/ontologies/atti.owl#progressivo-annuale> 64 .
?v4 <http://isabox.com/ontologies/atti.owl#anno-registro-generale> 2018 . }

The mapping and the ontology are the same, have you any ideas about that?

**Comment by ghxiao** [comment]
Which version of Ontop has been used?

It seems to me that the version without quote is more correct if the values are really integers. Does it also work on protege?

**Comment by BrexLed** [comment]
We are using 2 different version of Ontop, the 1.81.1 with protege and the 3.0.0 beta 2 with the workbench.

The 2 kind of queries (with or without qoute) work with quote inside protege exclusively, and without qoute in the workbench exclusively.

Now we are going to install the same version on Ontop and doing some test.

**Comment by BrexLed** [comment]
I have installed the 3.0.0 beta 2 in protege, It looks like that the 2 versions of Ontop have 2 different behaviors. Could it be?
The 3.0.0 beta 2 works whitout quote,
The 1.81.1 works with quote.

**Comment by ghxiao** [comment]
Indeed, In ontop-v3, datatype handling becomes more standard and restrict. I am not surprised the behaviors are different. Please use the latest version.
