### ISSUE TITLE
Bugs found in LeftJoinProfTest in ontop-docker-tests

### ISSUE THREAD

**Issue by martinkarbon** [ontop/ontop#307]
I am working on porting the new tests in`LeftJoinProfTest` done for H2 to the other DBs.
The new tests can be found in the branch https://github.com/martinkarbon/ontop/tree/feature/lj-prof-test-docker .

Here are some problems found:
 - [x] DESC is missing in ORDER BY for SQL Server
 - [ ] Minus tests return empty results for MySQL
 - [x] Boolean CASE expressions are not translated correctly for Oracle and SQL server (equalities to 0/1 are missing)
 - [x] SQL server and DB2 returns an integer for `AVG()` over integers
 - [x] Exception form testPreferences: 
                          com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-214, SQLSTATE=42822, SQLERRMC=V1...;ORDER BY;2, DRIVER=4.15.113

 To run these tests, one needs to use the novel DB Docker images that are in the branch https://github.com/ontop/ontop-dockertests/tree/lj-prof

**Comment by bcogrel** [comment]
MySQL (5.7) seems to have semantics issues with the encoding of MINUS as a left-join (filter is-null combined with a left-join).
