### ISSUE TITLE
Some potential NPE bugs

### ISSUE THREAD

**Issue by JulyChen728** [ontop/ontop#309]
Hi all,
Our bug scanner has reported some potential NPE bugs.

1.The variable `set` is checked for whether being `null` or not at [ResultSetTableModel.java#L87](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/treemodels/ResultSetTableModel.java#L87) . So when `set` invokes its method `getStatement()` at [ResultSetTableModel.java#L83](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/treemodels/ResultSetTableModel.java#L83) , a NullPointerException may take place.

A similar situation occurs in [SavedQueriesPanel.java#L76](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/panels/SavedQueriesPanel.java#L76) and [SavedQueriesPanel.java#L73](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/panels/SavedQueriesPanel.java#L73) . (For the variable `queryController` )

2.The second bug is caused by the `return null` in function [findParentContainer()](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/component/SQLResultTable.java#L157) . A possible call chain is [findParentContainer()](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/component/SQLResultTable.java#L95) => [findFocus()](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/component/SQLResultTable.java#L96) . And a NullPointerException may take place in function [findFocus()](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/component/SQLResultTable.java#L161) .

3.The third bug is caused by the `return null` in function [getTreeNode()](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/treemodels/QueryControllerTreeModel.java#L215) . When the return value of the function `getTreeNode()` invokes its method [setQuery()](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/treemodels/QueryControllerTreeModel.java#L192) , a NullPointerException may occur.

A similar statement occurs at [Line200](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/treemodels/QueryControllerTreeModel.java#L200) . 

4.The function [getNode()](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/treemodels/QueryControllerTreeModel.java#L256) may return `null` when the while statement block is skipped, and a NPE may take place when the return value of the method `getNode()` invokes its method [getPath()](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/panels/SavedQueriesPanel.java#L353) . 

A similar return null situation is in method [getElementQuery()](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/gui/treemodels/QueryControllerTreeModel.java#L281) , and the NPE may occur at [SavedQueriesPanel.java#L322](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/panels/SavedQueriesPanel.java#L322) and [SavedQueriesPanel.java#L311](https://github.com/ontop/ontop/tree/version4/client/protege/src/main/java/it/unibz/inf/ontop/protege/panels/SavedQueriesPanel.java#L311) .

Thanks.

**Comment by ITWOI** [comment]
Hi, we have reported the bugs a while ago would you please take a look and confirm if they are real bugs. We have been conducting an experiment to measure the accuracy of our static checker. We would be deeply appreciated if you can provide some feedback!

**Comment by ghxiao** [comment]
Hi, I won't say they are real bugs. The relevant code is used to read the query files generated by Ontop. These NPEs should not happen. Of course one can handle this is in a better manner, for the cases where the files haven modified outside of Ontop manually and becomes invalid.
