### ISSUE TITLE
plugin changes output file for OBO ontologies

### ISSUE THREAD

**Issue by nicolevasilevsky** [ontop/ontop#310]
### Description

After installing the Ontop OBDA Protége plugin, we were getting huge diffs in HPO, Mondo and CRO.

### Attached material

More details are in this ticket here:
https://github.com/protegeproject/protege/issues/926

### Versions

We are using Protege 5.5. This happened to me a few months ago, and @drseb had this issue last week.

**Comment by LCCarmody** [comment]
With @matentzn help, the easiest work around was to add the files to .gitignore
(i.e., src/ontology/maxo-edit.obda).  It worked, but I don't know what the plugin was for and I didn't remember to report it to protege.

**Comment by ghxiao** [comment]
Hi, the issue has been fixed in the v3.0.1 release. Please give it a try. Please feel free to reopen the issue if the problem persists.
