### ISSUE TITLE
[v3] Unbound variable when there is no LIMIT

### ISSUE THREAD

**Issue by seralf** [ontop/ontop#317]
### Description

During materialization (I'm using dremio as a source) the process exited with an exeption each time the LIMIT part of the SQL query/view is omitted.

### Steps to Reproduce

1) prepare a simple R2RML mapping, using some of the columns from the view:

```
<view_region> a rr:R2RMLView ;

rr:sqlQuery  """
    SELECT 
        REG.REG_CODE AS REG_CODE,
        REG.REG_SLUG AS REG_SLUG,
        REG.REG_NAME AS REG_NAME,
        REG.NUTS2 AS NUTS2
    FROM "regions_view" AS REG 
""" ;
.

<tmap_region> a rr:TriplesMap ;
  rr:logicalTable <view_region> ;

  ...
```

2) execute the materialization with something like:

```bash
$ ontop materialize -m {mapping_file} --format "turtle" -o {out_file} -p configuration.properties
```

**Expected behavior:**

the process should materialize the dump `{out_file}`

**Actual behavior:**

the process exited with exception:
```
it.unibz.inf.ontop.answering.reformulation.impl.QuestQueryProcessor - Unexpected exception: Unbound variable found in WHERE clause: REG_SLUG1m4
```

**Reproduces how often:**
it happens all the time

### Attached material

I'm using ontop version 3 on dremio

### Versions

ontop version 3

### Additional Information

If a `LIMIT` clause is added to the query, everything works as expected.

**Comment by ghxiao** [comment]
Hi, 

This problem of `Unbound variable found in WHERE clause: REG_SLUG1m4` should be due to the internal bug of Ontop, which has been solved in v4. 

This issue is not due to Dremio. However, we are refactoring the DB support part and temporarily we don't officially support Dremio. Proper support of Dremio will be part of the v4.1 release.

**Comment by seralf** [comment]
HI ghxiao thanks very much for the reply and the good news about the issue! :-)

Specifically talking about dremio: in my team, we are experimenting with ontop (directly, or using a java/scala wrapper, by API) on dremio, in some different scenario. If we may be of help in any way for giving some feedback about improving the support on this part, just let us know or write me directly! 
thank you again

**Comment by bcogrel** [comment]
I am closing the issue since it relates to an old version of Ontop. If the problems re-occurs with Ontop 4.x, feel free to re-open it.

As for Dremio support, it is about to arrive in the next release (4.1.0), which we are finalizing.
