### ISSUE TITLE
Can't Map to a double in MySQL

### ISSUE THREAD

**Issue by khanhnvo** [ontop/ontop#320]
### Description

[Description of the issue]
Can't Map to a double in MySQL.  My MySQL has a double column and I can't seem to map a dataytype to that double.  When I map it as a XSD:DOUBLE, Ontop converts it to a decimal.

In protégé, the sparql conversion to sql converts the datatype double to  DECIMAL. If you take that SQL and paste it into MYSQL, you get 1 and 0s.

For example:
:has_eccentricity_value {has_Eccentricity_value}^^xsd:double;

Ontop converts the spaql to SQL with "has_Eccentricity_alue as DECIMAL, making the results a 1 or 0 instead of a doubles value.

### Steps to Reproduce

1.  Try mapping to a doubles value in MySQL
 
**Expected behavior:** Get back the value such as 0.001234 instead of 1 or 0.

**Actual behavior:** Returning 1 or 0
**Reproduces how often:** Every time

### Attached material

Informations about the attachments (ontology, mappings and queries that are necessary to reproduce the problem)
Provide the log file (more information on how to obtain it in the guidelines)

### Versions

Which version of Ontop are you using 
![doubles error](https://user-images.githubusercontent.com/49532551/70502814-ad3cfc00-1ad6-11ea-8eac-cb3d757d9ffd.jpg)
![doubles error2](https://user-images.githubusercontent.com/49532551/70502815-add59280-1ad6-11ea-80e2-0105420b8ac2.jpg)
![doubles error3](https://user-images.githubusercontent.com/49532551/70502816-add59280-1ad6-11ea-8dd2-17d821f6a50e.jpg)

and in which setting (Protege, SPARQL endpoint, Cli, Java API, ...)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ghxiao** [comment]
Hi,

We didn't manage to reproduce the bug with the latest version of Ontop. Likely it has been fixed in the meantime.

Feel free to reopen it if the issue persists.
