### ISSUE TITLE
RefObjectMap seems to be broken in Ontop 3.0.1

### ISSUE THREAD

**Issue by mchaloupka** [ontop/ontop#324]
### Description

Ontop does not seem to be able to handle `RefObjectMap`. I have tried to start Ontop with a sample database generated using bsbm. Ontop does not start.

### Steps to Reproduce

1. Prepare a MySQL database
2. Start ontop using the following command:
```
docker run --rm -it -v {...}:/opt/ontop/jdbc -v {...}:/static -e ONTOP_MAPPING_FILE=/static/mapping.ttl -e ONTOP_PROPERTIES_FILE=/static/ontop.mysql.properties -p 8080:8080 ontop/ontop-endpoint
```

**Expected behavior:**
Ontop should start.

**Actual behavior:**
The are lots of errors and the execution finishes. Sample error (others are similar):
```
Error: The source query does not provide the attribute nr (variable nr) required by the target atom.
Problem location: source query of the mapping assertion
[id: mapping-join--2111843245
target atom: triple(s,p,o) with s/URI2T4("http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/Product{}",nr), p/URI1("http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/producer"), o/URI2T2("http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/Producer{}",nr) source query: SELECT * FROM (SELECT * FROM product) AS child, (SELECT * FROM producer) AS parent WHERE child.producer=parent.nr]
```

**Reproduces how often:** Every time

### Attached material

* SQL files required to fill the MySQL database
* Mapping file
* Properties file

[files.zip](https://github.com/ontop/ontop/files/4049491/files.zip)

### Versions

* 3.0.1

**Comment by ghxiao** [comment]
Thanks @mchaloupka for reporting this. We will look it into.

**Comment by vhf** [comment]
I'm having the same issue and I strongly suspect `select *` to be cause. In all my queries using `*` be it `select * …` or `select t.* …`, Ontop seems to unable to find the attributes/variables required by the target atom.

For instance when `select * from foo` returns the columns `id` and `name`, this will fail:

```
<#FooBar>
	rr:logicalTable [ rr:sqlQuery """select * from foo""" ];
	
	rr:subjectMap [
		rr:template "https://example.com/{id}/{name}" ;
	];
	
	rr:predicateObjectMap [
		rr:predicate wdt:P123 ;
		rr:objectMap [
			rr:constant <https://www.wikidata.org/wiki/Q789> ;
		];
	]
.
```

because 
> Error: The source query does not provide the attribute id (variable id) required by the target atom.

and then


```
<#FooBar>
	rr:logicalTable [ rr:sqlQuery """select *, id from foo""" ];
	
	rr:subjectMap [
		rr:template "https://example.com/{id}/{name}" ;
	];
	
	rr:predicateObjectMap [
		rr:predicate wdt:P123 ;
		rr:objectMap [
			rr:constant <https://www.wikidata.org/wiki/Q789> ;
		];
	]
.
```

will fail with:
 
> Error: The source query does not provide the attribute name (variable name) required by the target atom.

Although the columns are properly named in the SQL results:
```
mysql> describe foo;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| id               | int(11)      | NO   | PRI | NULL    | auto_increment |
| name             | varchar(100) | NO   | UNI | NULL    |                |
+------------------+--------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)

mysql> select * from foo;
+----+------+
| id | name |
+----+------+
|  1 | test |
+----+------+
1 row in set (0.00 sec)
```

**Comment by bcogrel** [comment]
@mchaloupka, thanks a lot for reporting the issue and providing the files. I have just tested with the current version4 branch, and it now works, thanks to the important refactoring done around the SQL parser recently.

These changes will be brought to the next RC release of Ontop 4. Unfortunately, we have no plan to backport them to 3.x.

@vhf, I think you are facing a different problem, as I cannot see any `rr:parentTriplesMap` triple in your example. Could you please give a try to the 4.0-snapshot version of [our Docker image](https://hub.docker.com/r/ontop/ontop-endpoint/tags)? If the problem still persists, feel free to fill another issue. 

Best,
Benjamin

**Comment by vhf** [comment]
(Sorry for the misplaced issue then, I tried the 4.0-snapshot and it works for me, thanks a lot!)
