### ISSUE TITLE
Can't map using prefix in the URI definition

### ISSUE THREAD

**Issue by adrianogoncalves** [ontop/ontop#331]
Hi,
I'm trying to map the data with a different base URI than ontology's. I tried defining a prefix for data, in Protegé, and use it in Mapping manager, like this:

dataUri:person/{id} a foaf:Person .

But it doesn't work. The plugin just changes it to "<nulldataUri:person/{id} .>".

**Comment by ghxiao** [comment]
Hi,

After adding a prefix in Protege, you might need to restart Protege to reload the ontology. Let us know if this helps.
