### ISSUE TITLE
GeoSPARQL Functions

### ISSUE THREAD

**Issue by ghxiao** [ontop/ontop#335]
# Implement GeoSPARQL Functions  

## Table 1 – Simple Features Topological Relations in the GeoSPARQL Specification.

- [x] geof:sfEquals
- [x] geof:sfDisjoint
- [x] geof:sfIntersects
- [x] geof:sfTouchs
- [x] geof:sfWithin
- [x] geof:sfContains
- [x] geof:sfOverlaps
- [x] geof:sfCrosses

As an example, `geof:sfWithin` has already been implemented in https://github.com/ontop/ontop/commit/7f7c08b79d637041bc01e335f36a9cec68e4ab5d.

The test case is implemented in the https://github.com/ontop/ontop/commit/9db841c7af7285e3f1d5e798bf90a7881fa72033 in the class `GeoSPARQLTest` using H2GIS.

**Comment by ghxiao** [comment]
## SRID

According to GeoSPARQL standard:
    Req 11 The URI <http://www.opengis.net/def/crs/OGC/1.3/CRS84> shall be assumed as the spatial reference system for geo:wktLiterals that do not specify. 
    
E.g.
`"Point(46.49067 11.33982)"^^geo:wktLiteral`
 and
`"<http://www.opengis.net/def/crs/OGC/1.3/CRS84> Point(46.49067, 11.33982)"^^geo:wktLiteral` 
are equivalent

Examples in other SRIDs

- `"<http://www.opengis.net/def/crs/EPSG/0/4326> POINT (11.33982 46.49067)"^^geo:wktLiteral`
- `"<http://www.opengis.net/def/crs/EPSG/0/3044> POINT (668682.853 5122639.964)^^geo:wktLiteral`

### Proposal:
- support WKT literals as constants with SRIDs inside (as above)
- support WKT literals from Literals  template with constant SRIDs inside, e.g,
`“{geom}”^^geo:wktLiteral` -> default CRS84
`"<http://www.opengis.net/def/crs/EPSG/0/3044> {geom}”^^geo:wktLiteral`
`"<http://www.opengis.net/def/crs/EPSG/0/3044> POINT ({x} {y})^^geo:wktLiteral`
- NOT support storing the literals with SRID URLs in one DB column, e.g.
“{geom}”^^geo:wktLiteral with geom is column with a value `“<http://www.opengis.net/def/crs/EPSG/0/3044> POINT (668682.853 5122639.964)”`.
Such values do not make sense in GIS systems.
NB: PostGIS uses a non-standard EWKT syntax storing SRID AsEWKT `“SRID=3044;POINT (668682.853 5122639.964)”`

**Comment by alpano-unibz** [comment]
### **Table 2 – Egenhofer Topological Relations in the GeoSPARQL Specification.**

For some of the the following functions the same equivalent representations from the simple feature topological relations are used. They have been noted where it is the case:
- [x] geof:ehCovers
- [x] geof:ehCoveredBy
- [x] geof:ehEquals <-> geof:sfEquals
- [x] geof:ehDisjoint <-> geof:sfDisjoint
- [x] geof:ehMeet <-> geof:sfTouches
- [x] geof:ehContains <-> geof:sfContains

For the following relations, the respective simple relation functions are currently being used, however the equivalence might not be 100% and is being reviewed.
- [ ] geof:ehOverlap <-> geof:sfOverlaps
- [ ] geof:ehInside <-> geof:sfWithin

The DE-9IM model specified for each function in http://schemas.opengis.net/geosparql/1.0/geosparql_vocab_all.rdf was used to determine equivalence where applicable.

**Comment by alpano-unibz** [comment]
### Table 3 – RCC8 Topological Relations in the GeoSPARQL Specification.

Egenhofer relations only apply to 2-dimensional geometries (e.g. polygons).

- [x] geof:rcc8eq <--> geof:sfEquals
- [x] geof:rcc8dc <--> geof:sfDisjoint
- [x] geof:rcc8ec <--> geof:sfTouches
- [x] geof:rcc8po <--> geof:sfOverlaps
- [x] geof:rcc8tppi <--> geof:sfContains
- [x] geof:rcc8tpp <--> geof:sfWithin
- [ ] geof:rcc8ntpp
- [ ] geof:rcc8ntppi

geof:rcc8ntppi --> The respective function ST_CONTAINSPROPERLY in PostGIS implementes this function. There is no implementation for H2GIS.

No SQL implementation of geof:rcc8ntpp, unlike geof:sfContains, the geometries' boundaries should not touch.

**Comment by kontchakov** [comment]
Is geof:rcc8ntpp not the same as geof:sfWithin?

9-Intersections are equivalent to RCC-8 for a suitably restricted class of spatial objects (e.g., polygons). However, one has to be a bit more careful even with "2-dimensional geometries" - there are bizarre objects there.

**Comment by alpano-unibz** [comment]
### Table 4 – Non-Topological Functions in the GeoSPARQL Specification.

[x] geof:distance
[ ] geof:boundary
[x] geof:buffer
[ ] geof:convexHull
[ ] geof:difference
[ ] geof:envelope
[x] geof:intersection
[ ] geof:getSRID
[ ] geof:symDifference
[ ] geof:union
[ ] geof:relate

Except for buffer, distance and relate, all other functions take geometries as inputs and have fixed arity.
