### ISSUE TITLE
List of built-in functions supported by ontop

### ISSUE THREAD

**Issue by marianormuro** [ontop/ontop#34]
There is no list of the functions that are supported by ontop/quest, we should add a wiki page with that information and maintain it as it grows.

There should be a list of the SPARQL functionality available, e.g.,

OPTIONAL
AS
FILTER
ORDER BY
LIMIT

etc.

**Comment by bcogrel** [comment]
As SPARQL: https://ontop-vkg.org/guide/compliance.html#sparql-1-1
