### ISSUE TITLE
Where to find more under layer information about models like Quest

### ISSUE THREAD

**Issue by nicholaslsq** [ontop/ontop#347]
For now, I need to find some information about how Quest working. As the older wiki was moved to ontop-vkg.org, I can't find it on ontop-vkg.org, instead of a simple "how-to" tutorials. So, does ontop-vkg.org has sufficient information about those under layer models like Quest and OBDA, etc. I can't find it on github wiki nor ontop-vkg.org.

**Comment by bcogrel** [comment]
Hi,

Quest is a former name of the Ontop query engine. We tend not to use it anymore (although it still appears in the name of several historical classes but not in interfaces).

Could you please tell us which kind of information (for which purposes?) are you looking at? 

For the conceptual and formal aspects, I encourage you to look at our publications (see https://ontop-vkg.org/research/publications)  and in particular at [our latest paper](https://research.bcgl.fr/pdfs/ontop-iswc20.pdf), which is describing Ontop 4.0, and our ["classical" paper describing the general architecture](http://www.semantic-web-journal.net/content/ontop-answering-sparql-queries-over-relational-databases-1).

Regarding the internals of Ontop, our technical documentation is indeed at the moment very limited. Content can be found in the [dev section](https://ontop-vkg.org/dev/). Some additional low-level documentation is still present in [our former wiki](https://github.com/ontop/ontop/wiki) but it is largely deprecated as it has been written for Ontop 1.x, which differs substantially from the newest version.

Best,
Benjamin
