### ISSUE TITLE
fix obda-to-r2rml covert script: `rr:column` needs to be quoted

### ISSUE THREAD

**Issue by ghxiao** [ontop/ontop#348]
See ontop/ontop-api-examples#2

The obda-to-r2rml does not produce correct mapping

E.g. the column in,
` <http://www.w3.org/ns/r2rml#column>                                     "wr_name"`

needs to be quoted:

` <http://www.w3.org/ns/r2rml#column>                                     "\"wr_name\""`

**Comment by bcogrel** [comment]
It should have been fixed in the `version4` branch. If it is not the case, please re-open it.
