### ISSUE TITLE
equivalence classes

### ISSUE THREAD

**Issue by martinrezk** [ontop/ontop#36]
Apparently equivalence classes are not working in ontop unless we set this preference
That is,

if you have 
A=B, 
A(a) 

and you ask the classes of "a" you only get A and not B unless you set this to true

pref.setCurrentValueOf(QuestPreferences.OPTIMIZE_EQUIVALENCES, "false"); is required

This must be fixed

**Comment by bcogrel** [comment]
This option has been removed in Ontop 3.0.0 beta 2.
