### ISSUE TITLE
logback config file ignored by Ontop CLI

### ISSUE THREAD

**Issue by ghxiao** [ontop/ontop#361]
In the latest releases of Ontop, the logback config file has been ignored by CLI. 
The reason is that the Spring Boot uses a different option than the classical logback file.

**Comment by ghxiao** [comment]
closed by 8ca2dc105614b916349af60bdade4db0020a98a6

**Comment by logicalfarhad** [comment]
@ghxiao The problem has not been solved I guess. When I run the CLI application using the command line I am getting the following error. 
![Ontop Error](https://user-images.githubusercontent.com/2293175/130236795-9d139b08-73a5-4dd1-b996-b69855b84496.png)
Do you suggest me anything to get rid of this error? 

Thanks in advance 
Farhad

**Comment by fracorco** [comment]
I had the same issue (while testing the endpoint locally within the Eclipse IDE) and if I'm not wrong -- at least in my case -- it was due to the following line in [`it.unibz.inf.ontop.cli.OntopEndpoint`](https://github.com/ontop/ontop/blob/a8bebeaa8cebb1356bdd2823127b9f13b7663b8e/client/cli/src/main/java/it/unibz/inf/ontop/cli/OntopEndpoint.java#L116), end of method `run()`

```java
// Spring boot gives warns when the logback.configurationFile property is set
System.setProperty("logback.configurationFile", "");
```

As a quick & dirty solution I commented that line and got rid of the issue, but a proper solution considering the case for which that line was originally entered has to be devised.

Just HTH,
Francesco

**Comment by logicalfarhad** [comment]
@fracorco Thanks! I also found the quick and dirty solution. However, a proper solution needed to be implemented. 

BR
Farhad

**Comment by ghxiao** [comment]
Hi @logicalfarhad and @fanavarro,

There are several separate but related issues/observations here. 

1) The problem should only happen when running Ontop inside IDE (Eclipse or IntelliJ). Running packaged Ontop CLI or Docker should work fine. @logicalfarhad how did you run Ontop?

2) The logback config file is not ignored. To see more log info in an IDE when developing, you just need to adjust the logging level here: https://github.com/ontop/ontop/blob/version4/client/cli/src/main/resources/logback.xml
Actually, the level used to be DEBUG. @juliencorman I saw that you changed it to ERROR in https://github.com/ontop/ontop/commit/999c0e68ff9d8602975c39c8ca1ecc97ac6c1596. Is there any reason?

3) The error message about "ch.qos.logback.core.LogbackException: Unexpected filename extension of file [...]. Should be either .groovy or .xml" seems to be new. It might be from a newer version of SpringBoot. This requires some investigation but does not affect the behavior of logging (if not set to ERROR).

4) The line of code (`System.setProperty("logback.configurationFile", "");`)  there was needed to surpass a warning from SpringBoot. It should not affect the behavior of logging. I could not understand why it makes changes on your machines.

**Comment by bcogrel** [comment]
@ghxiao , regarding point 2), I would expect the command line interface not to run with the DEBUG level by default. Instead, the user has to explicitly add an option to the command line to enable this verbose mode.

Also when running the CI, it is important that logging levels remain at ERROR to avoid polluting the logs. The developer can manually turn the logback config to DEBUG locally on his/her machine, without committing it.

**Comment by ghxiao** [comment]
@bcogrel 
Ontop CLI ships two config files: `logback.xml` (`INFO` level, default),`logback-debug.xml` (`DEBUG` level).

The docker image uses `logback.xml` by default and `logback-debug.xml` when `ONTOP_DEBUG` is set.

Btw, I had to revert the logging level of`logback-debug.xml` to `DEBUG` in https://github.com/ontop/ontop/commit/20a9dea6c730df7711b4ceede9e4c4da8b8ba0ee. This file is not used by CI.

**Comment by logicalfarhad** [comment]
> Hi @logicalfarhad and @fanavarro,
> 
> There are several separate but related issues/observations here.
> 
> 1. The problem should only happen when running Ontop inside IDE (Eclipse or IntelliJ). Running packaged Ontop CLI or Docker should work fine. @logicalfarhad how did you run Ontop?
> 2. The logback config file is not ignored. To see more log info in an IDE when developing, you just need to adjust the logging level here: https://github.com/ontop/ontop/blob/version4/client/cli/src/main/resources/logback.xml
>    Actually, the level used to be DEBUG. @juliencorman I saw that you changed it to ERROR in [999c0e6](https://github.com/ontop/ontop/commit/999c0e68ff9d8602975c39c8ca1ecc97ac6c1596). Is there any reason?
> 3. The error message about "ch.qos.logback.core.LogbackException: Unexpected filename extension of file [...]. Should be either .groovy or .xml" seems to be new. It might be from a newer version of SpringBoot. This requires some investigation but does not affect the behavior of logging (if not set to ERROR).
> 4. The line of code (`System.setProperty("logback.configurationFile", "");`)  there was needed to surpass a warning from SpringBoot. It should not affect the behavior of logging. I could not understand why it makes changes on your machines.

@ghxiao thanks for your reply. I just ran _**./ontop endpoint -m input/university-complete.obda -t input/university-complete.ttl -p input/university-complete.properties --cors-allowed-origins=***_ for ontop CLI and saw the error mentioned earlier. 

Thanks 
Farhad
