### ISSUE TITLE
Performance regression from v3.0.1 to v4.0.2

### ISSUE THREAD

**Issue by dbilid** [ontop/ontop#363]
### Description

Hello, 

I have executed some benchmarks on some versions of Ontop (with existential reasoning), and I found that performance in version 4 (4.0.2) is worse than performance in version 3 (3.0.1).

I have used PostgreSQL 11.3 as a backend in a machine with 24 GB of memory and the following memory configuration:

_shared_buffers       = 15GB
effective_cache_size = 20GB
maintenance_work_mem =  1GB
work_mem             = 15GB_

Specifically I have found that:

- for NPD benchmark scale 100, the average execution time increases from 25274 to 53757 ms
- for LUBM benchmark scale 100 (from [here](https://github.com/ontop/iswc2014-benchmark)), the average execution time increases from 3931 to 21624 ms
- for Wisconsin benchmark with 1 million tuple tables (from [here](https://github.com/ontop/ontop-examples/tree/master/iswc-2017-cost/wisconsin-experiment)), for 3 atom queries average execution time increases from 53624 to 254008 ms and for 4 atom queries from 64048 to 318679 ms.

For example, for query 01 of LUBM benchmark and for fresh started PostgreSQL with cold caches, the execution time increases from 685 to 9640 ms. Below are the SQL queries retrieved by PostgreSQL from the two different versions of Ontop for the specific query:

Version3:
```
SELECT *
FROM (
SELECT DISTINCT 
   1 AS "xQuestType", NULL AS "xLang", ('http://www.Department' || REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST('0' AS VARCHAR(10485760)), '%', '%25'), ' ', '%20'), '!', '%21'), '"', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '''', '%27'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '<', '%3C'), '=', '%3D'), '>', '%3E'), '?', '%3F'), '@', '%40'), '[', '%5B'), '\', '%5C'), ']', '%5D'), '^', '%5E'), '`', '%60'), '{', '%7B'), '|', '%7C'), '}', '%7D') || '.University' || REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST('0' AS VARCHAR(10485760)), '%', '%25'), ' ', '%20'), '!', '%21'), '"', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '''', '%27'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '<', '%3C'), '=', '%3D'), '>', '%3E'), '?', '%3F'), '@', '%40'), '[', '%5B'), '\', '%5C'), ']', '%5D'), '^', '%5E'), '`', '%60'), '{', '%7B'), '|', '%7C'), '}', '%7D') || '.edu/GraduateStudent' || REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST("Qpublic_takescoursesVIEW0"."studid" AS VARCHAR(10485760)), '%', '%25'), ' ', '%20'), '!', '%21'), '"', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '''', '%27'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '<', '%3C'), '=', '%3D'), '>', '%3E'), '?', '%3F'), '@', '%40'), '[', '%5B'), '\', '%5C'), ']', '%5D'), '^', '%5E'), '`', '%60'), '{', '%7B'), '|', '%7C'), '}', '%7D')) AS "x"
FROM 
    "public"."takescourses" "Qpublic_takescoursesVIEW0",
    "public"."students" "Qpublic_studentsVIEW1"
WHERE 
    "Qpublic_takescoursesVIEW0"."studid" IS NOT NULL AND
    ("Qpublic_takescoursesVIEW0"."studid" = "Qpublic_studentsVIEW1"."id") AND
    ('0' = "Qpublic_takescoursesVIEW0"."depid") AND
    ('0' = "Qpublic_takescoursesVIEW0"."uniid") AND
    (1 = "Qpublic_takescoursesVIEW0"."coursetype") AND
    ('0' = "Qpublic_takescoursesVIEW0"."courseid") AND
    ('0' = "Qpublic_studentsVIEW1"."depid") AND
    ('0' = "Qpublic_studentsVIEW1"."uniid") AND
    (1 = "Qpublic_studentsVIEW1"."stype")
) SUB_QVIEW
```

version 4:
```
SELECT DISTINCT ('http://www.Department' || CAST(v1."depid" AS TEXT) || '.University' || CAST(v1."uniid" AS TEXT) || '.edu/GraduateStudent' || CAST(v1."id" AS TEXT)) AS "v0"
        FROM "students" v1, "takescourses" v2
        WHERE 
(

('http://www.Department' || CAST(v1."depid" AS TEXT) || '.University' || CAST(v1."uniid" AS TEXT) || '.edu/GraduateStudent' || CAST(v1."id" AS TEXT)) = ('http://www.Department' || CAST(v2."depid" 
AS TEXT) || '.University' || CAST(v2."uniid" AS TEXT) || '.edu/GraduateStudent' || CAST(v2."studid" AS TEXT)) 

AND 'http://www.Department0.University0.edu/GraduateCourse0' = ('http://www.Department' || CAST(v2."depid" AS TEXT) || '.University' || CAST(v2."uniid" AS TEXT) || '.edu/GraduateCourse' || CAST(v2."courseid" AS TEXT)) 

AND v2."depid" IS NOT NULL 

AND v2."uniid" IS NOT NULL 

AND v2."studid" IS NOT NULL 

AND  v2."courseid" IS NOT NULL 

AND 1 = v1."stype" 

AND 1 = v2."coursetype"

)
```

So, I can see that there are joins over IRIs in the latest version. Is this due to the new translation method? Is it something that can be avoided? I suspect that this happens because you now consider that the same value can be produced from different IRI templates. Is this correct? Do you have plans to improve this?

Best,
Dimitris

**Comment by bcogrel** [comment]
Hi Dimitris,

Thanks a lot for this rich feedback!

Yes, your intuition is right, version 4 only decomposes an IRI template when it can prove that it is injective. Prior to it, in versions 1.x and 3.0, IRI templates were simply decomposed without checking if it was actually correct to do so.

In the last query, the IRI template does not always use a safe separator between the arguments as recommended by R2RML (https://www.w3.org/TR/r2rml/#note-safe-separators). One needs to look at lexical spaces of the concrete datatypes of its arguments to prove that it is injective here. Version 4 at the moment does not go that far and only considers the presence of safe separators.

My suggestion would be to improve the mappings used in the benchmark so as to follow the strong recommendation of R2RML and not give an unfair advantage to unsound implementations.

I don't have yet a clear opinion whether or it would be a good idea to consider the argument datatypes for proving injectivity in the code of Ontop. I am still looking for a good concrete use case where one has a good reason not to fix the IRI template in the mapping. 

Regarding performance, have you seen other potential problems than missed IRI decompositions?

Best,
Benjamin

**Comment by bcogrel** [comment]
Hi,

Looking again at the R2RML specification, I can see that R2RML does not a crisp recommendation on how to make the IRI templates safe (injective). On one side, it suggests using characters that would be percent-encoded (the good practice we recommend) but on the other side it keeps open the possibility to consider lexical spaces for proving that the IRI template is safe using these columns.

We are now having a good motivation for implementing this feature. We will look at it soon.

Best,
Benjamin

**Comment by dbilid** [comment]
Hello Benjamin,

Thanks for your reply. Regarding other potential problems, no, I have not seen something.

Thanks,
Dimitris

**Comment by bcogrel** [comment]
This decomposition of IRI templates has been implemented for integers, decimals, floats, doubles and UUIDs: https://github.com/ontop/ontop/commit/788c42dc3031f7039e1545f74b5b49439012a568

It will take part of the 4.2.0 release.
