### ISSUE TITLE
"EquivalentTo"and "p some C" returns no value

### ISSUE THREAD

**Issue by qootec** [ontop/ontop#371]
### Description

I was extending my ontology with some "EquivalentTo".
Unfortunately, Ontop does not seem to return any of the result that I expected.

### Steps to Reproduce

1. Create a small ontology:
* Concepts: A and B
* Object properties: hasB (in principle with domain A and Range B, but I didn't specify these)
* Concept: GoodA
  having an "Equivalent To" filled with:
```
  A and hasB some B
```

2. Create an Ontop mapping
```
target :a/{idA} a :A ; :hasB :b/{idB} . :b/{idB} a B .
source select idA, idB from MyTable
```
The database table MyTable contains rows with all idA and idB fields nicely filled.

3. Query the result
```
select ?id {
	?id a :GoodA .
}
```

**Expected behavior:**
Since every A has some B associated to it by construction, I would expect that all my "table rows" satisfy my concept "GoodA'.

**Actual behavior:**
The query doesn't return any value at all.

I also tried some queries that are based on the same data and should therefore return output similar to the full GoodA query:
```
select ?idA, ?idB {
	?idA :hasB ?idB .
}

select ?idA, ?idB {
	?idA a :A; :hasB ?idB .
}

select ?idA, ?idB {
	?idA a :A; :hasB ?idB .
        ?idB a :B .
}
```
All these queries return all rows from my table.

If I reduce the "Equivalent To" to just "A", then all rows are returned.
If I reduce the "Equivalent To" to just "hasB some B", then nothing is returned.
That leads me to think that my original syntax for "hasB some B" is at fault, but that looks ok to me, no?

**Reproduces how often:**

Consistently

### Versions
* Protege 5.5.0
* Ontop plugin 4.1 (built from git commit 4e6930ac94bc3548ba7347166229d483a344fc76)

**Comment by bcogrel** [comment]
Hi,

What you are asking for goes beyond the profile that is supported by Ontop (OWL 2 QL).

The "advanced" reasoning that Ontop can do is what we call existential reasoning. It is disabled by default, you need to add the following entry to the properties file:
```properties
ontop.existentialReasoning=true
```

You can for instance specify that for each graduate student, it exists a professor by which he/she is supervised by (see  https://ontop-vkg.org/tutorial/mapping/existential.html). 

For more details on the OWL 2 QL profile, I suggest you to have a look at the following slides (starting from slide 20): 
https://raw.githubusercontent.com/ontop/ontop-examples/master/cikm-2018-tutorial/1-introduction.pdf

Best,
Benjamin
