### ISSUE TITLE
Question about generated SQL for OPTIONAL pattern

### ISSUE THREAD

**Issue by LorenzBuehmann** [ontop/ontop#380]
Hi again,

not sure if this is a bug or if I misunderstand SQL and/or misused Ontop, thus, I tried to ask on the mailing list (aka Google Group ), but for whatever reason I cannot see my thread there. so please consider it as question if it's a bug.

JDBC
``` sql
CREATE TABLE IF NOT EXISTS "p1" (s varchar(255) NOT NULL, o varchar(255) NOT NULL)```
```

Mapping

```
[MappingDeclaration] @collection [[
mappingId     "p1_mapping"
source        SELECT "s", "o" FROM "p1"
target        <{s}> <http://ex.org/p1> <{o}> .
]]
```

SPARQL
``` sparql
SELECT * WHERE {
?s <http://ex.org/p1> <http://ex.org/A> 
 OPTIONAL { ?s <http://ex.org/p1> ?o1 . 
            ?o1 <http://ex.org/p1> ?o2
          }
 }
```

SQL
``` sql
SELECT V5.`o1m10` AS `o1m10`,
       V5.`o1m5` AS `o1m5`,
       V5.`s1m1` AS `s1m1`
FROM
  (SELECT DISTINCT V3.`o` AS `o1m10`,
                   V2.`o` AS `o1m5`,
                   V1.`s` AS `s1m1`,
                   CASE
                       WHEN V2.`o` IS NOT NULL THEN V1.`s`
                       ELSE NULL
                   END AS `s1m4`
   FROM `p1` V1
   LEFT OUTER JOIN `p1` V2
   JOIN `p1` V3 ON V2.`o` = V3.`s` ON V1.`s` = V2.`s`
   WHERE 'http://ex.org/A' = V1.`o` ) V5
```
I'm not sure if the left join is correct here. From my understanding, the inner join which is the right side of the left-join should be in brackets and also get an alias which is used for the last ON condition. Like

``` sql
FROM `p1` V1
LEFT OUTER JOIN (`p1` V2
   JOIN `p1` V3 ON V2.`o` = V3.`s`) V4 ON V1.`s` = V4.`s`
```

Am I missing something? Can you reproduce this? Or did I misuse Ontop? I used latest Ontop release version 4.0.3

Cheers,
Lorenz

**Comment by kontchakov** [comment]
Hi Lorenz

Looking at the grammar (https://dev.mysql.com/doc/refman/8.0/en/join.html), the right-hand side argument of a LEFT JOIN is a table_reference, which means that the "brackets" are placed exactly as you suggest anyway. As for the alias, it is a bit unclear to me what V4.`s` would refer to - is it V2.`s` or V3.`s`?

Roman

**Comment by bcogrel** [comment]
Hi Lorenz,

I confirm what Roman has said. 

There is no ambiguity in how to parse the first SQL query. The last ON condition has to refer to the left join, otherwise the SQL query would have been rejected by the DB engine.

Best,
Benjamin

**Comment by LorenzBuehmann** [comment]
Hi guys,

thank's for the quick response and yep - sorry for confusion. I'm sure you're right and we can close this issue. 

It's more like a limitation of the Apache Spark SQL parser then, which isn't able to parse
``` sql
A join B join C on () on ()
```
and complaining about the second `on`. Not sure about the standard SQL 92 syntax where they use brackets (see the [BNF](https://ronsavage.github.io/SQL/sql-92.bnf.html#joined%20table)), but I'll try their ANSI SQL mode and I'll also ask the Spark devs if there is a chance to make their parser more smart.

In the meantime, I extended the `SelectFromWhereSerializer` and added those brackets, so I'm fine with it.

Thank's for clarification.

**Comment by kontchakov** [comment]
Hi Lorenz

Looking at the SQL grammar you mention, the brackets around qualified_joins are **optional** (a joined_table can be a qualified_join or a joined_table in brackets). On the other hand, your original suggestion contained a derived_table followed by a correlation_specification, where the derived_table was a subquery in the form of a joined_table. Still, the problem in your particular example is the ambiguity of the column names in the joined_table subquery (the two joined tables are identical, and one would need to use the derived_column_list to give the columns unambiguous names).

Best
Roman

**Comment by LorenzBuehmann** [comment]
Yep, looks like [Spark SQL JOIN syntax](https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-join.html) follows [Hive syntax](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Joins) both of which aren't smart enough at parsing.

Good thing, it was rather easy to extend the serializer and plug in via injection.

So, thank's again for helping me out and good job.
