### ISSUE TITLE
Dose ontop can merge other rules engine like drools?

### ISSUE THREAD

**Issue by nicholaslsq** [ontop/ontop#382]
Ontop has its own rules engine, so is there possible for merging in other rules engine and how it works?

**Comment by ghxiao** [comment]
Hi @nicholaslsq ,

Merging in other rule engines in Ontop is not a trivial task.

The fundamental reason is the kind of rules internally in Ontop is quite different than other systems like drools.
More technically, Ontop is a writing-based system. The "rewriting rules" in Ontop are backward, but the rules in drools are forward. 

I hope this answers your question. If you need more info, feel free to contact us.
