### ISSUE TITLE
extending Ontop that allows formulating SPARQL queries over an Apache Spark cluster

### ISSUE THREAD

**Issue by tangyong** [ontop/ontop#383]
seeing https://openreview.net/pdf?id=AEfW7G7pP8I

![image](https://user-images.githubusercontent.com/187414/103870265-691b9100-5106-11eb-94f6-d912856604fd.png)

https://github.com/chimera-suite/OntopSpark

Ontop has any plan to add such capability into roadmap?

Thanks!

**Comment by ghxiao** [comment]
Hi,

Thanks for the pointer.

We are also aware of another effort in the [SANSA](https://github.com/SANSA-Stack/SANSA-Stack) project connecting Ontop with Spark.

To answer your question, YES, adding Spark support in Ontop is on our agenda. We will see the best way to proceed on the technical side by asking the community as well.

If you have specific questions, you can also contact me directly via email.

Cheers,

Guohui

**Comment by tangyong** [comment]
Thanks @ghxiao ! Sure, we are also evaluating SANSA Stack project  and  SANSA 0.7.1 has added Ontop connection ,  just as SPARQL Queries over Distributed RDF Datasets, SANSA Stack currently uses Sparklify[1][2] as execution engine -  a scalable software component for efficient evaluation of SPARQL queries over distributed RDF datasets has been proposed, and it rewrites SPARQL to SQL  for translating SPARQL queries into Spark executable code. 
[1] Sparklify: A Scalable Software Component for Efficient Evaluation of SPARQL Queries over Distributed RDF Datasets
[2] https://github.com/SmartDataAnalytics/Sparqlify

![image](https://user-images.githubusercontent.com/187414/103983859-fd4a2e80-51c0-11eb-822d-029a1ceab6a6.png)

I think that the core part of the above architecture is Data Partition, because it plays a critical role on making distributed SPARQL Queries scalable while facing massive rdf datasets.

**Comment by LorenzBuehmann** [comment]
Just as a short note on your discussion, there is Ontop support in SANSA - maybe not perfect right now (I'm still busy with project proposals), but the integration isn't that simple to be fair. Getting the final SPARQL result into the driver is simple, but keeping it on RDD/DataFrame level is not.

We're also working on the partitioning, especially, we already have code for (inverse) wide property tables, but this isn't aligned with the Ontop integration. So far, this is based on vertical partitioning only, but my colleague Claus and me will generalize the partitioning stuff next week. So in the end we will have the common partitioning strategies integrated, but making query engines make use of those is still a TODO.

@tangyong I didn't get the idea of your last slide/screenshot. Partitioning by subject would lead to millions of tables. Or what is the notation of a partition here in the Spark context then? My colleague Claus also has this entity centric view implemented, leading to a mapping of entity to graph containing all triples related to the entity. But this is on RDD level and there is no query engine on top (yet). I'll ping him for some comments, though I'm still not convince this will scale as partitioning. Our idea will go with the well-known characteristic sets approach - this is more or less some kind of clustering by common proeprties, so we will have multiple wide property tables reducing the `NULL` values. By the way, `NULL` values aren't that bad if we serialize the tables into Parquet format. 

If anybody is interested in collaboration and/or has ideas/feature requests etc. - just ping me or somebody else from the SANSA team.

Cheers

**Comment by tangyong** [comment]
Thanks detailed reply ! @LorenzBuehmann and you come from  the SANSA team?

>@tangyong I didn't get the idea of your last slide/screenshot. Do you have any reference to this slide or is it from you?
From the Gezim Sejdiu Slide Page 22:

![image](https://user-images.githubusercontent.com/187414/104142153-3ff44c80-53f5-11eb-9878-c88a6196c30d.png)

Slide: https://www.slideshare.net/GezimSejdiu/efficient-distributed-inmemory-processing-of-rdf-datasets-phd-viva

if having other questions, I will ping you.

Thanks!
