### ISSUE TITLE
Supporting Virtual Ontology-Based Access to Heterogeneous and Large Data Sources

### ISSUE THREAD

**Issue by tangyong** [ontop/ontop#384]
Hi, currently, ontop has supported Virtual Ontology-Based Access to Heterogeneous and Large Data Sources not only relational DB?

SANSA has integrated Squerall[1][2] into STACK for accessing semantic datalake and is still based on Spark.

[1] Squerall: Virtual Ontology-Based Access to Heterogeneous and Large Data Sources
[2] https://github.com/EIS-Bonn/Squerall

Thanks

**Comment by bcogrel** [comment]
Hi, you can use Ontop with Dremio (see https://docs.dremio.com/data-sources/ for the data sources it supports). Support for Dremio will come with 4.1 and is already available on Docker as a snapshot version.

Best,
Benjamin

**Comment by tangyong** [comment]
Thanks @bcogrel ! Good news!

In addition, I want to  make clear that this issue is different from #383 , want to listen teams's suggestion.

**Comment by tangyong** [comment]
@bcogrel has any doc/material about how to use Ontop with Dremio?

**Comment by bcogrel** [comment]
Hi, we are having a small tutorial which was done for Ontop 3.0: https://ontop-vkg.org/tutorial/federation/dremio/ . 
We will have to re-test it for the next release.

**Comment by tangyong** [comment]
> Hi, we are having a small tutorial which was done for Ontop 3.0: https://ontop-vkg.org/tutorial/federation/dremio/ .
> We will have to re-test it for the next release.

Thanks !

**Comment by Muffexx** [comment]
> Hi, you can use Ontop with Dremio (see https://docs.dremio.com/data-sources/ for the data sources it supports). Support for Dremio will come with 4.1 and is already available on Docker as a snapshot version.
> 
> Best,
> Benjamin

Hi Benjamin,

i built the current release (4.1.0-beta-1-SNAPSHOT) and tried using the exisiting files from our current instance (v3.0.1) but ontop won't start. Do these files have to altered? With the current instance we can use our Dremio spaces.

> Error creating bean with name 'predefinedQueryController' defined in URL [jar:file:/home/fpdatalake/ontop_4.1.0/lib/ontop-endpoint-4.1.0-beta-1-SNAPSHOT.jar!/it/unibz/inf/ontop/endpoint/controllers/PredefinedQueryController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'setupPredefinedQueryEngine' defined in class path resource [it/unibz/inf/ontop/endpoint/beans/PredefinedQueryComponent.class]: Unsatisfied dependency expressed through method 'setupPredefinedQueryEngine' parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'setupVirtualRepository' defined in class path resource [it/unibz/inf/ontop/endpoint/beans/OntopVirtualRepositoryBean.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository]: Factory method 'setupVirtualRepository' threw exception; nested exception is org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: Error: Cannot find relation id: "connections_blogs_weblogentry" "connections_blogs_weblogentry"
Problem location: source query of triplesMap

**Comment by Muffexx** [comment]
The issue was resolved using the current beta-version. The issue was related to the default schema of Dremio in the properties file.

**Comment by bcogrel** [comment]
With the release 4.1.0, Ontop supports Dremio again. We also updated the tutorial, please give a try: https://ontop-vkg.org/tutorial/federation/dremio/ .

I am closing the issue for now.
