### ISSUE TITLE
Problems running ontop container in AWS as ECS task

### ISSUE THREAD

**Issue by kleegrewec** [ontop/ontop#385]
Hi all,
I wanted to launch an ontop docker container as an ECS task in AWS but the creation of the tasks fails with an exception. The scenario I use for testing is the university-complete1 scenario which comes with the tutorials. The setup is the following

- I create an ec2 instance containing the h2 database 
- I create an ecs service containing the task (task definition is attached to this ticket)
- The ecs task is launched but terminates with an exception after some seconds.

image is from: ontop/ontop-endpoint:latest -- which I needed to move to my on ECR repository

Checking the connection from my container to the h2 database with nmap shows that the oprt and address are avaible
Also connecting from a test server to the h2 database using sqlline works.

Any idea what is going wrong and how to solve the issue is welcome.

thanks Christian

Attachment 1) contains the contents of the input and jdbc folders which are mounted into the container
[university-complete.zip](https://github.com/ontop/ontop/files/5822103/university-complete.zip)
Attachment 2) contains the log output of the failing task
[log-events-ontop-university-complete.log.txt](https://github.com/ontop/ontop/files/5822019/log-events-ontop-university-complete.log.txt)
Attachment 3) contains the ECS task description of the ontop endpoint
[ontop-ecs-task-definition.json.txt](https://github.com/ontop/ontop/files/5822023/ontop-ecs-task-definition.json.txt)

**Comment by kontchakov** [comment]
Hi Christian

"IO Exception: null [90028-196]" looks like an H2 error message indicating a corrupt database. I wonder if it is caused by the *relative* path in the connection URL (jdbc.url=jdbc\:h2\:tcp\://10.141.1.231:9092/../university-session1).

Best
Roman

**Comment by kleegrewec** [comment]
Hi Roman,

thanks for your response. This helped me to solve the problem. Finally it was a bug in the database URL generation and a missing baseDir assignment in h2. So everyting i working fine now and I will close this ticket.

best, Christian
