### ISSUE TITLE
GeoSPARQL support

### ISSUE THREAD

**Issue by DougalW** [ontop/ontop#389]
Hi

Is there any plan to add support for GeoSPARQL into the main Ontop branch? There is a version available from https://github.com/ConstantB/ontop-spatial but it's using a much older version of Ontop, and it would be very useful to have this functionality folded into the main Ontop codebase.

**Comment by akuckartz** [comment]
See #335 !

**Comment by DougalW** [comment]
Thanks for that - I searched open issues so missed that it was closed.
