### ISSUE TITLE
"Test SQL query" in Protege Plugin may run out of memory

### ISSUE THREAD

**Issue by marianormuro** [ontop/ontop#4]
"Test SQL query" in the Protege plugin brings ALL the tuples from the query and potentially will crash Protege due to out of memory issues.

**Comment by ghxiao** [comment]
Hi @marianormuro , this is an old issue but I guess it is still valid. 
This issue reminds me that MySQL Workbench is alway appending a `LIMIT 1000` to the SQL query.
Probably we can follow the same idea.

**Comment by bcogrel** [comment]
Still a valid issue indeed, since it encourages users to add a LIMIT in the source query, which is a bad practice (force the creation of a black-box view, does make sense in terms of semantics).

**Comment by skomlaebri** [comment]
Fixed using setMaxRows in aab62d224ebe8a7757661bff8bbe3ece4c02473e , most databases implemented it limiting the result set at the SQL level.
