### ISSUE TITLE
Does Ontop support None-RDBMS?

### ISSUE THREAD

**Issue by xuchen-tech** [ontop/ontop#403]
Does Ontop support None-RDBMS? or has plan to support none-RDBMS?such as: redis, Cassandra, MongoDB, Neo4J, InfluxDB

**Comment by bcogrel** [comment]
Hi,

Ontop indirectly supports several of them through a database federator like Dremio (with 4.1.0) and Denodo:

See https://docs.dremio.com/data-sources/ and https://community.denodo.com/docs/html/browse/8.0/en/vdp/administration/creating_data_sources_and_base_views/jdbc_sources/jdbc_sources .

Best,
Benjamin

**Comment by xuchen-tech** [comment]
Thanks for that
