### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by KonradHoeffner** [ontop/ontop#409]
### Description

Java 15 warns that Ontop will stop working in a future Java release:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/konrad/opt/ontop/lib/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### Steps to Reproduce
```
ontop materialize \
 -m scripts/export/citation.r2rml.ttl \
 -o export.ontop.ttl \
 -f turtle \
 -p scripts/export/hito.properties
```

**Expected behavior:**
no warning

**Actual behavior:** 
the warning above

**Reproduces how often:**
every time

### Attached material
I don't think the files are relevant here as the problem seems to related to the code and the JVM version but if you want I can provide the files.

### Versions

Ontop 4.0.3 CLI.
openjdk 15.0.2 2021-01-19

**Comment by bcogrel** [comment]
Hi Konrad,

Thanks for reporting this issue. We are aware of it. 

We will need to investigate how to update our Guice dependency. However, at the moment, we don't have a lot of flexibility, due to our dependency on Protégé.

For 4.0.3, the recommended version is Java 8. Starting from 4.1.0, both Java 8 and Java 11 are supported by Ontop (outside of Protégé).

**Comment by ghxiao** [comment]
Hi @KonradHoeffner  @bcogrel,

If it is only about Guice, we might be able to solve this issue by shading the guice dependency, so as to use a different guice version from Protege.

**Comment by KonradHoeffner** [comment]
@ghxiao: Unfortunately I cannot say if the problem is caused by Guice only as I am not a developer, I just downloaded and executed the ontop release.

**Comment by KonradHoeffner** [comment]
This issue seems to be solved now.
I don't get any warning with ontop 4.2.0 using openjdk 18.0.1 2022-04-19.
