### ISSUE TITLE
BSBM query is failing in Ontop on MS SQL

### ISSUE THREAD

**Issue by mchaloupka** [ontop/ontop#412]
### Description

The following query (from BSBM) is failing with Ontop:
```
PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?product ?label
WHERE {
    ?product rdfs:label ?label .
    ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType6> .
        ?product bsbm:productFeature <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature205> .
        ?product bsbm:productPropertyNumeric1 ?p1 .
        FILTER ( ?p1 > 72 )
        ?product bsbm:productPropertyNumeric3 ?p3 .
        FILTER (?p3 < 455 )
    OPTIONAL {
        ?product bsbm:productFeature <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature197> .
        ?product rdfs:label ?testVar }
    FILTER (!bound(?testVar))
}
ORDER BY ?label
LIMIT 10
```

I get the following error:
```
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: com.microsoft.sqlserver.jdbc.SQLServerException: The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.
```

### Steps to Reproduce

1. Prepare environment for BSBM. 
   1. Checkout https://github.com/mchaloupka/r2rml-benchmark
   2. In the folder with the checked out repository, start .NET F# interactive using `dotnet fsi` (requires .NET 5 SDK)
   3. Use the following command:
```
#load "benchmark.fsx"
open Database
open Docker
open Endpoints
Benchmark.createAndClearWorkingDirectories ()
Benchmark.generateData 20
createNetwork benchmarkNetwork
startDatabaseContainer Databases.MsSql
ontopEndpoint.Start Databases.MsSql
;;
```
2. Visit `http://localhost:5051/` to access Ontop UI and try the above mentioned query.
3. To cleanup, you can write the following command in the .NET interactive console
```
stopAndRemoveContainer ontopEndpoint.DockerName
stopAndRemoveContainer databaseDockerName
removeNetwork benchmarkNetwork
;;
```
4. To close the interactive session, just write: `#quit;;`

**Expected behavior:** The query processed

**Actual behavior:** The query fails with 500

**Reproduces how often:** Every time

### Attached material

All materials are part of the linked repository

### Versions

Docker Ontop (using `:latest` tag), downloaded version: `4.1.0`

### Additional Information

Please let me know if you encounter any issues with reproducing the issue.

**Comment by apano-on** [comment]
Hi @mchaloupka,

Thanks a lot for reporting this issue.

It is an issue with our SQL translation of ORDER BY and LIMIT in sql server.

We are looking into fixing it.

**Comment by mchaloupka** [comment]
Hi, do you have some ETA for the fix? Or do you recommend me to use some older version of Ontop? Do you know in which version it broke (it used to work before).

**Comment by apano-on** [comment]
Hi @mchaloupka,

We have applied a bugfix and towards the end of the month we will be releasing Ontop v4.1.1 which will have the official update.

However, we have also added the fix to the Docker image for [Ontop v4.1](https://hub.docker.com/layers/ontop/ontop-endpoint/4.1/images/sha256-bfaa9d52ab799f8912562a383b73ebc329a31ac88b590338c4b6e39309073ac6?context=explore) with the bugfix. Please change your tag "ontop/ontop-endpoint" -> "ontop/ontop-endpoint:4.1".

Please give a try to this docker image instead of the one with tag latest and let us know in case there are still any issues. We will notify you when the bugfix has been applied to the latest version.

**Comment by mchaloupka** [comment]
Hi,

I have tried the docker image `ontop/ontop-endpoint:4.1` and it does not seem to be fixed.

You can verify it using the original steps. Just do a minor change to the following file:
https://github.com/mchaloupka/r2rml-benchmark/blob/master/endpoints.fsx#L60
Change it to: `let imageName = "ontop/ontop-endpoint:4.1"`

Can you verify that the fix is in place? I have tried it and it seems to have the exact same failure as before.

**Comment by apano-on** [comment]
Hi,

Yes, you are correct there was still a small bug which we just fixed and we tested your setup with:
`let imageName = "ontop/ontop-endpoint:4.1"`
and the query should yield the expected results. 

Thanks again for the quick feedback and let us know in case of any other issues. Once Ontop v4.1.1 is released we will let you know in this thread.

**Comment by mchaloupka** [comment]
Thanks,
it seems that now it is resolved using the above mentioned image.
