### ISSUE TITLE
Does Ontop support INSERT and DELETE operator to manage bottom data with it's own mapping?

### ISSUE THREAD

**Issue by nicholaslsq** [ontop/ontop#415]

**Comment by bcogrel** [comment]
Hi @nicholaslsq , 

No, as of now, it does not support these operators. It is a read-only system.

Best,
Benjamin

**Comment by nicholaslsq** [comment]
Thanks for your reply.By the way, is there any OBDA system implements these operations? Will ontop support them？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ontop/ontop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ontop/ontop] Does Ontop support INSERT and DELETE operator to manage bottom data with it's own mapping? (#415)





 
Hi @nicholaslsq ,
 
No, as of now, it does not support these operators. It is a read-only system.
 
Best,
 Benjamin

**Comment by ghxiao** [comment]
Hi @nicholaslsq ,

We do want to support them, but we don't have a concrete plan yet. It is a challenging task also from a theoretical point of view.

**Comment by nicholaslsq** [comment]
Thanks, hope your working group solve this point soon. Good luck.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ontop/ontop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ontop/ontop] Does Ontop support INSERT and DELETE operator to manage bottom data with it's own mapping? (#415)





 
Hi @nicholaslsq ,
 
We do want to support them, but we don't have a concrete plan yet. It is a challenging task also from a theoretical point of view.
