### ISSUE TITLE
Option to disable URL encoding?

### ISSUE THREAD

**Issue by KonradHoeffner** [ontop/ontop#427]
In my SPARQL endpoint, different encodings for the same URIs are treated like different URIs.
For example, `https://dbpedia.org/resource/Java_%28programming_language%29` and `https://dbpedia.org/resource/Java_(programming_language)` are separate and triples for one of them aren't shown when querying for the other.
Another example is `https://dbpedia.org/resource/C%2B%2B` and `https://dbpedia.org/resource/C++`.

Also, my RDF Turtle files don't cause problems when the URIs contain characters like "(" or "+".

So I would like to disable the URI encoding for Ontop, is that possible?

**Comment by bcogrel** [comment]
Hi Konrad,

Ontop is not proposing such a global option anymore, which I personally always found problematic.

There is a way to achieve what you want while remaining compliant with R2RML (and our Ontop native syntax): you simply build the IRI at the SQL query level. R2RML does not apply IRI safe encoding to column-valued term map. It applies it only to IRI templates (https://www.w3.org/TR/r2rml/#dfn-iri-safe), which in my view should be avoided in your case.

While it may not look very user-friendly at first glance, this design of R2RML makes perfect sense to me, as I think the IRI safe encoding should be applied by default to IRIs. It brings essential properties to IRI templates: it can make them injective when they have multiple arguments (i.e. they can decomposed so as to allow performing joins on primary keys) and guarantees that a valid IRI will be generated (even in the presence of spaces in database values).

Best,
Benjamin

**Comment by KonradHoeffner** [comment]
Hi Benjamin,

Thank you for the detailed explanation! I removed all special characters from my own URIs to circumvent this problem, however it still occurs with references to external URIs like the DBpedia examples given. I will try to rewrite my templates to column-valued term maps.

I still prefer if it was not URI encoded in the IRI templates but I guess my use case is different from others.

I found a statement in https://www.w3.org/TR/turtle/ about why this problem occurs:

> %-encoded sequences are in the character range for IRIs and are explicitly allowed in local names. These appear as a '%' followed by two hex characters and represent that same sequence of three characters. These sequences are not decoded during processing. A term written as <http://a.example/%66oo-bar> in Turtle designates the IRI http://a.example/%66oo-bar and not IRI http://a.example/foo-bar. A term written as ex:%66oo-bar with a prefix @prefix ex: <http://a.example/> also designates the IRI http://a.example/%66oo-bar.
