### ISSUE TITLE
Possible Mixing Text and Geometry when rewriting GeoSPARQL functions

### ISSUE THREAD

**Issue by ghxiao** [ontop/ontop#428]
### Description

Ontop may generate illegal SQL queries when rewriting GeoSPARQL functions. 

### Steps to Reproduce

The following SPARQL query fails on <https://sparql.opendatahub.bz.it/>
```sparql
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX : <http://noi.example.org/ontology/odh#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT ?x ?wkt ?wktColor ?wktLabel {
    ?m a :Municipality .  ?m rdfs:label ?mWktLabel . 
    ?m geo:defaultGeometry/geo:asWKT ?mWkt .
  	FILTER(?mWktLabel = 'Bolzano'@it)
    BIND(geof:buffer(?mWkt, 1000, uom:metre) AS ?bWkt) 
    BIND('red' AS ?wktColor)    
    ?s a :MeteoStation . ?s geo:defaultGeometry/geo:asWKT ?wkt .
#    #spatial join
    FILTER(geof:sfIntersects(?wkt, ?bWkt))
}
```

Error:

```
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: org.postgresql.util.PSQLException: ERROR: function st_intersects(geometry, text) is not unique
  Hint: Could not choose a best candidate function. You might need to add explicit type casts.
  Position: 109
```

Expected SQL:

```sql
SELECT ST_ASTEXT(v2."pointprojection") AS "v0"
    FROM "odp_municipalities" v1, "intimev2"."station" v2
    WHERE (ST_INTERSECTS(v2."pointprojection",
        ST_BUFFER(CAST(v1."geom_4326" AS GEOGRAPHY),1000)) 
               AND v1."geom_4326" IS NOT NULL AND v2."pointprojection" IS NOT NULL 
               AND v1."istat_code" IS NOT NULL AND 'Bolzano' = v1."name_i" AND 'MeteoStation' = v2."stationtype");
```

Generated SQL:

```sql
SELECT ST_ASTEXT(v2."pointprojection") AS "v0"
        FROM "odp_municipalities" v1, "intimev2"."station" v2
         WHERE (ST_INTERSECTS(v2."pointprojection", CAST(ST_ASTEXT(ST_BUFFER(CAST(ST_ASTEXT(v1."geom_4326") AS GEOGRAPHY),'1000')) AS TEXT)) 
         AND v1."geom_4326" IS NOT NULL AND v2."pointprojection" IS NOT NULL AND v1."istat_code" IS NOT NULL 
         AND 'Bolzano' = v1."name_i" AND 'MeteoStation' = v2."stationtype")
```

This cast in `CAST(ST_ASTEXT(ST_BUFFER(CAST(ST_ASTEXT(v1."geom_4326") AS GEOGRAPHY),'1000')) AS TEXT)` is causing the problem because the first argument of ST_INTERSECTS is geometry and this one is text. PostGIS complains.

**Reproduces how often:** 

Always

### Versions

Ontop 4.1.0 and the latest branch `releasing/v4.1`

### Additional Information

We can use the code from https://github.com/ontopic-vkg/odh-vkg to reproduce the problem locally. However, we should also create a minimal example to replicate this issue in the codebase.

**Comment by kokfoongcmcl** [comment]
Hello, I believe this issue is still present in v4.2.1, I'm using geof:ehCovers and got the following exception
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: org.postgresql.util.PSQLException: ERROR: function st_covers(text, geometry) is not unique
  Hint: Could not choose a best candidate function. You might need to add explicit type casts.
  Position: 1337
