### ISSUE TITLE
Ontop refuses to generate valid SQL queries involving UNION of computed columns with different text types (TEXT, VARCHAR, CHAR)

### ISSUE THREAD

**Issue by fracorco** [ontop/ontop#438]
### Description

When using Ontop over MySQL (tested version: 5.7) and processing SPARQL queries whose translation involves the SQL UNION of computed columns with different text types (TEXT, VARCHAR, CHAR), Ontop reports an exception like:
```
 NonUniqueTermTypeException: Multiple term types found for cover0m1: [VARCHAR, TEXT]
```
while translating the SPARQL. See attached file `stacktrace.txt` for more info.

### Steps to Reproduce

I'm attaching file `docker-compose-example.tar.gz` minimal example based on Docker Compose, including a minimal MySQL database, mapping and ontology.

If you have Docker and Docker Compose installed, you just have to uncompress file `tar.gz` into some folder and run `docker-compose up` to start MySQL and Ontop. Then open Ontop Web UI and test this SPARQL query to reproduce the error:
```
PREFIX : <http://example.com/ontology#>
SELECT DISTINCT ?s WHERE { ?s a :Image } 
```
You may also test the issue without Docker Compose, by opening the `tar.gz` and manually setting up a MySQL DB with the SQL script under folder /sql. Then manually setup an Ontop endpoint using the ontology and mappings under folder /vkg.

**Expected behavior:** SPARQL to SQL translation succeeds as the involvement of different SQL text types in the generated SQL UNION is not an issue for MySQL.

**Actual behavior:** NonUniqueTermTypeException

**Reproduces how often:** always

### Attached material

File `docker-compose-example.tar.gz` (see links at the end) includes a minimal Docker Compose application that allows reproducing the issue.
File `stacktrace.txt` includes the root exception reported by Ontop (chain of wrapping exceptions omitted).

### Versions

Ontop endpoint 4.1

### Additional Information

Here are the relevant bits from `docker-compose-example.tar.gz` and some additional comment. Ontology:
```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix : <http://example.com/ontology#> .

:Image a owl:Class .

:image a owl:ObjectProperty ;
    rdfs:range :Image .
```

Mappings:
```
[PrefixDeclaration]
:    http://example.com/ontology#

[MappingDeclaration] @collection [[
mappingId  mytable_cover
target     <{url}> a :Image .
source     SELECT CONCAT('file:', cover) AS url
              FROM mytable WHERE cover IS NOT NULL

mappingId  mytable_coveren
target     <{url}> a :Image .
source     SELECT CONCAT('file:', coveren) AS url
           FROM mytable WHERE coveren IS NOT NULL
]]
```
The error with the aforementioned SPARQL query is strictly related to the presence in the mappings of expressions like
```
SELECT ... CONCAT('file:', cover) AS URL ... FROM ...
```
because if I drop the CONCAT then Ontop stops complaining and tries executing the resulting SQL query.

A simple workaround is to force a common SQL type by rewriting mappings using CAST (... AS CHAR) expressions as follows (see file `vkg/vkg.obda.good` in the `tar.gz`):
```
[PrefixDeclaration]
:    http://example.com/ontology#

[MappingDeclaration] @collection [[
mappingId  mytable_cover
target     <{url}> a :Image .
source     SELECT CONCAT('file:', CAST(cover AS CHAR)) AS url
           FROM mytable WHERE cover IS NOT NULL

mappingId  mytable_coveren
target     <{url}> a :Image .
source     SELECT CONCAT('file:', CAST(coveren AS CHAR)) AS url
           FROM mytable WHERE coveren IS NOT NULL
]]
```
With this workaround Ontop generates this SQL query:
```
SELECT DISTINCT v5.`v0` AS `v0`
FROM (
  SELECT CAST(v1.`cover` AS CHAR) AS `v0`
  FROM   `mytable` v1
  WHERE  v1.`cover` IS NOT NULL
UNION ALL
  SELECT CAST(v3.`coveren` AS CHAR) AS `v0`
  FROM   `mytable` v3
  WHERE  v3.`coveren` IS NOT NULL
) v5
```
However, please note that the CAST in the SQL are not necessary in MySQL and indeed the SQL query without CASTs works perfectly fine:
```
SELECT DISTINCT v5.`v0` AS `v0`
FROM (
  SELECT v1.`cover` AS `v0`
  FROM   `mytable` v1
  WHERE  v1.`cover` IS NOT NULL
UNION ALL
  SELECT v3.`coveren` AS `v0`
  FROM   `mytable` v3
  WHERE  v3.`coveren` IS NOT NULL
) v5;
```

Note that this issue was first encountered while trying to materialize all the triples based on mappings, and the aforementioned problematic query is indeed representative of the kind of queries generated by Ontop during materialization.

[docker-compose-example.tar.gz](https://github.com/ontop/ontop/files/6598290/docker-compose-example.tar.gz)
[stacktrace.txt](https://github.com/ontop/ontop/files/6598293/stacktrace.txt)

**Comment by bcogrel** [comment]
Hi @fracorco , thanks a lot for this detailed report!

It provides a good example of when the unique type assumption is too strong, even for a "strongly-typed" system. I have adapted your test to H2 and added to the code base.

I have relaxed the type extractor and renamed it. This exception was actually useful during the early development of Ontop 4.0 for detecting missing casts, but it is not needed anymore.

There were already an issue on this topic in our internal development bug tracker (https://gitlab.inf.unibz.it/ontop/ontop-issues/-/issues/88).

Best,
Benjamin
