### ISSUE TITLE
java.lang.NullPointerException: null when starting Ontop Reasoner

### ISSUE THREAD

**Issue by grobmo** [ontop/ontop#439]
When I startup Ontop Reasoner it throws the following error;

DEBUG  19:27:14  Firing event ABOUT_TO_CLASSIFY
  DEBUG  19:27:14  Firing model manager event: OWLModelManagerChangeEvent{org.protege.editor.owl.model.OWLModelManagerImpl@260ce275, ABOUT_TO_CLASSIFY}
  DEBUG  19:27:14  ABOUT_TO_CLASSIFY
   INFO  19:27:14  ------------------------------- Running Reasoner -------------------------------
   INFO  19:27:14  
  ERROR  19:27:14  An error occurred during reasoning: null.
java.lang.NullPointerException: null
	at it.unibz.inf.ontop.protege.core.OntopReasonerInfo.getConfiguration(OntopReasonerInfo.java:50) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:17) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
  DEBUG  19:27:14  Firing event ONTOLOGY_CLASSIFIED
  DEBUG  19:27:14  Firing model manager event: OWLModelManagerChangeEvent{org.protege.editor.owl.model.OWLModelManagerImpl@260ce275, ONTOLOGY_CLASSIFIED}
  DEBUG  19:27:14  ONTOLOGY_CLASSIFIED
  DEBUG  19:27:14  --- Verifying selection ---
  DEBUG  19:27:14  Last selected class: null
  DEBUG  19:27:14  Last selected object property: null
  DEBUG  19:27:14  Last selected data property: null
  DEBUG  19:27:14  Last selected annotation property: null
  DEBUG  19:27:14  Last selected individual: null
  DEBUG  19:27:14  Last selected datatype: null
  DEBUG  19:27:14  Last selected entity: null
  DEBUG  19:27:14  ---------------------------

Other Reasoner run without any problems, but now I want to map a database and i want to use ontop. I did now map anything and I don't know where to start searching.

**Comment by kontchakov** [comment]
Could you provide more details? Ontop version, OWL and OBDA files are a start.

**Comment by ghxiao** [comment]
Could you try to reset the preferences? This might help.

See e.g., https://groups.google.com/g/ontop4obda/c/XOmzlPqjVl8/m/VLglbde8BAAJ

**Comment by grobmo** [comment]
Hello,
because there is no current mapping I haven't got a OBDA File. My Ontop Version is 4.1. But resetting the preferences did the job, thanks.
But why? Where was the error in my preferences?

**Comment by ghxiao** [comment]
@grobmo This is a known issue inherited from Protege. You did nothing wrong.

Further explanation: https://groups.google.com/g/ontop4obda/c/XOmzlPqjVl8/m/kqD3qAHTAwAJ
