### ISSUE TITLE
Set default query in ontop endpoint via portal file

### ISSUE THREAD

**Issue by apano-on** [ontop/ontop#454]
### Description

The default query in the ontop endpoint is currently the yasgui default.
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  ?sub ?pred ?obj .
} 
LIMIT 10
```
Request: I would like to be able to set a customized default query via the toml PORTAL_FILE.

### Steps to Reproduce

1. Add a section in the portal file responsible for the default query e.g.
```
[defaultTab]
query = "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT * WHERE {
  ?sub ?pred ?obj .
} 
ORDER BY ?sub
LIMIT 100"
```
2. Modify the default Yasqe query via ```YASGUI.YASQE.defaults.value```

### Versions

Ontop v4.1.1

### Additional Information

See https://github.com/ontop/ontop/commit/7ccb20b109a9a48e2e83bef8d1393dc7acf5e34c for an example which adopts the [defaultTab] style provided above to do so (though any style of choice can be used). It can be tested on any ontology.

**Comment by ghxiao** [comment]
Feature merged.

For documentation, one can add such a section in the portal toml file now as in https://github.com/GeoKnow/LinkedGeoData/blob/develop/linkedgeodata-docker/lgd-ontop-web/lgd.portal.toml:

```toml
[defaultTab]
query="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX geom: <http://geovocab.org/geometry#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX lgd: <http://linkedgeodata.org/triplify/>
PREFIX lgdo: <http://linkedgeodata.org/ontology/>
PREFIX lgdm: <http://linkedgeodata.org/meta/>
PREFIX lgd-geom: <http://linkedgeodata.org/geometry/>

SELECT * WHERE {
#DESCRIBE ?x ?g WHERE {
    ?x a lgdo:Bar ;
        geo:hasGeometry ?g;
        rdfs:label ?wktLabel .
    ?g geo:asWKT ?wkt ;    
    FILTER(lang(?wktLabel) = "" || lang(?wktLabel) = "en")
} 
LIMIT 1
"""
```
