### ISSUE TITLE
Invalid CASE statements in WHERE clause

### ISSUE THREAD

**Issue by chrdebru** [ontop/ontop#457]
Ontop generated CASE statements in WHERE clauses that are invalid; the ELSE clause contains an expression and not a value.

A part of the query that was generated looked as follows:

```
SELECT (...) AS "v1m16" FROM   "footable" v5
WHERE
CASE
  WHEN v5."foo" IS NULL THEN true
  ELSE v5."foo" IS NOT NULL
END 
```

Not only is that query not permitted, it does not make sense either. The SQL query that I'm mapping looks as follows:

```
SELECT 
ID,
-- other columns here            
CASE WHEN foo IS NULL THEN CONCAT('CAW-',ID) ELSE foo END AS IRI
FROM footable
```
The case in the SELECT clause is used to create a part of the subject's IRI

I am using ontop-cli-4.1.1. I am also using Denodo.

**Comment by bcogrel** [comment]
Hi @chrdebru , thanks for reporting the issue.

I suspect that Denodo does not accept boolean expressions in the `THEN` or `ELSE` clauses. Oracle and SQL server both have such a restriction, but not PostgreSQL if I remember correctly.

Possible fix:
 - [ ] Override the method [createDBBooleanCase(...)](https://github.com/ontop/ontop/blob/version4/db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/AbstractSQLDBFunctionSymbolFactory.java#L580) for Denodo like it has been done for Oracle.

Best,
Benjamin

**Comment by bcogrel** [comment]
Hi @chrdebru, I commit a possible fix (https://github.com/ontop/ontop/commit/c9c25fc8167a69ac3d4608756744d36d65e09559) in the `version4` branch. Could you please give it a try?

Best,
Benjamin

**Comment by bcogrel** [comment]
I am closing the issue for now, but feel free to re-open it if the issue turns out not being fixed.
