### ISSUE TITLE
Ontop SQL syntax with BigQuery and CAST to TEXT

### ISSUE THREAD

**Issue by pashworth** [ontop/ontop#462]
I've been working with Google BigQuery and trying to connect with ontop.
Whilst I am able to make the JDBC connection Ontop is not liking the sql syntax.

This appears to be backticks but I am not sure why as I use backticks for MySql and it works just fine. 
If someone could look into this and provide a fix to support BigQuery it would be greatly appreciated.

BigQuery accepts a variety of sql syntax which work.
 
Example valid query syntax are shown.
```
1. SELECT gameId FROM `level-array-321409.baseball.schedules` 
2. SELECT gameId FROM `level-array-321409`.`baseball`.`schedules` 
3. SELECT gameId FROM level-array-321409.baseball.schedules 
4. SELECT `gameId` FROM level-array-321409.baseball.schedules 
5. SELECT `gameId` FROM `level-array-321409.baseball.schedules` 
6. SELECT GameId FROM level-array-321409.baseball.schedules 
7. SELECT GameId FROM `level-array-321409.baseball.schedules` 
```

backticks only can be used. The use of 'gameid' or "gameid" is allowed but treated as a literal to return as one might expect.
The last one also shows that column case insensitive is possible for column names however the dataset must be case sensitive throughout.

When specifying these queries as the r2rml:sqlQuery in an r2rml description Ontop converts these to invalid SQL statements.

Ontop gives the following error message
Executing Queries 1,5,7
```
source query: SELECT gameId FROM `level-array-321409.baseball.schedules`]
        at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:115)
        at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:81)
        at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:94)
        at it.unibz.inf.ontop.cli.OntopQuery.run(OntopQuery.java:96)
        at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:20)
Caused by: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: Error: Cannot find relation `level-array-321409.baseball.schedules` (available choices: ["level-array-321409"."baseball"."games_post_wide", "level-array-321409"."baseball"."games_wide", "level-array-321409"."baseball"."schedules"]) `bigquery-public-data.baseball.schedules`
Problem location: source query of triplesMap

```
Executing Query 2
```
source query: SELECT gameId FROM `level-array-321409`.`baseball`.`schedules`]
        at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:115)
        at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:81)
        at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:94)
        at it.unibz.inf.ontop.cli.OntopQuery.run(OntopQuery.java:96)
        at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:20)
Caused by: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: Error: Cannot find relation `level-array-321409`.`baseball`.`schedules` (available choices: ["level-array-321409"."baseball"."games_post_wide", "level-array-321409"."baseball"."games_wide", "level-array-321409"."baseball"."schedules"]) `bigquery-public-data`.`baseball`.`schedules`
Problem location: source query of triplesMap
```

Executing Queries 3,4,6  (list of expecting shortened for brevity)
```
FAILED TO PARSE: SELECT gameId FROM level-array-321409.baseball.schedules net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "-" "-"
    at line 1, column 28.

Was expecting one of:

    ","
    ";"
    "ACTION"
    "ANY"
    "APPLY"
    "AS"
    ..... 

PARSER VIEW FOR SELECT gameId FROM level-array-321409.baseball.schedules
```

Since Ontop does not seem to support the pass through of these sql queries it would appear that I am currently unable use with BigQuery.

As an experiment I tested with a sql query that Ontop would understand and make the JDBC connection and send to execute on BigQuery.
in the r2rml I set 

`r2rml:sqlQuery "SELECT gameId FROM \"level-array-321409\".\"baseball\".\"schedules\"" ;`

This did get to BigQuery 
But gave the exception 

`ERROR in i.u.i.o.a.c.impl.QuestStatement - java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Unexpected string literal "gameId1m0" at [1:11]`

In the JDBC log I could see that the sql sent across was going to error because of the quotes.

```
SELECT v9."gameId1m0" AS "gameId1m0", v9."v0" AS "v0", v9."v1" AS "v1", v9."v2" AS "v2"
FROM (SELECT v3."gameId1m0" AS "gameId1m0", 0 AS "v0", 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' AS "v1", 'http://in4mium.com/masterdatakg/def/bigquery-public-data.baseball/schedules' AS "v2"
FROM (SELECT DISTINCT v1."gameId" AS "gameId1m0"
FROM "level-array-321409"."baseball"."schedules" v1
WHERE v1."gameId" IS NOT NULL
) v3
UNION ALL 
SELECT v7."gameId1m0" AS "gameId1m0", 1 AS "v0", 'http://in4mium.com/masterdatakg/def/bigquery-public-data.baseball/schedules.gameId' AS "v1", CAST(v7."gameId1m0" AS TEXT) AS "v2"
FROM (SELECT DISTINCT v5."gameId" AS "gameId1m0"
FROM "level-array-321409"."baseball"."schedules" v5
WHERE v5."gameId" IS NOT NULL
) v7
) v9
LIMIT 5

```

I did edit this sql query and ran directly in big query to see the triples being created and it worked. After I chnaged the syntax and the cast to string

```
SELECT v9.gameId1m0 AS gameId1m0, v9.v0 AS v0, v9.v1 AS v1, v9.v2 AS v2
FROM (SELECT v3.gameId1m0 AS gameId1m0, 0 AS v0, 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' AS v1, 'http://in4mium.com/masterdatakg/def/bigquery-public-data.baseball/schedules' AS v2
FROM (SELECT DISTINCT v1.gameId AS gameId1m0
FROM `level-array-321409.baseball.schedules` v1
WHERE v1.gameId IS NOT NULL
) v3
UNION ALL 
SELECT v7.gameId1m0 AS gameId1m0, 1 AS v0, 'http://in4mium.com/masterdatakg/def/bigquery-public-data.baseball/schedules.gameId' AS v1, CAST(v7.gameId1m0 AS STRING) AS v2
FROM (SELECT DISTINCT v5.gameId AS gameId1m0
FROM `level-array-321409.baseball.schedules` v5
WHERE v5.gameId IS NOT NULL
) v7
) v9
LIMIT 5

```

**Comment by pashworth** [comment]
Just wondered if anyone is able to think of a quick fix for this. Effectively the syntax is the same as MySql and we just need the Cast to STRING instead of the TEXT. 
Is there an option to the SQL syntax language in the properties? I couldn't see one.

**Comment by kontchakov** [comment]
Hi @pashworth 

`level-array-321409.baseball.schedules` means that the table name is level-array-321409.baseball.schedules - there is no schema or catalog name in this case (and the dots are actually part of the table name). It is not the same as `level-array-321409`.`baseball`.`schedules`, where you have 3 components: level-array-321409, baseball and schedules (which is actually what you did in the R2RML example). In that sense, Queries 1,5,7 are not really an option.

I am not sure why Queries 3,4,6 do not work - will need to see the OBDA file.

The real issue, however, is that Ontop has to work with many database engines, and the default way of quoting identifiers in Ontop is double quotation marks - which is perfectly in line with the SQL standard. MySQL is one notable exception that uses backticks, and Ontop recognises MySQL datasources and treats them in a special way. Since BigQuery is not currently supported by Ontop,  the system defaults to the SQL standard (which does not quite work in this case). In principle, extending Ontop to support BigQuery should not be too much of a problem - a few custom classes need to be implemented. 

Best
Roman

**Comment by pashworth** [comment]
@kontchakov I'd be happy to test out any builds that could get this working for BigQuery. I think there a few people that would love to see this working.
Cheers
Phil

**Comment by JensPiegsa** [comment]
The CAST-to-TEXT syntax also creates issues with `org.mariadb.jdbc.Driver`.

**Comment by mhavey** [comment]
CAST TO TEXT also an issue using Amazon Athena or Presto-based databases.

**Comment by thomasjtaylor** [comment]
May be similar to  #455 Casting to TEXT does not work in Teiid (and Dremio) (and HSQLDB)
