### ISSUE TITLE
Allow multiple columns to be used in ObjectMap template

### ISSUE THREAD

**Issue by pashworth** [ontop/ontop#463]
Could we enable the use of multiple columns in an ObjectMap template.

In  r2rml we can describe columns in ObjectMaps
such as 

```
  <rr:ObjectMap rdf:about="http://in4mium.com/masterdatakg/r2rml/id/sakila/objMap.actor.first_name">
    <rr:column>first_name</rr:column>
    <rr:datatype rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
    <rr:termType rdf:resource="http://www.w3.org/ns/r2rml#Literal"/>
  </rr:ObjectMap>
```

and

```
 <rr:ObjectMap rdf:about="http://in4mium.com/masterdatakg/r2rml/id/sakila/objMap.actor.last_name">
    <rr:column>last_name</rr:column>
    <rr:datatype rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
    <rr:termType rdf:resource="http://www.w3.org/ns/r2rml#Literal"/>
  </rr:ObjectMap>
```

However it is very handy to use these columns to create new properties from a combination of columns using a template directly in the r2rml
such as 

 ```
 <rr:ObjectMap rdf:about="http://in4mium.com/masterdatakg/r2rml/id/sakila/objMap.actor.full_name">
    <rr:template>{first_name} {last_name}</rr:template>
    <rr:datatype rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
    <rr:termType rdf:resource="http://www.w3.org/ns/r2rml#Literal"/>
  </rr:ObjectMap>
```

It would see that ontop does not support this functionality. But is allowed by other sql to rdf rdfization software.

In Ontop this has to be done by joining the data in the SQL query via a concat on the columns and then using the new column in the r2rml. This is very very time consuming as often we just want to use the r2rml to play with the data. 

It would seem relatively simple to enable this by iterating over the template with a tokenizer until all substitutions have been completed.

**Comment by ghxiao** [comment]
Hi @pashworth,

This kind of mapping should be supported by Ontop. Using ontop native mapping syntax, your example can be written as:
```
target :{id} :first_name {first_name}^^xsd:string ; :last_name {last_name}^^xsd:string ; :full_name "{first_name} {last_name}"^^xsd:string .
source SELECT id, first_name, last_name FROM person
```

Note that the quotes `"` needed is needed to enclose the template: `"{first_name} {last_name}"^^xsd:string `

**Comment by pashworth** [comment]
Excellent. Thanks for the info I will give it a try.

**Comment by kontchakov** [comment]
Hi @pashworth 

In R2RML, one can use multiple columns in IRI and literal templates, and Ontop supports that.

If you have an error message, please feel free to re-open the issue and provide details.

Best
Roman
