### ISSUE TITLE
Unnecessary escaping of IRIs?

### ISSUE THREAD

**Issue by KonradHoeffner** [ontop/ontop#468]
### Description
Ontop seems to convert parentheses to unicode symbols even though it is not necessary.

### Steps to Reproduce

1. Use a database with IRIs containing parentheses, such as <http://dbpedia.org/resource/Java_(programming_language)> 
2. Run ontop
3. The output now contains  <http://dbpedia.org/resource/Java_%28programming_language%29>

**Expected behavior:**
According to [the Turtle specification](https://www.w3.org/TR/turtle/):

    <' ([^#x00-#x20<>"{}|^`\] | UCHAR)* '>' /* #x00=NULL #01-#x1F=control codes #x20=space */

So every character that is not a control character or one of `<>|^`\` should be allowed, for example parentheses.

**Actual behavior:**
IRIs with parentheses seem to get converted to unicode references.

**Reproduces how often:**
Every time.

### Versions
Ontop 4.1

**Comment by bcogrel** [comment]
Hi Konrad,

Are you using an IRI template? If so, yes, parentheses should be percent-encoded as they are not part of the `iunreserved` production according to the R2RML standard (see https://www.w3.org/TR/r2rml/#from-template). The Ontop mapping language is aligned with this standard.

However, if the IRI is directly stored in the database and mapped as a column (not a template), no IRI-safe encoding should be applied.

IRI-safe encoding is an important mechanism for making IRI templates decomposable and applying many optimizations.

Best,
Benjamin

**Comment by KonradHoeffner** [comment]
Oh then it is working as intended, I am using a template. I didn't know that the allowed characters of the R2RML standard differ from those of the Turtle specification. I will use columns then, thanks!

**Comment by KonradHoeffner** [comment]
For anyone else with a similar problem, here is our solution as an example:

## Escaped Parentheses

```turtle
<#SwpHasProgrammingLanguageMap>
    rr:logicalTable [ rr:tableName "swp_has_programminglanguage" ]; 
    rr:subjectMap [
        rr:template "http://hitontology.eu/ontology/{swp_suffix}";
        rr:class hito:SoftwareProduct;
    ];
    rr:predicateObjectMap [
        rr:predicate hito:programmingLanguage;
        rr:objectMap [ rr:template "http://dbpedia.org/resource/{plang_suffix}"; rr:termType rr:IRI ];
    ].
```

## Unescaped Parentheses

```turtle
<#SwpHasProgrammingLanguageMap>
    rr:logicalTable [rr:sqlQuery """  
        SELECT
        CONCAT('http://hitontology.eu/ontology/',swp_suffix) AS swp,
        CONCAT('http://dbpedia.org/resource/',plang_suffix) AS plang
        FROM swp_has_programminglanguage
    """];
    rr:subjectMap [
        rr:column "swp";
        rr:class hito:SoftwareProduct;
    ];
    rr:predicateObjectMap [
        rr:predicate hito:programmingLanguage;
        rr:objectMap [ rr:column "plang"; rr:termType rr:IRI ];
    ].
```
