### ISSUE TITLE
question: could mappings be implemented with rdb-direct-mapping and SPARQL constructs instead of R2RML?

### ISSUE THREAD

**Issue by justin2004** [ontop/ontop#470]
Rather than implementing mappings with R2RML or the Ontop native format (.obda) would be be possible to first auto generate [rdb-direct-mappings](https://www.w3.org/TR/rdb-direct-mapping/) and then write SPARQL construct queries on top of the direct mappings?

SPARQL constructs are often powerful enough to do most of the graph transformations needed to "lift" raw rdf into modeled rdf. Also SPARQL constructs often need fewer lines than the equivalent task in R2RML or RML. For example, in [this](https://github.com/justin2004/rml-testing) project -- to produce the desired triples it took 37 lines of SPARQL vs 132 lines of RML.

I know this is possible for materializing triples. But is it possible when virtualizing them? That is, is there a place in Ontop to put user-defined SPARQL construct queries so that it is possible to query the constructed triples?

**Comment by bcogrel** [comment]
Hi @justin2004, in theory yes, with a RDB2RDF mapping and SPARQL queries you can generate a new mapping.
However, the Ontop codebase does not provide this functionality at the moment. 

As for virtualization concerns, one would have to look at important corner-cases, such as bnodes (no support for unlabeled bnode #372) and IRI-safe encoding for making the IRI templates decomposable (i.e. injective). For the latter aspect, the `ENCODE_FOR_URI` function could be used, but it is not exactly the same as the one of R2RML.

Best,
Benjamin

**Comment by justin2004** [comment]
Hi @bcogrel ,

>with a RDB2RDF mapping and SPARQL queries you can generate a new mapping
Do you have any tips on how to approach that? Are there any codebase examples that you know of?

**Comment by bcogrel** [comment]
I am aware of [Onprom](https://github.com/onprom/onprom) done by former colleagues of mine. I never took the time to dive into their codebase but I would expect their module `onprom-obdamapper` to do something of that kind.

**Comment by justin2004** [comment]
thanks
