### ISSUE TITLE
Snowflake connection problems

### ISSUE THREAD

**Issue by michalpie** [ontop/ontop#474]
Cannot connect to Snowflake with authentication using private key files

This is how my properties file looks like:
```
jdbc.url=jdbc:snowflake://<a_repo>.eu-central-1.snowflakecomputing.com/?user=userid&private_key_file=C:/apath/rsa_key.p8&role=A_ROLE&warehouse=A_WH&db=A_DB&schema=A_SCHEMA
jdbc.driver=net.snowflake.client.jdbc.SnowflakeDriver
jdbc.user=
#jdbc.name=
jdbc.password=
```

I get the error: JWT token is invalid

### Versions

I am using ontop-cli-4.1.1 on Windows.

### Additional Information

The problem seems to be related to Ontop only: I am able to successfully connect to Snowflake from IntelliJ using the same JDBC URL.

I suspect that the problem is with mandatory jdbc.user and jdbc.password properties. Setting jdbc.user to my userid did not help. All information required to log in is passed in the JDBC URL.

**Comment by bcogrel** [comment]
It should be fixed by https://github.com/ontop/ontop/commit/72e653da4adaa9b49d1770c1d6c7ff434df94c18.
