### ISSUE TITLE
Generate mapping file for bootstrapping

### ISSUE THREAD

**Issue by kealist** [ontop/ontop#475]
### Description

This may be a silly question, but I am trying to bootstrap an ontology from a database.  I can do this fine in the Protege + Ontop bundle, using the `Ontop -> Bootstrap ontology and mapping....` menu functionality, but is there a way to autogenerate an `odba` mapping file from the database from Ontop CLI, or is it another tool?  Looking at the documentation, there is a gap of information about this.  I'm still new to everything, but would like to be able to autogenerate these files from scripts as a starting point to work on rather than working through GUIs.  Thank you

### Versions

Ontop CLI

**Comment by bcogrel** [comment]
The CLI documentation has been updated: https://ontop-vkg.org/guide/cli.html#ontop-bootstrap
