### ISSUE TITLE
Potential parsing issue with Dremio/PSQL POSITION function

### ISSUE THREAD

**Issue by Muffexx** [ontop/ontop#476]
### Description

The SQL statement

    POSITION('-' IN (REVERSE(REPLACE(variableName, '.','-')))) +2)

is parsed to

    POSITION('-',REVERSE(REPLACE(v4."variableName",'.','-')))) + 2)) AS "v3"

Error message

    (org.apache.calcite.sql.parser.SqlParseException) Encountered "," at line 53, column 196.
    Was expecting one of:
        "IN" ...
        <QUOTED_STRING> ...
        "UESCAPE" ...
    
    com.dremio.exec.planner.sql.parser.impl.ParserImpl.convertException():349
    com.dremio.exec.planner.sql.parser.impl.ParserImpl.normalizeException():135
    org.apache.calcite.sql.parser.SqlParser.handleException():130
    org.apache.calcite.sql.parser.SqlParser.parseStmtList():185
    com.dremio.exec.planner.sql.SqlConverter.parseMultipleStatementsImpl():183
    com.dremio.exec.planner.sql.SqlConverter.parseSingleStatementImpl():198
    com.dremio.exec.planner.sql.SqlConverter.parse():214
    com.dremio.exec.planner.sql.handlers.commands.CommandCreator.getSqlCommand():277
    com.dremio.exec.planner.sql.handlers.commands.CommandCreator.toCommand():230
    com.dremio.exec.work.foreman.AttemptManager.plan():437
    com.dremio.exec.work.foreman.AttemptManager.lambda$run$1():349
    com.dremio.service.commandpool.CommandWrapper.run():62
    com.dremio.context.RequestContext.run():95
    com.dremio.common.concurrent.ContextMigratingExecutorService.lambda$decorate$3():199
    com.dremio.common.concurrent.ContextMigratingExecutorService$ComparableRunnable.run():180
    java.util.concurrent.ThreadPoolExecutor.runWorker():1149
    java.util.concurrent.ThreadPoolExecutor$Worker.run():624
    java.lang.Thread.run():748`

**Expected behavior:**
The first "," in the parsed statement should instead be "IN".

**Reproduces how often:**
Always

### Versions
4.2.0-SNAPSHOT (SPARQL endpoint)

### Additional Information
I'm addressing a PSQL database through Dremio.

regards
Muffexx

**Comment by bcogrel** [comment]
Hi @Muffexx , thanks for reporting the issue. We are not yet supporting the serialization of named arguments in SQL functions. I just created an issue for it: #477 .

Best,
Benjamin

**Comment by bcogrel** [comment]
Hi @Muffexx ,

Sorry for the late answer. 

You can mimic what has been done for PostgreSQL: https://github.com/ontop/ontop/blob/4e30316dd4c75bb958268990302858cd5a8db357/db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/PostgreSQLDBFunctionSymbolFactory.java#L43

The new function symbol would have to be added to the table of https://github.com/ontop/ontop/blob/4e30316dd4c75bb958268990302858cd5a8db357/db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DremioDBFunctionSymbolFactory.java#L30 .

Best,
Benjamin

**Comment by Muffexx** [comment]
Hey @bcogrel,

thanks! Now it works. :)

reagards,
Muffexx

**Comment by bcogrel** [comment]
Hi @Muffexx,

Sorry I didn't see your edit in time. Yes a PR would have been great, but I already committed a fix (https://github.com/ontop/ontop/commit/bafbf0a37f517c44bb7df2b2dccc66f2f10ad776). Could you please double-check it?

Best,
Benjamin

**Comment by Muffexx** [comment]
Hey @bcogrel,

the changes from https://github.com/ontop/ontop/commit/bafbf0a37f517c44bb7df2b2dccc66f2f10ad776 do not resolve the issue. At least not for me. I get the same error as before.

Kind regards
Muffexx

**Comment by bcogrel** [comment]
Sorry @Muffexx, I made a stupid mistake (https://github.com/ontop/ontop/commit/1d01a766cf91b3738b6503ddf9f498236ad12466). May I ask you to give it a second try?

**Comment by Muffexx** [comment]
Hi @bcogrel,

thanks for your time. Now it works as intended. Keep up the good work. 💪

Best,
Muffexx

**Comment by bcogrel** [comment]
Thanks!
