### ISSUE TITLE
Time function extension - duration

### ISSUE THREAD

**Issue by apano-on** [ontop/ontop#478]
### Time function extension - duration arithmetic

Implement functions in Ontop which perform arithmetic between timestamps and dates with the goal of supporting expressions which retrieve the duration in user specified units between two dates or datetimes e.g.:
```
now() - ‘1970-01-01’^^xsd:date 
```
```
?end - ?start < 5 (days)
```

The output of these functions should be durations in user-specified units. Tentative prefix for these functions will be ofn with namespace to be defined. The functions to be implemented are:

- [x] ofn:weeksBetween
- [x] ofn:daysBetween
- [x] ofn:hoursBetween
- [x] ofn:minutesBetween
- [x] ofn:secondsBetween
- [x] ofn:millisBetween

Support both xsd:dateTime and xsd:date.

Also investigate adding more specific datatypes related to [duration](https://github.com/w3c/sparql-12/wiki/Inventory-of-existing-extensions-to-SPARQL-1.1#extended-mathematics-operations-on-datetimeduration-datatypes). A similar implementation to what will be added is available [here](https://graphdb.ontotext.com/free/devhub/time-functions.html#durations-expressed-in-certain-units).

**Comment by apano-on** [comment]
Adopted the following rules which comply with the graphDB/Ontotext implementation:
- Datatype. xsd:long
- Namespace: <http://www.ontotext.com/sparql/functions/>
- Namespace prefix: ofn
- Truncation for date/datetime (where possible). GraphDB/Ontotext uses truncation, i.e. 25 days and 23 hours and 59 minutes difference --> 25 days difference. Some DB engines
automatically round to highest integer so this is not always possible.
- No Daylight Savings Time (DST) (where possible). GraphDB/Ontotext does not account for DST the extra (+1) or less (-1) hour.

Below is a list of DB engines which we aim to support and the respective functions/methodology used to get the desired time arithmetic:

- H2: [TIMESTAMPDIFF](http://www.h2database.com/html/functions.html#datediff)
- PostgreSQL: No built in function. Among several possibilities solution selected is to use [DATE_PART](https://www.postgresql.org/docs/8.1/functions-datetime.html) with some
math arithmetic to achieve the desired results as in https://www.sqlines.com/postgresql/how-to/datediff
- MySQL: [TIMESTAMPDIFF](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_timestampdiff)
  - Other notes: MySQL always seems to handle DST correctly.
- Microsoft SQL Server: [DATEDIFF](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-ver15)
  - Other notes: An automatic ceiling seems to apply for time difference with this function i.e. 2 hours and 20 minutes --> 3 hours. Dateline change applies in calculating new day i.e. 2 additional minutes from 23:59 to 00:01 is "one" day which is not what happens in GraphDB/Ontotext and other engines.
- DB2
  - [WEEKS_BETWEEN](https://www.ibm.com/docs/en/psfa/7.2.1?topic=functions-weeks-between),
  [DAYS_BETWEEN](https://www.ibm.com/docs/en/psfa/7.2.1?topic=functions-days-between),
  [HOURS_BETWEEN](https://www.ibm.com/docs/en/psfa/7.2.1?topic=functions-hours-between),
  [MINUTES_BETWEEN](https://www.ibm.com/docs/en/psfa/7.2.1?topic=functions-minutes-between),[SECONDS_BETWEEN](https://www.ibm.com/docs/en/psfa/7.2.1?topic=functions-seconds-between)
  - [SECONDS_BETWEEN](https://www.ibm.com/docs/en/psfa/7.2.1?topic=functions-seconds-between) is also used for milliseconds, by limiting truncation to 3 decimal figures.
  - [TRUNC](https://www.ibm.com/docs/en/db2/11.5?topic=functions-truncate-trunc) is used to mirror Ontotext/GraphDB behavior.
  - [TIMESTAMPDIFF](https://www.ibm.com/docs/en/db2/11.5?topic=functions-timestampdiff) does not work for milliseconds. Moreover, as per DB2 it is deemed less precise.
- Denodo
    - [GETTIMEINMILLIS](https://community.denodo.com/docs/html/browse/7.0/vdp/vql/appendix/syntax_of_condition_functions/date_processing_functions#gettimeinmillis) used for all in conjunction with some basic arithmetic.
    - [GETDAYSBETWEEN](https://community.denodo.com/docs/html/browse/7.0/vdp/vql/appendix/syntax_of_condition_functions/date_processing_functions#getdaysbetween) exists for calculations for days only. However, for consistency we do not use it.
    - [TRUNC](https://community.denodo.com/docs/html/browse/6.0/vdp/vql/appendix/syntax_of_condition_functions/arithmetic_functions#trunc) used to comply with ofn rules.
    - CAST to TIMESTAMP necessary for GETTIMEINMILLIS to work. It works fine for both
    TIMESTAMP AND DATE. It supports the letter "T" as divisor. More generic solution
    vs. TO_TIMESTAMP which would yield limitations in the date/datetime format. It 
    could be replaced in the future with a Denodo time normalization class.
- Spark SQL
    - [DATEDIFF](https://spark.apache.org/docs/2.3.0/api/sql/index.html#datediff) for days and weeks.
    - Difference between TIMESTAMPS for hours, minutes, seconds.
    - [unix_millis](https://docs.databricks.com/sql/language-manual/functions/unix_millis.html) for milliseconds. However, it will work only for Spark >=v3.1
    and beyond.
    - No truncation function. [FLOOR](https://spark.apache.org/docs/2.3.0/api/sql/index.html#floor) used instead providing conformity with 
    Ontotext/GraphDB behavior for positive differences but not negative ones.
  
- Dremio (Limited support)
  - Time function: [TIMESTAMPDIFF](http://docs.dremio.com/sql-reference/sql-functions/functions/TIMESTAMPDIFF/). However, no support for difference in milliseconds.
  - Implementation will limit support to the following user-provided datetimes in the query:
    - YYYY-MM-DDThh:mm:ss
    - YYYY-MM-DDThh:mm:ssZ
    - YYYY-MM-DDThh:mm:ssTZD

- Oracle
  - No built in function in the version available for free.
  - [EXTRACT](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions050.htm) to be used with some arithmetic to achieve desired results, with the exception of milliseconds.
  - Support to be limited for user input in the SPARQL query in an identical manner to Dremio.

I will open a draft pull request imminently (by tomorrow morning), also taking into account any other feedback.

**Comment by namedgraph** [comment]
I don't get it. Why the need for new functions if they can be expressed as arithmetic?

**Comment by apano-on** [comment]
I think since there is no approved official standard for time/duration arithmetic, it was not necessary to constrain the functionality to such a solution in this case.

**Comment by apano-on** [comment]
Issue resolved by changes implemented in #483.

**Comment by namedgraph** [comment]
@apano-on there is a standard: https://www.w3.org/TR/xpath-functions-31/#durations
