### ISSUE TITLE
Upgrade to RDF4J 3.7.4 and latest OWL API

### ISSUE THREAD

**Issue by avataar** [ontop/ontop#498]
### Description

RDF4J is on its way to release version 4.0.0 this year (currently there is 4.0.0-M1). This is a major version that introduces backward incompatible changes such as removal of long-deprecated methods and classes but also moving some classes to different packages.

Ontop is far from ready for such a big change but as a first step that will minimize what's needed in the future it needs to upgrade to the latest RDF4J 3.x (currently 3.7.4) and get rid of using deprecated methods and classes. The matters are slightly more complicated because third-party libraries (e.g. OWL API) may also use such deprecated methods and classes so they need to be upgraded too.

**Comment by avataar** [comment]
PR https://github.com/ontop/ontop/pull/499.

Note that some of the changes in the PR are not strictly necessary for the upgrade but they help if you want to compile the same codebase with RDF4J 4 support, e.g. getting the SERQL query language indirectly in the tests (since SERQL was removed in RDF4J 4).

**Comment by bcogrel** [comment]
Hi @avataar , thank you for the PR! 

Upgrading to RDF4J 3.7.4 and getting prepared for 4.0.0 is a good idea. The main difficulty at the moment comes from OWLAPI, which is a dependency shared with Protégé. Protégé still requires OWLAPI 4.5, so we will need to find a solution for both updating RDF4J and keeping the Protégé plugin working.

We are having a few ideas in mind and we are planning to start investigate them in the next coming days.

As for the SERQL queries, it makes sense to convert them in SPARQL, it should not take too long.

Best,
Benjamin

**Comment by bcogrel** [comment]
Hi Pavel, 

Thank you for proposing to rewrite the SERQL queries, that would be great. I think it is better to do it in a separate branch.

Benjamin

**Comment by ghxiao** [comment]
The latest development of Ontop v5 already moved to RDF4J 4.1.3 and OWLAPI 5.1.20.
