### ISSUE TITLE
Integration with Spark SQL

### ISSUE THREAD

**Issue by nomananwar07** [ontop/ontop#509]
### Description

I am working on integrating Ontop to my DataLake prototype in my master thesis. The datalake uses apache spark and for some reasons I want Ontop to use Spark SQL to query all databases through Spark SQL that will omit the need of defining seperate JDBC credential information for each database. 

I have studied Chimera (https://github.com/ontop/ontop/pull/422) as well but it uses Hive/thrift JDBC as communication with Spark cluster.

So far I am not able to understand codebase where the SQL queries are called, I would like to point those SQL queries to Spark SQL and get results in spark DataFrame. Where should I look into codebase, What are the classes responsible for that?

**Comment by ghxiao** [comment]
Hi @nomananwar07,

I understood that you don't want to take the results out from Spark, but keep them inside Spark as a DataFrame. In this case, I would suggest you have a look the SANSA-stack project http://sansa-stack.github.io/SANSA-Stack/. They have integrated Ontop inside, and it should work as the way you expected.

**Comment by nomananwar07** [comment]
Hi @ghxiao, Thanks for the valuable suggestion. 

To better understand the OnTop project from developer's point of view, Is their any class diagram or UML diagram available? Particularly for ontop/db module.

**Comment by bcogrel** [comment]
Hi @nomananwar07,

No, we don't have such diagrams nor extensive documentation of about Ontop's internals, just a few pages that can be found in the https://ontop-vkg.org/dev section.

In your case, you might be interested by https://ontop-vkg.org/dev/db-adapter.html#support-a-new-database-system, which explains how to extend Ontop to support new SQL dialects.

Would you be interested in learning something more specific, the best would be having a chat, where we could give you relevant pointers.

**Comment by nomananwar07** [comment]
Hi @bcogrel,

I studied the dev section, it says that spark SQL is already implemented.
To the best of my knowledge, Chimera provides an extension for OnTop to Spark, but they use Hive JDBC, not Spark SQL.

How can I initiate a chat? Their I can explain what my thesis is and what I want to do with OnTop.

**Comment by bcogrel** [comment]
Great, just drop an email at {firstname}.{lastname}@ontopic.ai with your availability next week.
