### ISSUE TITLE
Migrate out of Travis CI

### ISSUE THREAD

**Issue by wetneb** [ontop/ontop#512]
### Description

This repository does not seem to have continuous integration enabled anymore, since Travis CI discontinued its services.

### Steps to Reproduce

1.Go to a pull request
**Expected behavior:** 
See some CI results.
**Actual behavior:** 
The test suite is not run automatically.

**Comment by bcogrel** [comment]
Hi @wetneb, you are right, the CI on Github is not running anymore, we need to look for an alternative.

However, our main CI is still enabled on the Gitlab of the Free University of Bozen-Bolzano, where we run the full series of test, which, by contrast with Travis CI script, involves as well [external databases of various vendors](https://github.com/ontop/ontop-dockertests) (e.g. MySQL, PostgreSQL, Oracle).

**Comment by bcogrel** [comment]
After #529, we are now running the same tests as Travis used to do. The migration is complete.
