### ISSUE TITLE
Key difference betweene Ontop and traditional approach

### ISSUE THREAD

**Issue by Gautamshahi** [ontop/ontop#524]
I want to get the key difference between Ontop and the traditional approach to creating knowledge graphs. I googled it but didn't get much about it.

I am looking for a detailed difference or blog which could explain it.

**Comment by ghxiao** [comment]
Hi, I would recommend reading the following survey, where these aspects are discussed intensively:

Guohui Xiao Linfang Ding, Benjamin Cogrel, and Diego Calvanese

Virtual Knowledge Graphs: An Overview of Systems and Use Cases. In: Data Intelligence 1 (2019), pp. 201–223. 
http://www.ghxiao.org/publications/2019-dint-vkg-survey.pdf
