### ISSUE TITLE
Protegeé displays object properties as annotation properties

### ISSUE THREAD

**Issue by marcostranisci** [ontop/ontop#527]
Hi,

I don't know if it is something inherent to Ontop, but when I try to materialized triples with object properties in a new .ttl file (eg, :Artist :creates :Work ), the object property is not recognized as such on Protegée. Instead, it is displayed as an Annotation property. This happens both with the CLI and the plugin. If instead I materialize triples within the same ontology file everything is fine. 

Is Ontop supposed to work like this? (below two snapshot of the original ontology and the file produced as an output)
![orig](https://user-images.githubusercontent.com/5514585/169660170-a94db453-7aa4-47d9-a321-a13245974da1.png)
![materialized](https://user-images.githubusercontent.com/5514585/169660172-05f426a4-58dd-4550-8569-fd60c8d72b3a.png)

My best

**Comment by bcogrel** [comment]
Hi, Protégé expects properties to be declared as instances of `owl:ObjectProperty` to be recognised as object properties. When it does not know if it is an instance of `owl:ObjectProperty` or`owl:DataProperty`, it treats it is as an annotation property.

Ontop on its side has no problem dealing with any property.
The pain point you experienced is specific to the Protégé UI.

Best,
Benjamin

**Comment by marcostranisci** [comment]
Hi Benjamin,

thanks a lot, I've dealt with this painful point :)

best,
Marco
