### ISSUE TITLE
MSSQL 2008 cannot be queried by SPARQL when limit is used

### ISSUE THREAD

**Issue by chenkun19960427** [ontop/ontop#531]
### Description

MSSQL 2008 cannot be queried by SPARQL when limit is used.
I read #412, #225. ```ORDER BY``` was also added. But it didn't work for me.

### Steps to Reproduce

1. docker run [ontop/ontop-endpoint:latest](https://hub.docker.com/r/ontop/ontop-endpoint)
```
docker run -itd --name=ontop-endpoint \
    	-v /mnt/semanticpublish/ontop/input:/opt/ontop/input \
    	-v /mnt/semanticpublish/ontop/jdbc:/opt/ontop/jdbc \
    	-v /mnt/jdk/jdk1.8.0_191:/jdk1.8.0_191 \
    	-e ONTOP_MAPPING_FILE=input/ontop.obda \
    	-e ONTOP_PROPERTIES_FILE=input/ontop.properties \
    	-e JAVA_HOME=/jdk1.8.0_191 \
    	-e PATH=/jdk1.8.0_191/bin \
    	-p 8081:8080 \
    	ontop/ontop-endpoint
```

2. Query SPARQL：
```
SELECT ?s WHERE { ?s ?p ?o . } ORDER BY ?s OFFSET 0 LIMIT 10
```

**Expected behavior:** result without errors

**Actual behavior:** An error occurs during SPARQL query:
```
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'OFFSET'.
```

**Reproduces how often:** always

### Attached material

.obda:
```
[PrefixDeclaration]
: 	http://test.com/

[MappingDeclaration] @collection [[

mappingId	test
target		:{id} a :test .
source		select id from Basic_info

]]
```

### Versions

ontop version: docker [ontop/ontop-endpoint:latest](https://hub.docker.com/r/ontop/ontop-endpoint)
mssql version: SQL Server 2008
jdbc version: mssql-jdbc-8.2.0.jre8.jar
java version: jdk1.8.0_191

### Additional Information

1.This problem is not found in MySQL
2.This problem does not occur without ```limit```

**Comment by chenkun19960427** [comment]
> It might be caused by the lack of support for LIMIT in the 2008 SQL Server version. As indicated in #225, OFFSET and FETCH NEXT are used to translate limit for Microsoft SQL Server (also see the current translation [here](https://github.com/ontop/ontop/blob/version4/db/rdb/src/main/java/it/unibz/inf/ontop/generation/serializer/impl/SQLServerSelectFromWhereSerializer.java#L61)). However, FETCH NEXT is available only since SQL Server 2012 (shown [here](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/ms188385(v=sql.110)?redirectedfrom=MSDN)). An alternative translation would be necessary for SQL Server 2008.
> 
> You could try using a more recent SQL Server version (at least 2012) and see if this fixes the issue or request from the maintainers full support for LIMIT in SQL Server 2008 (though I think this version of SQL Server is no longer maintained by Microsoft since 2019).

Hi @apano-on ,

Thank you very much for your reply!

But I'm not allowed to change the SQL Server version.

Does that mean ontop does not support SQL Server 2008?

Will it be considered in the future?

Best Regards

**Comment by apano-on** [comment]
Hi @chenkun19960427 ,

Via this [commit](https://github.com/ontop/ontop/commit/018a1700d5ede44f88d951ff52a0e15008d69684) a workaround has been added which should now allow usage of limit and offset in SQL Server 2008 (and older versions) by using ROW_NUMBER() OVER (ORDER BY %s). You can try testing whether it works for your query.

In principle it is good to strive to support all used versions of SQL dialects but there is some engineering effort to get an instance for such old versions running in order to run tests. For example SQL Server only provides a docker image for versions 2017 and later https://hub.docker.com/_/microsoft-mssql-server?tab=description.

**Comment by bcogrel** [comment]
I close it for now and it should be fixed, but feel free to reopen the issue if the problem still persists for some old versions of SQL Server.

**Comment by chenkun19960427** [comment]
Thanks a lot.

I am using version: `docker pull ontop/ontop-endpoint:4.3.0-SNAPSHOT`

The problem `limit` has been solved. But when the number of `offset` is very large(1000000+), it will be very slow.
