### ISSUE TITLE
how to get sparql query results as ontology or list of RDFFacts? 

### ISSUE THREAD

**Issue by rrkotik** [ontop/ontop#534]
hello, i want to get sparql query result in form of ontology or list of RDFFact objects.
I found how it is realized in OntopMaterialize but can't find a solution for ontop query and also don't understand how to implement it by myself. 
Appreciate any help.

**Comment by rrkotik** [comment]
@ghxiao thanks for your answer. how can i translate output from executeConstructQuery(query) to triplets?
now i do something like `GraphOWLResultSet result = st.executeConstructQuery(query);` it contains what i need, how to translate it into list of RDFFact's?

**Comment by ghxiao** [comment]
First of all, Using OWLAPI interface Ontop is deprecated. You should better use the RDF4J interface:

There are two ways to use RDF4J:

1) [Recommended] Setup an SPARQL endpoint using Ontop. Use the standard RDF4J library to connect to the endpoint, and run the queries:

Check the example:

https://rdf4j.org/documentation/tutorials/getting-started/ <https://rdf4j.org/documentation/tutorials/getting-started/> 
Example 16: SPARQL CONSTRUCT Queries

2) [Less Recommended]. Using the RDF4J binding of Ontop, like this example:
https://github.com/ontop/ontop-api-examples/blob/master/src/main/java/it/unibz/inf/ontop/examples/rdf4j/OntopRDF4JR2RMLMappingExample.java

**Comment by rrkotik** [comment]
@ghxiao thank you very much for your help. it was very useful.
