### ISSUE TITLE
Can ontop reasoner support rule-based reasoning?

### ISSUE THREAD

**Issue by Cq5616** [ontop/ontop#538]
### Description
To the best of my knowledge, the reasoner of ontop (an OWL2 QL reasoner) is based on ontology. It can do something like completing the hierarchy of properties and classes, identifing domain/range from reverse property, etc. 
I wonder can ontop reasoner support rule-based reasoning?  For example, like Apache Jena rules engine. 
If ontop has its rule engine, how to use it ?

**Comment by bcogrel** [comment]
Hi @Cq5616, no Ontop does not directly support rule-based reasoning. 

Some colleagues investigated how to rewrite more expressive ontologies (e.g. OWL2 RL) into a OWL2 QL ontology with a larger mapping, and how to approximate these ontologies when all their expressive power cannot be expressed in this setting.

This work led to an article (https://arxiv.org/pdf/1511.08412.pdf) and a prototype implementation (https://github.com/ontop/ontoprox). Results were encouraging but so far this work hasn't been continued and nothing has been merged into Ontop.
