### ISSUE TITLE
Ontop Query Evaluation Exception  java.sql.SQLSyntaxErrorException

### ISSUE THREAD

**Issue by Amrosx** [ontop/ontop#540]
### Description
```
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: java.sql.SQLSyntaxErrorException: (conn=21) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"s_id1m4" AS "s_id1m4", V13."v1" AS "v1", V13."v6" AS "v6", V13."v9" AS "v9"
```

### Versions

ontop-cli version 4.1.1
with jdbc (mysql) mariadb-java-client-2.7.3.jar

### Additional Information

the SQL query I am running `select * from student;`
the table created is `create table student (s_id varchar(100), first_name varchar(100), last_name varchar(100));`

when I try to run sparql enpoint I face the above SQL syntax error ??

**Comment by bcogrel** [comment]
Hi @Amrosx, we haven't added yet support for MariaDB (but we do support MySQL). Here the generated query is following the conventions of the generic SQL adapter, not the MySQL's one, leading to a query rejected by MariaDB. For instance, it uses double-quotes instead of back-tits.

Which JDBC URL have you used? Have you tried with a MySQL one?
Ontop uses the JDBC driver class name or the JDBC URL to recognize the dialect. 

This could work by making it appear as a MySQL database.

Best,
Benjamin

**Comment by thomasjtaylor** [comment]
@Amrosx, as @bcogrel notes, you can use the mysql-connector-java JAR to connect to MariaDB.

If you need to use the mariadb-java-client, you can pass properties to augment/override the [`sql-default.properties`](
https://github.com/ontop/ontop/blob/62d0d08462be45781c94b3d627c3f9f062542717/db/rdb/src/main/resources/it/unibz/inf/ontop/injection/sql-default.properties)

For example, replace `com.mysql.jdbc.Driver` with `org.mariadb.jdbc.Driver` for these settings:
```
com.mysql.jdbc.Driver-serializer = it.unibz.inf.ontop.generation.serializer.impl.MySQLSelectFromWhereSerializer
com.mysql.jdbc.Driver-normalizer = it.unibz.inf.ontop.generation.normalization.impl.MySQLExtraNormalizer
com.mysql.jdbc.Driver-typeFactory = it.unibz.inf.ontop.model.type.impl.MySQLDBTypeFactory
com.mysql.jdbc.Driver-symbolFactory = it.unibz.inf.ontop.model.term.functionsymbol.db.impl.MySQLDBFunctionSymbolFactory
com.mysql.jdbc.Driver-metadataProvider = it.unibz.inf.ontop.dbschema.impl.MySQLDBMetadataProvider
```

**Comment by bcogrel** [comment]
Hi,

Support for MariaDB has just been added to the development version: https://github.com/ontop/ontop/issues/271 .
It will be available in the next major release.

By now, let me close this issue.
