### ISSUE TITLE
SQL parsing exception on boolean filter

### ISSUE THREAD

**Issue by qootec** [ontop/ontop#552]
### Description

When an OBDA mapping contains a SQL statement that contains a single boolean value, its parser seems to fail "walking the SQL abstract syntax tree".
This causes Ontop to fail to start.

### Steps to Reproduce

1. Create a mapping where the source part contains something like
`select * from myTable where validX`
where validX is a boolean column.
3. Start ontop reasoner (by starting the endpoint or explicitly in the plugin for Protégé)

**Expected behavior:**
It should just work :-)

**Actual behavior:**
Exception is raised:

`ontop-jml        | Caused by: java.lang.ClassCastException: class it.unibz.inf.ontop.model.term.impl.VariableImpl cannot be cast to class it.unibz.inf.ontop.model.term.ImmutableExpression (it.unibz.inf.ontop.model.term.impl.VariableImpl and it.unibz.inf.ontop.model.term.ImmutableExpression are in unnamed module of loader 'app')
ontop-jml        |      at it.unibz.inf.ontop.spec.sqlparser.ExpressionParser$TermVisitor.getExpression(ExpressionParser.java:643)
ontop-jml        |      at it.unibz.inf.ontop.spec.sqlparser.ExpressionParser$TermVisitor.access$000(ExpressionParser.java:163)
ontop-jml        |      at it.unibz.inf.ontop.spec.sqlparser.ExpressionParser.parseBooleanExpression(ExpressionParser.java:62)
ontop-jml        |      at it.unibz.inf.ontop.spec.sqlparser.SelectQueryParser.translateSelectBody(SelectQueryParser.java:91)
ontop-jml        |      at it.unibz.inf.ontop.spec.sqlparser.SelectQueryParser.parse(SelectQueryParser.java:28)
ontop-jml        |      at it.unibz.inf.ontop.spec.sqlparser.SQLQueryParser.getRAExpression(SQLQueryParser.java:29)
ontop-jml        |      at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.getRAExpression(SQLPPMappingConverterImpl.java:140)
ontop-jml        |      at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:61)
ontop-jml        |      at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:245)
ontop-jml        |      at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:216)
ontop-jml        |      at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:185)
ontop-jml        |      at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:151)
ontop-jml        |      at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:106)
ontop-jml        |      at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:46)
ontop-jml        |      at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:127)
ontop-jml        |      at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:87)
ontop-jml        |      at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47)
ontop-jml        |      at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34)
ontop-jml        |      at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44)
ontop-jml        |      at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20)
ontop-jml        |      at it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository.initializeInternal(OntopVirtualRepository.java:72)
ontop-jml        |      ... 43 more
ontop-jml        | Exception in thread "main" java.lang.AssertionError
ontop-jml        |      at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:30)`

**Reproduces how often:**
Always

### Versions

Ontop 4.2.1

### Additional Information

Problem is solved when the SQL query is reformulated as
`select * from myTable where validX=true`

**Comment by bcogrel** [comment]
Hi Johan, thanks for reporting the issue. 

Actually I already fixed it in June (https://github.com/ontop/ontop/commit/1df53221d03879eac717416dcf7b7a1be01bc967) but I forgot about it.

Best,
Benjamin
