### ISSUE TITLE
Ontology missing from Sparql construct queries using the university tutorial

### ISSUE THREAD

**Issue by WilliamWhispell** [ontop/ontop#555]
### Description

Following the tutorial on https://ontop-vkg.org/tutorial/

Attempting to query for any of the ontology definitions via the Ontop SPARQL UI page on port 8080 returns an empty result:

for example, a query for the triples defining the Student class is empty :
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://example.org/voc#>

SELECT * {
	:Student ?p ?o .
}
```

However, we see the university-complete.ttl file has the triples:
```
###  http://example.org/voc#Student
:Student rdf:type owl:Class ;
         rdfs:subClassOf foaf:Person .
```

In fact, non of the triples from the university-complete.ttl data is returned, only the individuals/instances are returned.

Here are the inputs to ONTOP:
```
ONTOP_ONTOLOGY_FILE=/opt/ontop/input/university-complete.ttl
ONTOP_MAPPING_FILE=/opt/ontop/input/university-complete.obda
ONTOP_PROPERTIES_FILE=/opt/ontop/input/university-complete.docker.properties
```

This seems similar to the issue reported in https://github.com/ontop/ontop/issues/302 - however, I'm not seeing any errors reported, but the result does not contain any triples for the class definitions, object property definitions, etc from the tutorial Ontology data file university-complete.ttl - When I navigate to the H2 database UI, I can see the data is present from the university-session1.h2.db file that is provided in the tutorial archive: https://ontop-vkg.org/tutorial/h2.zip - I can also verify that ontop is loading the university-complete.ttl file, because if I add garbage text before startup, the docker-compose process throws errors.

**Expected behavior:**

I would expect queries to ontop sparql service to provide results from both the OBDA mapping, but also the input ontology file.

**Actual behavior:** 

Triples from the ontology file are not included when querying the sparql endpoint.

**Comment by WilliamWhispell** [comment]
A possible workaround would be to use basic query federation, but I see that is currently unsupported in ONTOP.

Example,
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://example.org/voc#>

SELECT ?s ?p ?o 
WHERE
{
  ?s ?p ?o .
  SERVICE <http://localhost:8080/ontology> { 
    ?s ?p ?o .  
  }
}
```

**Comment by apano-on** [comment]
Try adding to the properties file:
```
ontop.enableFactExtractionWithTBox=true
```
as per https://ontop-vkg.org/guide/advanced/configuration.html.

**Comment by WilliamWhispell** [comment]
Thank you!

I set the evironment variable ONTOP_ENABLE_FACT_EXTRACTION_WITH_T_BOX=true and this worked for the docker setup as expected.

**Comment by zwelz3** [comment]
Can you provide any insight into why `false` is the default behavior?
