### ISSUE TITLE
Ontop Extract-DB-Metadata Fails for oracle.jdbc.driver.OracleDriver

### ISSUE THREAD

**Issue by thomasjtaylor** [ontop/ontop#557]
### Description

Extracting DB Metadata using `OntopExtractDBMetadata` from the command-line results in an error/failure using the `oracle.jdbc.driver.OracleDriver`.

### Steps to Reproduce

1. Start Docker Oracle XE 21.3.0
   `docker run --rm --name ontop-oracle -p 1521:1521 -e "ORACLE_PWD=Rdb2RdfTest" container-registry.oracle.com/database/express:21.3.0-xe`
2. Create `Rdb2RdfTest` User/Schema in Oracle in the `PDB`
3. Configure database connection properties:
```
jdbc.driver=oracle.jdbc.driver.OracleDriver
jdbc.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
jdbc.user=Rdb2RdfTest
jdbc.password=Rdb2RdfTest
```
5. Run ontop-cli: 
   `Ontop extract-db-metadata -p _test/db.properties -o _test/db-metadata.txt`

**Expected behavior:** [What you expect to see]

Produce a `db-metadata.txt` database metadata file for the `Rdb2RdfTest` Oracle schema.

**Actual behavior:** [What actually happens]

Syserr Message: 
`Cannot find relation "CTXSYS"."SYS_IOT_OVER_64708" (available choices: [ ...(every Oracle Schema/Table)... ]`

**Reproduces how often:** [Does it happen every time?]

Every time.

### Versions

Ontop 4.2.1 (JARs from Maven Central)

#### Workaround 1: Use `oracle.jdbc.OracleDriver`
Ontop's default `sql-settings.properties` also supports use of the `oracle.jdbc.OracleDriver`. Using this driver resolves the issue.
```
jdbc.driver=oracle.jdbc.OracleDriver
jdbc.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
jdbc.user=Rdb2RdfTest
jdbc.password=Rdb2RdfTest
```

#### Workaround 2: Add correct setting in user/database properties:
```
jdbc.driver=oracle.jdbc.driver.OracleDriver
jdbc.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
jdbc.user=Rdb2RdfTest
jdbc.password=Rdb2RdfTest
oracle.jdbc.driver.OracleDriver-metadataProvider=it.unibz.inf.ontop.dbschema.impl.OracleDBMetadataProvider
```
### Fix - change [sql-settings.properties](https://github.com/ontop/ontop/blob/c5632c7876af70d144edda413e627f40baab22d6/db/rdb/src/main/resources/it/unibz/inf/ontop/injection/sql-default.properties#L77)
4.2.1:   `oracle.jdbc.Driver.OracleDriver-metadataProvider = it.unibz.inf.ontop.dbschema.impl.OracleDBMetadataProvider`
FIXED: `oracle.jdbc.driver.OracleDriver-metadataProvider = it.unibz.inf.ontop.dbschema.impl.OracleDBMetadataProvider`

#556 Fixes this issue

**Comment by bcogrel** [comment]
Many thanks @thomasjtaylor !
I also appreciated you provided a complete example to reproduce the issue.

Best,
Benjamin
