### ISSUE TITLE
"extract-db-metadata" fails for postgres with the "timescaledb" extension enabled

### ISSUE THREAD

**Issue by Aklakan** [ontop/ontop#570]
### Description

Timescaledb is postgres extension for temporal data. One reason to use the plugin is justified as follows: While vanilla postgres has support for partitioning tables e.g. by time, it lacks the feature of automatically create child tables for intervals - such as every 4hours or every day. Timescaledb adds a set of database objects, such as "hypertables" which are much like partitions however with support for automatically creating child tables (AFAIK via insert triggers).

If a postgres dbms is set up with timescaledb e.g. according to [these setup instructions](https://docs.timescale.com/install/latest/self-hosted/installation-debian/) then the extension can be enabled on a database with  `CREATE EXTENSION IF NOT EXISTS timescaledb;`.

### Steps to Reproduce
Run `./ontop extract-db-metadata -p mydb.local.ontop.properties -o mydb.local.ontop.dbmetadata.json` against a potsgres with timescaledb extension enabled.

**Expected behavior:** A file with the db-metadata JSON

**Actual behavior:** Neither file creation, nor JSON output - just the error below:

```
Cannot find relation "_timescaledb_cache"."cache_inval_bgw_job"

(available choices: ["_timescaledb_cache"."cache_inval_bgw_job", "_timescaledb_cache"."cache_inval_extension", "_timescaledb_cache"."cache_inval_hypertable", "_timescaledb_catalog"."chunk", "_timescaledb_catalog"."chunk_constraint", "_timescaledb_catalog"."chunk_copy_operation", "_timescaledb_catalog"."chunk_data_node", ...)
```

### Versions

Ontop CLI 4.2.1, Postgres Ubuntu 14.6-1.pgdg22.04+1

### Additional Information
Running the `endpoint` command with the same properties file works without warnings or errors - so it seems something is handled differently in `extract-db-metadata`.
Maybe `endpoint` performs metadata extraction w.r.t. the logical tables mentioned in the (r2rml) mapping file? If so, then it might make sense to extend `extract-db-metadata` to accept a mapping file against which to analyze.

Also, probably the `extract-endpoint-command` should have an option to simply ignore such types of errors.

**Comment by bcogrel** [comment]
Hi @Aklakan, thanks for reporting the issue.

We decided to ignore the tables in schema with names starting with `_timescaledb`: https://github.com/ontop/ontop/commit/f17084eafbaabc2959cc9dea2cfb03c8fc80af77

We tested it on an instance of TimescaleDB.

I will create another issue for your idea of using the CLI just for extracting db-metadata only the relations used in a mapping. You guessed right, the Ontop endpoint only extracts the relevant metadata at runtime.

Best,
Benjamin

**Comment by Aklakan** [comment]
Thanks for the prompt response. A more future proof/general solution would probably be to add support for exclusion patterns for schema and table names either in the properties file (not sure if there is a better location) - (you know that :) ) - but I guess the popularity of timescaledb justifies a quick fix :)
