### ISSUE TITLE
Error: java.lang.IllegalArgumentException: Nullable attribute  cannot be in a PK

### ISSUE THREAD

**Issue by CaioViktor** [ontop/ontop#574]
Hi everyone,

I am trying materialize some triples from a ORACLE database to create study of the graph been constructed. However, everytime I run the materialize using the CLI it givens the following error:

java.lang.IllegalArgumentException: Nullable attribute "ROB_RUC_OBLIGACION" NUMBER(14) cannot be in a PK
	at it.unibz.inf.ontop.dbschema.impl.UniqueConstraintImpl$PrimaryKeyBuilder.addDeterminant(UniqueConstraintImpl.java:79)
	at it.unibz.inf.ontop.dbschema.impl.AbstractDBMetadataProvider.insertPrimaryKey(AbstractDBMetadataProvider.java:241)
	at it.unibz.inf.ontop.dbschema.impl.AbstractDBMetadataProvider.insertIntegrityConstraints(AbstractDBMetadataProvider.java:212)
	at it.unibz.inf.ontop.dbschema.impl.CachingMetadataLookup.extractImmutableMetadata(CachingMetadataLookup.java:57)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:247)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:216)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:185)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:151)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:106)
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:46)
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:127)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:87)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47)
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34)
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44)
	at it.unibz.inf.ontop.materialization.impl.DefaultOntopRDFMaterializer.<init>(DefaultOntopRDFMaterializer.java:48)
	at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer.<init>(DefaultRDF4JMaterializer.java:59)
	at it.unibz.inf.ontop.rdf4j.materialization.RDF4JMaterializer.defaultMaterializer(RDF4JMaterializer.java:34)
	at it.unibz.inf.ontop.cli.OntopMaterialize.createMaterializer(OntopMaterialize.java:124)
	at it.unibz.inf.ontop.cli.OntopMaterialize.run(OntopMaterialize.java:105)
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:18)
Exception in thread "main" java.lang.AssertionError
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:30)

I am running the following command:
./ontop materialize -m maps.ttl -p config.properties -o out.ttl -f turtle

The mapping I am using are the following R2RML:

@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix ex: <http://example.com/ns#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix dc: <http://purl.org/dc/elements/1.1/>.
@prefix vcard: <http://www.w3.org/2006/vcard/ns#>.
@prefix dcterms: <http://purl.org/dc/terms/>.
@prefix skos: <http://www.w3.org/2004/02/skos/core#>.
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sfz: <http://www.sefaz.ma.gov.br/ontology/> .
@prefix map: <http://sistemas.sefaz.ma.gov.br/maps/RFB/2020-04-01> .
@prefix sd: <http://www.w3.org/ns/sparql-service-description#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix tl: <http://purl.org/NET/c4dm/timeline.owl#> .
#TABELA APL_HIS.O$_RUC_OBLIGACIONES

map:EstabelecimentoCAD a rr:TripleMap;
    rr:logicalTable [
        rr:sqlQuery """
            select r.RGE_RUC,r.RGE_CGC_CPF from APL_HIS.O$_RUC_OBLIGACIONES h INNER JOIN "APL_ARR".RUC_GENERAL r ON h.ROB_RUC_OBLIGACION =  r.RGE_RUC WHERE NOT (ANTES = 'DESCONHECIDO' AND DEPOIS IS NULL) AND NOT (ANTES IS NULL AND DEPOIS IS NULL) AND CAMPO IN ('ROB_FEC_FIN_OBLIG', 'ROB_FEC_INIC_OBLIG', 'ROB_TIM_COD_IMPUESTO', 'ROB_PERIODICIDAD_OBLIG') AND h.ROB_RUC_OBLIGACION = '12102597'
        """;
    ];
    rr:subjectMap [
        rr:template "http://www.sefaz.ma.gov.br/resource/Cadastro_SEFAZ-MA/Estabelecimento/{RGE_CGC_CPF}";
        rr:class sfz:Estabelecimento;
    ];
    rr:predicateObjectMap [
        rr:predicate sfz:tem_timeLine;
        rr:objectMap [
            rr:template "http://www.sefaz.ma.gov.br/resource/Cadastro_SEFAZ-MA/TimeLine/{RGE_CGC_CPF}";
        ];
    ]; 
    rr:predicateObjectMap [
        rr:predicate rdfs:label, sfz:cnpj;
        rr:objectMap [
            rr:column '"RGE_CGC_CPF"';
            rr:datatype xsd:string
        ];
    ].

The only relevant part of the query is this:
select r.RGE_RUC,r.RGE_CGC_CPF from APL_HIS.O$_RUC_OBLIGACIONES h INNER JOIN "APL_ARR".RUC_GENERAL r ON h.ROB_RUC_OBLIGACION =  r.RGE_RUC 

This is just a simple junction between two tables. It says that the field O$_RUC_OBLIGACIONES cannot be a PK, but it is not a PK and it is not even used in the URI.

I already materialized other fragments from the graph, so the ontop is working in other cases, but not in this. I am using the ontop cli version "ontop-cli-4.2.2". The SQL query runs without any problemns in the SQLDeveloper. In the table, the field h.ROB_RUC_OBLIGACION don't have any null value. Unfortunatily I can't set the field as NOT NULL.

**Comment by kontchakov** [comment]
Hi @CaioViktor 

Thanks for reporting this issue. Ontop retrieves information about all columns in all relevant tables. In particular, it retrieves all nullability constraints, primary and foreign keys. It seems that in your setup, the information provided by the Oracle JDBC driver is not quite what is expected by Ontop: the column declared as being the primary key turns out to be nullable (from the JDBC driver point of view). I just wonder which version of the JDBC driver you use. It would also be helpful if you could share the definition of tables APL_HIS.O$_RUC_OBLIGACIONES and "APL_ARR".RUC_GENERAL. 

Thanks
Roman

**Comment by CaioViktor** [comment]
Hi @kontchakov,

Thank you for your response. I'm using the latest OJDBC 11 with JDBC 4.3 spec and certified with JDK11 and JDK17.
The table definitions are as follow:

CREATE TABLE "APL_HIS"."O$_RUC_OBLIGACIONES" 
   (    "ROB_RUC_OBLIGACION" NUMBER(14,0), 
    "ROB_TIM_COD_IMPUESTO" VARCHAR2(3 BYTE), 
    "ROB_FEC_INIC_OBLIG" DATE, 
    "CAMPO" VARCHAR2(30 BYTE), 
    "HORA" DATE, 
    "ANTES" VARCHAR2(4000 BYTE), 
    "DEPOIS" VARCHAR2(4000 BYTE), 
    "OSUSER" VARCHAR2(30 BYTE), 
    "DBUSER" VARCHAR2(30 BYTE), 
    "PROGRAM" VARCHAR2(64 BYTE), 
    "MACHINE" VARCHAR2(64 BYTE), 
     PRIMARY KEY ("ROB_RUC_OBLIGACION", "ROB_TIM_COD_IMPUESTO", "ROB_FEC_INIC_OBLIG", "CAMPO", "HORA") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_HIS" ;



CREATE TABLE "APL_ARR"."RUC_GENERAL" 
   (    "RGE_RUC" NUMBER(14,0) NOT NULL ENABLE, 
    "RGE_NOMBRE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
    "RGE_TIP_PERSONA" NUMBER(1,0) NOT NULL ENABLE, 
    "RGE_NACIONALIDAD" NUMBER(1,0), 
    "RGE_DOMICILIADO_PAIS" NUMBER(1,0), 
    "RGE_TAB_COD_UNIDAD" NUMBER(2,0), 
    "RGE_TAE_COD_ACTIVIDAD" NUMBER(8,0), 
    "RGE_MES_CIERRE_ACT" NUMBER(2,0), 
    "RGE_TIP_BAJA" NUMBER(2,0), 
    "RGE_NOT_ELECTRONICA" VARCHAR2(1 BYTE), 
    "RGE_CGC_CPF" NUMBER(14,0) NOT NULL ENABLE, 
    "RGE_RUC_CONDICION" NUMBER(2,0) NOT NULL ENABLE, 
    "RGE_TMU_COD_MUNICIPIO" NUMBER(7,0) NOT NULL ENABLE, 
    "RGE_TCO_CONDICION_PAGO" NUMBER(2,0), 
    "RGE_TSC_SIT_CADASTRAL" NUMBER(2,0) NOT NULL ENABLE, 
    "RGE_OPT_SIMPLIFICADO" VARCHAR2(1 BYTE), 
    "RGE_FEC_ACTUALIZACION" DATE, 
    "RGE_REGIMEN_ESPECIAL" NUMBER(2,0), 
    "RGE_IND_SUBST_TRIBUT" NUMBER(1,0), 
    "RGE_TUS_COD_USUARIO" VARCHAR2(20 BYTE), 
    "RGE_VAL_ESTIMADO" NUMBER(14,2), 
    "RGE_REMISSO" NUMBER(1,0), 
    "RGE_IND_GRANDE_CONTRIB" NUMBER(1,0), 
    "RGE_RANK_ARRECADACAO" NUMBER(6,0), 
    "RGE_REGIME_ANTERIOR" NUMBER(1,0), 
    "RGE_TIPO_CADASTRO" NUMBER(1,0) NOT NULL ENABLE, 
    "RGE_INSC_ESTADUAL" NUMBER(14,0), 
    "RGE_TRANSFERIDO_VIVANOTA" NUMBER(1,0), 
    "RGE_SERASA" NUMBER(1,0), 
    "RGE_RUC_CENTRALIZADOR" NUMBER(14,0), 
    "RGE_DATA_ULT_ALT" DATE, 
    "RGE_DATA_SIT_CADASTRAL" DATE, 
    "RGE_NIVELCUMPRIMENTO" NUMBER(1,0), 
    "RGE_ORIGEM_CAD" NUMBER(2,0), 
     CONSTRAINT "PK_RUC_GENERAL" PRIMARY KEY ("RGE_RUC")
  USING INDEX (CREATE INDEX "APL_ARR"."IDX_RUC_GENERAL_04" ON "APL_ARR"."RUC_GENERAL" ("RGE_RUC", "RGE_TMU_COD_MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2826240 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_I_CAD" )  ENABLE, 
     CONSTRAINT "CK_TIPO_CADASTRO" CHECK (rge_tipo_cadastro in (1,2,3)) ENABLE, 
     CONSTRAINT "CK_REMISSO" CHECK (RGE_REMISSO=1) ENABLE, 
     CONSTRAINT "CK_CGC_CPF" CHECK (RGE_CGC_CPF>0) ENABLE NOVALIDATE, 
     SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS, 
     SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS, 
     SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING

**Comment by kontchakov** [comment]
A bug fix has been implemented: d7b41d4908420c80dff73f6eb5bb2145a3783074
