### ISSUE TITLE
Let users declare columns as URL-safe in lenses

### ISSUE THREAD

**Issue by bcogrel** [ontop/ontop#587]
As recently reported in the thread of #312 by @GeorgFerdinandSchneider and @VladimirAlexiev, the translation of R2RML's safe-encoding mechanism in SQL queries introduces a significant performance penalty when materializing the RDF graph.

In many cases this URL-safe-encoding function does not modify the DB string so we should give the option to users to declare this transformation as unnecessary.

This could be a novel kind of constraint to be specified in [lenses](https://ontop-vkg.org/guide/advanced/lenses.html#constraints), as we already do for non-nullability constraints and general functional dependencies.

**Comment by yaskoo** [comment]
@bcogrel do you have an idea when this might be implemented?

**Comment by bcogrel** [comment]
@yaskoo, I am planning to start working on it in the coming days. It should not be a lot of work, so I expect to have something to share early February.

**Comment by bcogrel** [comment]
Implemented by https://github.com/ontop/ontop/commit/978a18bc7f88b829cba176ec7e1e232ebce8daab. The new key is `iriSafeConstraints` (see the updated [lens documentation](https://ontop-vkg.org/guide/advanced/lenses)).

See [this file](https://github.com/ontop/ontop/blob/version5/binding/rdf4j/src/test/resources/person/views/no-iri-encoding-lens.json) for an example.

This feature will be included in 5.0.2. It is already available in the Maven snapshot (5.0.2-SNAPSHOT).

@yaskoo, @GeorgFerdinandSchneider and @VladimirAlexiev, please give it a try and let me know if you need something.

**Comment by yaskoo** [comment]
@bcogrel, we're currently working on integrating this. Thanks!
