### ISSUE TITLE
Ontop v5 OracleDBMetaDataProvider change from USER_TABLES to ALL_TABLES causes RelationNotFoundInMetadataException

### ISSUE THREAD

**Issue by thomasjtaylor** [ontop/ontop#590]
### Description
Commit [bd4ab20d8d6f74c8f8bc19f3f2385f9604cb59b5](https://github.com/ontop/ontop/commit/bd4ab20d8d6f74c8f8bc19f3f2385f9604cb59b5) by @bcogrel changed the default behavior of the OracleDBMetaDataProvder from using `user_tables` to using `all_tables`. 

Note: commit [ec53960a0b3a6324f49001524a7e39c36801d5a3](https://github.com/ontop/ontop/commit/ec53960a0b3a6324f49001524a7e39c36801d5a3) updates the OracleDBMetaDataProvider, but still causes the issue.

In my [Rdb2RdfTests](https://github.com/thomasjtaylor/ontop/tree/r2rml-pgsql) branch for [Rdb2RdfTestsOracle](https://github.com/thomasjtaylor/ontop/blob/7439aeefafa3271361f7c324d3f67696819272ef/test/rdb2rdf-compliance/src/test/java/RDB2RDFTestOracle.java), this has caused:
```
it.unibz.inf.ontop.exception.MappingBootstrappingException: \
  it.unibz.inf.ontop.exception.RelationNotFoundInMetadataException: \
    Cannot find relation "WMSYS"."SYS_IOT_OVER_23962" 
```
If I revert the latest OracleDBMetaDataProvider changes, to commit [d7b41d4908420c80dff73f6eb5bb2145a3783074](https://github.com/ontop/ontop/commit/d7b41d4908420c80dff73f6eb5bb2145a3783074), I don't get this exception and my query runs as expected.

If I add `WMSYS` to the `all_tables` owner exclusions, I get:
`Cannot find relation "ORDDATA"."ORDDCM_PREFS_DEF_VALUES_TAB" `

If I also add `ORDDATA` to the `all_tables` owner exclusions, the queries seem to work correctly.

### Versions
Ontop: `version5`
Oracle: Docker Image: `container-registry.oracle.com/database/express:21.3.0-xe`
Oracle JDBC Driver:  `com.oracle.database.jdbc:ojdbc11:21.7.0.0`

### Additional Information
My tests are in [Rdb2RdfTests](https://github.com/thomasjtaylor/ontop/tree/r2rml-pgsql) branch.

**Comment by thomasjtaylor** [comment]
@bcogrel Let me know if I should add a PR for my Rdb2RdfTests branch (part of the ontop-rdb2rdf-compliance tests). There are a few failures in these tests that I need to explore and possibly add issues.

**Comment by bcogrel** [comment]
Many thanks @thomasjtaylor ! I merged it and also backported it so it can take part of v5.0.2.

Regarding your RDB2RDF tests, yes that would be nice to add them to the CI pipeline. There is a recent module, [`ontop-lightweight-tests`](https://github.com/ontop/ontop/tree/version5/test/lightweight-tests), that would be well-suited to host them. It already has Docker images for Oracle, PostgreSQL, SQL Server and MySQL (amongst others), which could be extended to these tests.

By contrast the module `ontop-rdb2rdf-compliance` does not depend on any external or Docker database, only on H2, which makes it executable anywhere.
