### ISSUE TITLE
Rdb2RdfTests MySQL createDBConcatOperator throws UnsupportedOperationException - Not supported by MySQL

### ISSUE THREAD

**Issue by thomasjtaylor** [ontop/ontop#597]
# Description
Several Rdb2RdfTests for MySQL fail with `UnsupportedOperationException: Not supported by MySQL`.
Caused by calling `MySQLDBFunctionSymbolFactory.createDBConcatOperator`.

Each of the failing cases uses a custom r2rml mapping that includes the double-pipe `||` concatenation operator.

[MySQLDBFunctionSymbolFactory](https://github.com/ontop/ontop/blob/version5/db/rdb/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/MySQLDBFunctionSymbolFactory.java).createDBConcatOperator:
```
    @Override
    protected DBConcatFunctionSymbol createDBConcatOperator(int arity) {
        throw new UnsupportedOperationException(UNSUPPORTED_MSG);
    }
```

Rather than throwing an exception, it seems reasonable to follow the approach used by most other DMBS implementations and return a NullRejectingDBConcatFunctionSymbol.

- Option 1: Use `NullRejectingDBConcatFunctionSymbol(CONCAT_STR, arity, dbStringType, abstractRootDBType, false);`
  - `CONCAT_STR = "CONCAT"`
  - This is the approach implemented by DB2, Denodo, Dremio, H2, Postgres, Snowflake, Spark, SQL Server
 - Option 2: Use `NullToleratingDBConcatFunctionSymbol(CONCAT_OP_STR, arity, dbStringType, abstractRootDBType, true);`
   - `CONCAT_OP_STR = "||"`
   - This is the approach implemented by Default, Oracle, Teiid

## Secondary Problem
Once this first issue is resolved, a second issue appears in the R2RML mapping for [D002](#d002) and [D014](#d014), where the R2RML mapping creates a new entity key `Select ('Student' || "ID" ) AS StudentId`, but Ontop returns a blank-node/generated key. (See test failures below in [Detailed Testing](#detailed-testing).

## Steps to Reproduce
1. Start MySQL
`docker run --rm --name ontop-mysql -p 3694:3306 -e MYSQL_ROOT_PASSWORD=mysql mysql:5`

2. Run [RDB2RDFTestMySQL.java](https://github.com/thomasjtaylor/ontop/blob/r2rml-pgsql/test/rdb2rdf-compliance/src/test/java/RDB2RDFTestMySQL.java) for D002, D003, and D014

**Expected behavior:** Ontop query results

**Actual behavior:** `UnsupportedOperationException: Not supported by MySQL`

**Reproduces how often:** Always

## Versions
Ontop: 5.0.2-SNAPSHOT
MySQL Docker: mysql:5
MySQL Connector J: mysql-connector-java:8.0.21

# Detailed Testing

### D002
| Test Case | Test ID | SQL Schema | R2RML Mapping | Expected Output |
|-----------|---------|---------------|--------------------|--------------------|
| [D002](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D002/) | tc002d | [create.sql](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D002/create.sql) | [r2rmld.ttl](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D002/r2rmld.ttl) |  [mappedd.nq](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D002/mappedd.nq) |

Schema
```
CREATE TABLE "Student" (
"ID" INTEGER,
"Name" VARCHAR(15)
);
INSERT INTO "Student" ("ID", "Name") VALUES(10,'Venus');
```
r2rml Mapping (fragment)
```
    rr:logicalTable [ 
                     rr:sqlQuery """
                       Select ('Student' || "ID" ) AS StudentId
                            , "ID"
                            , "Name"
                         from "Student"
                       """
                       ];
```
Expected Result
```
_:Student10 <http://xmlns.com/foaf/0.1/name> "Venus" .
```

Native Query (with NullRejectingDBConcatFunctionSymbol):
![Status](https://img.shields.io/badge/Test-FAIL-red.svg) Failed - result does not include custom mapping `StudentId` key (uses bnode)
```
13:10:40.708 [Thread-1] DEBUG i.u.i.o.a.r.impl.QuestQueryProcessor - Resulting native query:
ans1(s,p,o)
CONSTRUCT [s, p, o] [p/<http://xmlns.com/foaf/0.1/name>, s/RDF(CONCAT2("Student"^^TEXT,ID1m1),BNODE), o/RDF(VARCHARToTEXT(Name1m1),xsd:string)]
   NATIVE [ID1m1, Name1m1]
SELECT DISTINCT v1.`ID` AS `ID1m1`, v1.`Name` AS `Name1m1`
FROM `Student` v1
WHERE (v1.`ID` IS NOT NULL AND v1.`Name` IS NOT NULL)

13:10:40.908 [main] DEBUG RDB2RDFTestBase - Result:
_:genid311e6ce20ef0e0943c5b2cc67662806995689a1177 <http://xmlns.com/foaf/0.1/name> "Venus" .
```

Native Query (with NullToleratingDBConcatFunctionSymbol)
![Status](https://img.shields.io/badge/Test-FAIL-red.svg) Failed - result does not include custom mapping `StudentId` key (uses bnode)
```
13:16:12.649 [Thread-1] DEBUG i.u.i.o.a.r.impl.QuestQueryProcessor - Resulting native query:
ans1(s,p,o)
CONSTRUCT [s, p, o] [p/<http://xmlns.com/foaf/0.1/name>, s/RDF(||2("Student"^^TEXT,ID1m1),BNODE), o/RDF(VARCHARToTEXT(Name1m1),xsd:string)]
   NATIVE [ID1m1, Name1m1]
SELECT DISTINCT v1.`ID` AS `ID1m1`, v1.`Name` AS `Name1m1`
FROM `Student` v1
WHERE v1.`Name` IS NOT NULL

13:16:12.851 [main] DEBUG RDB2RDFTestBase - Result:
_:genid311daa6f1a3cda94595ebc0016101027b76f523c72 <http://xmlns.com/foaf/0.1/name> "Venus" .
```

### D003/r2rmlb.ttl
| Test Case | Test ID | SQL Schema | R2RML Mapping | Expected Output |
|-----------|---------|---------------|--------------------|--------------------|
| [D003](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D003/) | tc003b | [create.sql](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D003/create.sql) | [r2rmlb.ttl](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D003/r2rmlb.ttl) |  [mappedb.nq](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D003/mappedb.nq) |

Schema
```
13:10:41.227 [main] DEBUG RDB2RDFTestBase - tc0003b CreateDB
CREATE TABLE "Student" (
"ID" INTEGER,
"FirstName" VARCHAR(50),
"LastName" VARCHAR(50)
);
INSERT INTO "Student" ("ID", "FirstName", "LastName") VALUES (10,'Venus', 'Williams');
```
R2RML Mapping (fragment)
```
     rr:logicalTable [ 
                     rr:sqlQuery """
                     SELECT "ID",
                            ("FirstName" || ' ' || "LastName") AS Name
                     FROM "Student"
                     """
                     ];
```
Expected Result:
```
<http://example.com/Student/10> <http://xmlns.com/foaf/0.1/name> "Venus Williams" .
```

Native Query (NullRejecting)
![Status](https://img.shields.io/badge/Test-SUCCESS-green.svg)
```
13:10:42.041 [Thread-4] DEBUG i.u.i.o.a.r.impl.QuestQueryProcessor - Resulting native query:
ans1(s,p,o)
CONSTRUCT [s, p, o] [p/<http://xmlns.com/foaf/0.1/name>, s/RDF(http://example.com/Student/{}(INTToTEXT(ID1m1)),IRI), o/RDF(v0,xsd:string)]
   NATIVE [ID1m1, v0]
SELECT DISTINCT v1.`ID` AS `ID1m1`, CONCAT(CONCAT(v1.`FirstName`,' '),v1.`LastName`) AS `v0`
FROM `Student` v1
WHERE (v1.`ID` IS NOT NULL AND v1.`FirstName` IS NOT NULL AND v1.`LastName` IS NOT NULL)

13:10:42.067 [main] DEBUG RDB2RDFTestBase - Result:
<http://example.com/Student/10> <http://xmlns.com/foaf/0.1/name> "Venus Williams" .
```
Native Query (NullTolerating)
![Status](https://img.shields.io/badge/Test-SUCCESS-green.svg)
```
13:16:14.084 [Thread-4] DEBUG i.u.i.o.a.r.impl.QuestQueryProcessor - Resulting native query:
ans1(s,p,o)
CONSTRUCT [s, p, o] [p/<http://xmlns.com/foaf/0.1/name>, s/RDF(http://example.com/Student/{}(INTToTEXT(ID1m1)),IRI), o/RDF(v0,xsd:string)]
   NATIVE [ID1m1, v0]
SELECT DISTINCT v1.`ID` AS `ID1m1`, ((v1.`FirstName` || ' ') || v1.`LastName`) AS `v0`
FROM `Student` v1
WHERE v1.`ID` IS NOT NULL

13:16:14.102 [main] DEBUG RDB2RDFTestBase - Result:
<http://example.com/Student/10> <http://xmlns.com/foaf/0.1/name> "Venus Williams" .
```

### D014
| Test Case | Test ID | SQL Schema | R2RML Mapping | Expected Output |
|-----------|---------|---------------|--------------------|--------------------|
| [D014](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/) | tc0014a | [create.sql](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/create.sql) | [r2rmla.ttl](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/r2rmla.ttl) |  [mappeda.nq](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/mappeda.nq) |
| [D014](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/) | tc0014b | [create.sql](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/create.sql) | [r2rmlb.ttl](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/r2rmlb.ttl) |  [mappedb.nq](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/mappedb.nq) |
| [D014](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/) | tc0014c | [create.sql](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/create.sql) | [r2rmlc.ttl](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/r2rmlc.ttl) |  [mappedc.nq](https://github.com/ontop/ontop/blob/version5/test/rdb2rdf-compliance/src/test/resources/D014/mappedc.nq) |

Schema
```
13:10:42.303 [main] DEBUG RDB2RDFTestBase - tc0014a CreateDB
CREATE TABLE "DEPT" (
      "deptno" INTEGER UNIQUE,
      "dname" VARCHAR(30),
      "loc" VARCHAR(100));
INSERT INTO "DEPT" ("deptno", "dname", "loc") VALUES (10, 'APPSERVER', 'NEW YORK');

CREATE TABLE "EMP" (
      "empno" INTEGER PRIMARY KEY,
      "ename" VARCHAR(100),
      "job" VARCHAR(30),
	  "deptno" INTEGER REFERENCES "DEPT" ("deptno"),
	  "etype" VARCHAR(30));
INSERT INTO "EMP" ("empno", "ename", "job", "deptno", "etype" ) VALUES (7369, 'SMITH', 'CLERK', 10, 'PART_TIME');

CREATE TABLE "LIKES" (
      "id" INTEGER,
      "likeType" VARCHAR(30),
      "likedObj" VARCHAR(100));
INSERT INTO "LIKES" ("id", "likeType", "likedObj") VALUES (7369, 'Playing', 'Soccer');
INSERT INTO "LIKES" ("id", "likeType", "likedObj") VALUES (7369, 'Watching', 'Basketball');
```

- r2rmla.ttl
```
    rr:logicalTable [ rr:sqlQuery """
       SELECT ('Department' || "deptno") AS "deptId"
            , "deptno"
            , "dname"
            , "loc"
       FROM "DEPT"
       """ ];
```
Expected
```
_:Department10 <http://example.com/dept#location> "NEW YORK" .
```

Native Query (NullRejecting)
![Status](https://img.shields.io/badge/Test-FAILURE-red.svg) Failed - result does not contain `deptId` key (returns bnode)

```
13:10:43.097 [Thread-7] DEBUG i.u.i.o.a.r.impl.QuestQueryProcessor - Resulting native query:
ans1(s,p,o)
CONSTRUCT [s, p, o] [s/RDF(CONCAT2("Department"^^TEXT,deptno1m1),BNODE), p/<http://example.com/dept#location>, o/RDF(VARCHARToTEXT(loc1m1),xsd:string)]
   NATIVE [deptno1m1, loc1m1]
SELECT v1.`deptno` AS `deptno1m1`, v1.`loc` AS `loc1m1`
FROM `DEPT` v1
WHERE (v1.`deptno` IS NOT NULL AND v1.`loc` IS NOT NULL)

13:10:43.115 [main] DEBUG RDB2RDFTestBase - Result:
_:genid300db52b7f901f6a6f97ac3d5834a831f3a2c73c99 <http://example.com/dept#location> "NEW YORK" .
```
Native Query (NullTolerating)
![Status](https://img.shields.io/badge/Test-FAILURE-red.svg) Failed - result does not contain `deptId` key (returns bnode)
```
13:16:15.200 [Thread-7] DEBUG i.u.i.o.a.r.impl.QuestQueryProcessor - Resulting native query:
ans1(s,p,o)
CONSTRUCT [s, p, o] [s/RDF(||2("Department"^^TEXT,deptno1m1),BNODE), p/<http://example.com/dept#location>, o/RDF(VARCHARToTEXT(loc1m1),xsd:string)]
   NATIVE [deptno1m1, loc1m1]
SELECT v1.`deptno` AS `deptno1m1`, v1.`loc` AS `loc1m1`
FROM `DEPT` v1
WHERE v1.`loc` IS NOT NULL

13:16:15.228 [main] DEBUG RDB2RDFTestBase - Result:
_:genid3335b3c40da5c8c8aea86b5e71ea3c6d0c7f1a2124 <http://example.com/dept#location> "NEW YORK" .
```

- r2rmlb.ttl
```
    rr:logicalTable [ rr:sqlQuery """
       SELECT ('Department' || "deptno") AS deptId
            , "deptno"
            , "dname"
            , "loc"
       FROM "DEPT"
       """ ];
```

- r2rmlc.ttl
```
    rr:logicalTable [ rr:sqlQuery """
       Select ('Department' || "deptno") AS deptId
            , "deptno"
            , "dname"
            , "loc"
         from "DEPT"
       """ ];
```
- r2rmld.ttl
```
    rr:logicalTable [ rr:sqlQuery """

        SELECT "EMP".*, (CASE "job"
            WHEN 'CLERK' THEN 'general-office'
            WHEN 'NIGHTGUARD' THEN 'security'
            WHEN 'ENGINEER' THEN 'engineering'
        END) AS ROLE FROM "EMP"

        """ ];
```

**Comment by bcogrel** [comment]
The SQL queries need to be adapted to MySQL, as the `||` operator is not a concat but an OR. 

I already pointed this issue to a benchmarking project based on this test suite:  https://github.com/kg-construct/r2rml-implementation-report/issues/12.
