### ISSUE TITLE
Release ontop for Protege 5.0

### ISSUE THREAD

**Issue by csnyulas** [ontop/ontop#60]
I tried to install ontopPro plug-in (v1.14.0) in Protege 5 and I got the following error:

>ERROR: Bundle it.unibz.krdb.obda.protege4 [10] Error starting file:/opt/Protege-5.0.0-beta-16-LinuxJRE/plugins/it.unibz.inf.obda.p4plugin-1.14.0.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle it.unibz.krdb.obda.protege4 [10]: Unable to resolve 10.0: missing requirement [10.0] osgi.wiring.package; (&(osgi.wiring.package=org.protege.editor.core)(version>=4.3.0)(!(version>=5.0.0))))
>org.osgi.framework.BundleException: Unresolved constraint in bundle it.unibz.krdb.obda.protege4 [10]: Unable to resolve 10.0: missing requirement [10.0] osgi.wiring.package; (&(osgi.wiring.package=org.protege.editor.core)(version>=4.3.0)(!(version>=5.0.0)))
>	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974)
>	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
>	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1291)
>	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
>	at java.lang.Thread.run(Thread.java:745)
>Starting Protege Desktop (Version 5.0.0, Build = beta-16)
>....

Apparently ontopPro is configured to work only with Protege versions starting with 4.3, but less than 5.0.
Is there a good reason for not upgrading it to work with Protege 5.0?

**Comment by ghxiao** [comment]
Hi, 

We actually started to migrate to Protege 5 and we plan to release protege 5 plugin in the next stable release. Currently, there is a branch for protege 5:

https://github.com/ontop/ontop/tree/feature/protege5 

If you are interested,  you can compile the plugin following the instruction in the beginning of https://github.com/ontop/ontop/wiki/ObdalibPluginDebug

Or I can also send you a version we compiled for protege5. 

The reason we did not upgrade to protege 5 is the version number of protege 5 is always with beta, so we were not sure whether it is stable enough.

Cheers,

**Comment by csnyulas** [comment]
Hi Guohui, and thanks for the quick reply.
I am really glad to hear that you have already started working on the migration.

I would really appreciate if you could send me the version you compiled, since I am very busy at the moment. It would be a great thing if I could demonstrate how the plugin works in Protege 5.0 to the Protege Short Course participants in the next few days.

BTW, Protege 5.0, although in officially in beta, is very stable, and has lots of improvements compared to the 4.x series, so definitely worth adapting all the plugins.

Thanks again!

**Comment by ghxiao** [comment]
Hi @csnyulas 

Can you send me an email in private so that I can share my build of protege 5 with you?
My email address is xiao (at) inf.unibz.it
