### ISSUE TITLE
Ontop 5.0.1 connects to mssql error

### ISSUE THREAD

**Issue by JoinJoker** [ontop/ontop#610]
Hello

  After my own test, when I used ontop 5.0.1 to connect mssql 2008, executing the command
 ontop cli./ontop endpoint failed
   org.springframework.beans.factory.BeanCreationException:  Error creating bean with name 'setupVirtualRepository' defined in class path resource  [it/unibz/inf/ontop/endpoint/beans/OntopVirtualRepositoryBean.class]: Bean instantiation via factory method failed;  nested exception is org.springframework.beans.BeanInstantiationException:  Failed to instantiate [it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository]:  Factory method 'setupVirtualRepository' threw exception;  nested exception is org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.MappingIOException:  it.unibz.inf.ontop.exception.MetadataExtractionException: com.microsoft.sqlserver.jdbc.SQLServerException:  Drivers cannot establish a secure connection to SQL Server by using Secure Socket Layer (SSL) encryption. Error: The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]. ClientConnectionId:3f88a7cc-e4ef-4abe-a8eb-9aab447aab87
Perform
. / ontop materialize the command times error Java. Lang. RuntimeException: it. Unibz. J inf. Ontop. Exception. MappingIOException: it.unibz.inf.ontop.exception.MetadataExtractionException: problem with JSON processing.

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'PrefixDeclaration':  was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')

at [Source: (InputStreamReader); line: 2, column: 19]

Is there a solution?

Have a good life!

**Comment by bcogrel** [comment]
Hi,

The JRE you are using probably disable TLS 1.0 by default (see for instance https://aws.amazon.com/blogs/opensource/tls-1-0-1-1-changes-in-openjdk-and-amazon-corretto/).

Regarding the second issue, it looks like you are providing the the OBDA mapping file as argument for the DB metadata parameter.

**Comment by JoinJoker** [comment]
@bcogrel 
Hello!
  Because some people who are willing to need the java environment to be configured to be the jdk 11 version, I use the same configuration file in the jdk 1.8 environment and the same command. When the ontop version is 4.22, there is no such problem. Is it because of the jdk environment configuration?
Wish you a happy life!

**Comment by fracorco** [comment]
Hi @JoinJoker,

according to this [post](https://www.petefreitag.com/item/916.cfm) and this [official page](https://www.java.com/en/jre-jdk-cryptoroadmap.html) (see for 2021-04-20 entry), TLS 1.0 has been disabled by default starting from Java v11.0.11+ as well as Java 1.8.0_291, which means you may encounter the same issue with Ontop 4.2 as soon as you update the Java 8 version used to run it.

The post in the first link explains how to re-enable TLS 1.0, which basically boils down editing file `java.security` of the JDK (either `lib/security/java.security` or `conf/security/java.security`) and therein removing TLS 1.0 out of property `jdk.tls.disabledAlgorithms` (and possibly move it under property `jdk.tls.legacyAlgorithms`, but I don't remember this property being needed at least for Java 8).

If you don't want / cannot edit that JDK file, you may also start the JVM with an alternative `java.security` file: just create a new text file with the content of `java.security` you would like to use, and start the JVM with `-Djava.security.properties=<path_to_created_file>`. With both the Ontop Docker image or the Ontop CLI package, you can pass arbitrary JVM arguments via environment property `ONTOP_JAVA_ARGS`.

HTH

**Comment by JoinJoker** [comment]
@fracorco 
I see. Thank you for your answer
