### ISSUE TITLE
Docker image can't read command line arguments from files

### ISSUE THREAD

**Issue by gpeb2** [ontop/ontop#649]
### Description

The Docker `entrypoint.sh` script uses the bash specific `$(< "${ONTOP_DB_PASSWORD_FILE}")` notation but the shebang path was changed to `/bin/sh` [here](https://github.com/ontop/ontop/commit/149a0786e69e51ca2d7f726f2247ed5fc700a5ad#diff-e70a7161b27a48cc780b54124b68c0e40d946ca406fca49418307fda8b12a594L1).

### Steps to Reproduce

1. Try to run the Docker container with the `ONTOP_DB_PASSWORD_FILE` environment variable set.

**Expected behavior:** Password is read from the file specified by `ONTOP_DB_PASSWORD_FILE`.

**Actual behavior:** No password is read in and the container fails to start

**Reproduces how often:** Whenever the `entrypoint.sh` script tries to read an argument from a file specified by a `_FILE` environment variable.

### Versions

Docker image version 5.0.0+

### Additional Information

Changing the shebang back to `#!/bin/bash` seems to fix the issue.

**Comment by fracorco** [comment]
Thanks for reporting this issue.

The `entrypoint.sh` script was recently revised and at the same time changed from using `bash` to requiring only `sh`, so to facilitate possibly providing a smaller Ontop Docker image based on Alpine where `bash` is missing. Unfortunately I forgot (and did not spot at test time) changing this Bash specific syntax `$(< file)`, which can be correspondingly written as `$(cat file)`.

This [branch](https://github.com/ontop/ontop/compare/bugfix/docker-read-cli-args-from-file) provides an updated `entrypoint.sh` (using `cat`) that addresses this issue. I tested it with `ONTOP_DB_PASSWORD_FILE` and it works. A temporary Docker image for testing this bug fix is available at [`fracorco/ontop-test:5.1.0-SNAPSHOT`](https://hub.docker.com/r/fracorco/ontop-test).

Apologies for the inconvenience.
