### ISSUE TITLE
nubee questions

### ISSUE THREAD

**Issue by wdduncan** [ontop/ontop#69]
Hi,
I've just started using ontop framework. So, I like what I see. I've already started translating some RDB data into an ontology using it. I have some brief questions/issues:
1. Do have an idea of when you might incorporate the use of annotations, such as rdfs:label. I work a lot with OBO Foundry ontologies (http://www.obofoundry.org) which makes heavy use of annotations, such as "definition" and "editor note". Not being able to use annotations is quite limiting.
2. I downloaded the most recent Protege plugin. This works with the latest release of Protege 5. However, do you have plugins that work with older version of Protege? I often work with Protege 4.3.
3. I cloned your git repo. However, I am not entirely clear on how to build the Protege plugin. Do the script "obdalib-protege41-test.sh" build a plugin for Protege 4.1 or does build the most recent version of the plugin?
4. When do you expect the next version of the plugin to be released?
5. I materialized a set of triples using the plugin for Protege 5.0. In this ontology,  I define a class called "patient role" that is used to characterize a person as being a patient. Patient roles are related to people using a "has role" relation. The pattern for mapping the person to the role looks like this:

:person/{person_id} a :person .
:patient_role/{person_id} a :patient_role .
:person/{person_id} :has_role :patient_role/{person_id} .

However, after materializing the triples, the "has role" shows up as an annotation for the individual person. Not as an object property assertion.

Thanks,
Bill

**Comment by ghxiao** [comment]
Dear Bill,

Thanks for your interest!

1. Supporting annotation property is a known issue. We are working on that.

2. The recent versions (v1.15 and v1.16) of Ontop support only Protege 5. The older versions work with Protege 4.  Another possibility is to create Protege 4 plugin by changing the version of Protege dependency in the pom.xml file and compile by yourself. It should work. Btw, why you cannot switch to Protege 5?
   
3. The procedure of building protege plugin is documented here: 
https://github.com/ontop/ontop/wiki/ObdalibPluginDebug. 
Check the first section.

4. We just released 1.16 last week. The next release is not scheduled yet. Normally we release a new version every 3/4 months.

5. Wired. Is "has role" declared as object property in your ontology? If yes, then it sounds like a bug.

**Comment by wdduncan** [comment]
Thanks for your reply. I look into how to build a plugin. In response to your questions:

I still use Protege 4.3 (at times) because I'm not completely convinced that Protege 5 has enough of the bugs worked out. Although, I have to admit that this last release was much better, and I have been using it for the most part.

Your downloads page only shows a download for 1.16 that includes Protege. The version of Protege that I have running on my machine includes a number of other plugins (such as ELK). I assume that I can copy the plugins:

it.unibz.inf.obda.p4plugin-1.16.0.jar
org.protege.osgi.jdbc.jar
org.protege.osgi.jdbc.prefs.jar

from the 1.16 download and place them in my instance of Protege. Right? Or do I only need the it.unibz.inf.obda.p4plugin-1.16.0.jar plugin?

"has role" is defined as an object property in the ontology. So, this may be a bug ...

-- Bill

**Comment by ghxiao** [comment]
> it.unibz.inf.obda.p4plugin-1.16.0.jar
>  org.protege.osgi.jdbc.jar
> org.protege.osgi.jdbc.prefs.jar
> from the 1.16 download and place them in my instance of Protege. Right? Or do I only need the it.unibz.inf.obda.p4plugin-1.16.0.jar plugin?

Yes, you need those three jars. Please note they only work with Protege 5. 

> "has role" is defined as an object property in the ontology. So, this may be a bug ...

We will double check. Thanks for reporting!

**Comment by ghxiao** [comment]
I created a separate issue for annotation property support (#77).
