### ISSUE TITLE
column functions and table aliases in MySQL

### ISSUE THREAD

**Issue by wdduncan** [ontop/ontop#70]
I'm getting some inconsistent behavior regarding the the use of column functions and table aliases with MySQL and ontop. 

Here is the environment:
  OS: OSX Yosemite 10.10.5 
  DB: 5.6.27 MySQL Community Server
  Ontology editor: Protege 5.0.0 (Build beta-17)
  Ontop Protege version: 1.16

In my DB, I have a table named 'demographics' that consists of a STUDY_ID field that identifies each patient. For testing purposes, I do not want to map all the patients into the ontology. Depending on how I set up the SQL query in the mapping, I get different results. 

Setup 1:
Triples template: 
  patient:{STUDY_ID} a obo:OHD_0000012 ; obo:name {label}^^xsd:string . 
SQL query: 
  select STUDY_ID, concat('patient role for patient ', STUDY_ID) as label from (select \* from demographics limit 50) as t1

Setup 2:
Triples template:
  patient:{STUDY_ID} a obo:OHD_0000012 ; obo:name {label}^^xsd:string . 
SQL query:
  select STUDY_ID, patient_name(STUDY_ID) as label from (select \* from demographics limit 50) as t1

The difference between Setup 1 an Setup 2 is that the SQL query for Setup 2 uses the function "patient_name(STUDY_ID)" to create the label rather than "concat('patient role for patient ', STUDY_ID)". There is nothing special about the patient_name function. It does the same thing as concat. Here is the function definition:

FUNCTION `patient_name`(id char(10)) RETURNS varchar(20) CHARSET big5
BEGIN
  declare patient_name varchar(20);
  set patient_name = concat('patient ', id);
RETURN patient_name;
END

For each setup, I run the following SPARQL query:

prefix patient: http://purl.obolibrary.org/obo/OHD_0000012
select ?p where { ?p a patient: . }

When I run the query for Setup 1, it returns all the patients from the demographics table (13,000+ URIs).
When I run the query for Setup 2, it only returns 50 patients, which is the behavior I expected.

-- Bill

**Comment by skomlaebri** [comment]
Hi Bill, 
you indeed found a bug, the limit is ignored at the moment in the query.The problem does not appear in setup2, since we do not support your user created function and we simply generate a view without any optimisation.
For the moment I will suggest you (if the query is simple) to add the limit in the SPARQL query instead of the sql one or to keep using the setup2. We will look into this.
Thanks
Sarah

**Comment by skomlaebri** [comment]
The error does not appear in version 3, a view is generated since limit is not supported in the source part of the mapping.
