### ISSUE TITLE
antlr4-maven-plugin:4.12.0  produces Java sources with illegal unicode escapes under Windows if a package name begins with 'u'

### ISSUE THREAD

**Issue by thomasjtaylor** [ontop/ontop#701]
### Description
ANTLR 4.12.0 produces Java sources with illegal unicode escapes under Windows if a package name begins with 'u'
https://github.com/antlr/antlr4/issues/4128

### Steps to Reproduce
On Windows 10 Pro, Command Line:

`mvn clean install -DskipTests -Prelease -pl :ontop-mapping-core`

**Expected behavior:** [What you expect to see]
Build success without errors

**Actual behavior:** [What actually happens]
Maven build errors:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project ontop-mapping-core: Compilation failure: Compilation failure:
[ERROR] /C:/dev/github/ontop/mapping/core/target/generated-sources/antlr4/it/unibz/inf/ontop/spec/mapping/parser/impl/TurtleOBDABaseVisitor.java:[1,23] illegal unicode escape
[ERROR] /C:/dev/github/ontop/mapping/core/target/generated-sources/antlr4/it/unibz/inf/ontop/spec/mapping/parser/impl/TurtleOBDALexer.java:[1,23] illegal unicode escape
[ERROR] /C:/dev/github/ontop/mapping/core/target/generated-sources/antlr4/it/unibz/inf/ontop/spec/mapping/parser/impl/TurtleOBDAParser.java:[1,23] illegal unicode escape
[ERROR] /C:/dev/github/ontop/mapping/core/target/generated-sources/antlr4/it/unibz/inf/ontop/spec/mapping/parser/impl/TurtleOBDAVisitor.java:[1,23] illegal unicode escape
```

Example Generated Sources:
```
// Generated from it\unibz\inf\ontop\spec\mapping\parser\impl\TurtleOBDA.g4 by ANTLR 4.12.0
package it.unibz.inf.ontop.spec.mapping.parser.impl;
```

**Reproduces how often:** 
Always

### Versions
Ontop: 5.1.0-SNAPSHOT (7/7/2023)
Windows: 10 Pro
Maven: 3.6.2
Java: 13.0.2

### Additional Information

This can be resolved by downgrading the antr4-maven-plugin to 4.11.1

`mvn clean install -DskipTests -Prelease -pl :ontop-mapping-core "-Dantlr4-maven-plugin.version=4.11.1"`

Example Generated Sources:
```
// Generated from java-escape by ANTLR 4.11.1
package it.unibz.inf.ontop.spec.mapping.parser.impl;
```
The ANTLR4 issue indicates this will be fixed in ANTLR 4.13.1 (unreleased). It is still present in the ANTRL 4.13.0 release.

**Comment by bcogrel** [comment]
Hi Thomas, thanks for the detailed report of the issue. 

I suggest waiting for the next version of ANTLR to be released (4.13.1 is still not out).
