### ISSUE TITLE
Issue with URI-decoding (URIs with percent encoded chars cant be used in the SPARQL query, empty results)

### ISSUE THREAD

**Issue by marianormuro** [ontop/ontop#71]
he issue is that the "encoding"/"decoding" of URIs is not done consistently, and returns empty results in queries inolving constant IRI's that need to be decoded by ontop into sql values. 

According to the standards, all values used to generate URIs must be "URI safe' by the mapping processor (using URL encodings, e.g., %20 %21 %22 etc), so if you have the table:

name
-------
Cote D'Ivore

And a mapping

<http://example.com/hotel-{$name}> rdf:type :Hotel
SELECT name FROM mytable

The result for

SELECT * WHERE { ?uri rdf:type :Hotel }

should be something like:

?uri
---------
<http://example.com/hotel-Cote%20D%27Ivore>

Like wise if the system receives a query with a constant that is generated from a mapping like:

SELECT ?type WHERE {
    <http://example.com/hotel-Cote%20D%27Ivore> rdf:type ?type
}

The system should match the URI to a URI template, identify the piece that holds DB values, decode the encoded characters and match them againts the original values. For example:

SELECT ':Hotel' as type FROM mytable WHERE name = 'Cote D'Ivore'

So it can return: 

?type
----
:Hotel

But right now it seems to be generating:

SELECT ':Hotel' as type FROM mytable WHERE name = 'Cote20D27Ivore'

**Comment by ghxiao** [comment]
@marianormuro This bug is already fixed, right? I guess if you want to close it by commit, you have to use "close" instead of "closes" in your commit message.

**Comment by marianormuro** [comment]
argh :S closing now
