### ISSUE TITLE
SQL queries omitting the keyword AS for aliases result in error

### ISSUE THREAD

**Issue by ailintom** [ontop/ontop#743]
Whereas MySQL and MariaDB do not require using the keyword AS for aliases, ontop returns an error, when an alias is not introduced by AS

### Description

Ontop returns the error: 

```
java.lang.RuntimeException: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: The placeholder(s) xxx in the target do(es) not occur in source query of the mapping assertion
```
### Steps to Reproduce

I cannot reproduce this with a simple example, but the problem occurs in a complex R2RML mapping file

**Expected behavior:** 
**Actual behavior:** error: The placeholder(s) id in the target do(es) not occur in source query of the mapping assertion

**Reproduces how often:** sometimes

### Versions

Ontop 5.1.0, MariaDB 10.4.28

**Comment by ghxiao** [comment]
Hi,

You need to enclose the column in {} in the template:

```
rr:template "https://example.com/#{id}" ;
```

**Comment by ailintom** [comment]
I am really sorry; I have complex mappings that fail in ontop unless I add " AS " before aliases. But I cannot yet reproduce this error using simpler mappings as an example.

**Comment by Abhishek1121-tech** [comment]
Any update how to resolve the Alias AS invalid mapping issue, the parsing is not able to suffice to create mapping / RDF. In case of mapping creation used force to create file but when operating to create RDF it's getting failed.

**Comment by bcogrel** [comment]
Could you please give us an example of a failing mapping entry?

**Comment by Abhishek1121-tech** [comment]
Falling mapping entry is below (database is postgres):-
`Problem location: source query of triplesMap
[id: MAPPING-ID28
target atoms: triple(s, p, o) with s/RDF(http://www.w3.org/ns/r2rml/dcim_interface/id={}(TmpToTEXT(dcim_interface_id)),IRI), p/<http://www.w3.org/ns/r2rml/dcim_interface#ref-bridge_id>, o/RDF(http://www.w3.org/ns/r2rml/dcim_interface/id={}(TmpToTEXT(dcim_interface_id)),IRI)
source query: SELECT "dcim_interface"."id" AS "dcim_interface_id", "dcim_interface"."id" AS "dcim_interface_id" FROM "dcim_interface", "dcim_interface" WHERE "dcim_interface"."bridge_id" = "dcim_interface"."id"]`
Attaching log file as well for detail stacking.
[log.log](https://github.com/ontop/ontop/files/13864303/log.log)

**Comment by kontchakov** [comment]
Why is "dcim_interface" repeated twice in the following?

`SELECT "dcim_interface"."id" AS "dcim_interface_id", "dcim_interface"."id" AS "dcim_interface_id" FROM "dcim_interface", "dcim_interface" WHERE "dcim_interface"."bridge_id" = "dcim_interface"."id"`

Is it a self-join? Then one should use something along the lines of 

`SELECT "parent"."id" AS "bridge_dcim_interface_id", "child"."id" AS "dcim_interface_id" FROM "dcim_interface" "parent", "dcim_interface" "child" WHERE "child."bridge_id" = "parent"."id"`

**Comment by Abhishek1121-tech** [comment]
Okay i see, wired but this is getting generated while creating the operation bootstrap within the .obda file. Attaching the file. Renaming not able to upload.
[obda_file.txt](https://github.com/ontop/ontop/files/13864555/obda_file.txt)
[ontology_file.txt](https://github.com/ontop/ontop/files/13864556/ontology_file.txt)

**Comment by bcogrel** [comment]
Should be fixed by now. Thanks for reporting!
