### ISSUE TITLE
Issues computing mappings from relational databases

### ISSUE THREAD

**Issue by ernestojimenezruiz** [ontop/ontop#75]
We have been performing tests with the RODI benchmark and used -ontop- as mapping extractor.

We have found the following issues. The database dumps can be found in the folder folder "data" in https://github.com/chrpin/rodi
1. We could not compute the mappings for the databases mondial_rel and conference_nofks
2. Table name specified twice:

cmt_mixed database:

ERROR: table name "persons" specified more than once

mappingId    MAPPING-ID72
target        http://www.semanticweb.org/cp/ontologies/2015/9/untitled-ontology-25/persons/id={persons_id} http://www.semanticweb.org/cp/ontologies/2015/9/untitled-ontology-25/persons#ref-assigned_by_reviewer http://www.semanticweb.org/cp/ontologies/2015/9/untitled-ontology-25/persons/id={persons_id} .
source        SELECT "persons"."id" AS persons_id, "persons"."id" AS persons_id FROM "persons", "persons" WHERE "persons"."assigned_by_reviewer" = "persons"."id"

We got a similar error in cmt_structured_ci database.

Thanks 
Ernesto

**Comment by ghxiao** [comment]
@ernestojimenezruiz I imported mondial_rel into our postgres server.

I tested bootstrapping mondial_rel using ontop 1.16 from command line. I see two problems:

1. The generated mapping files contain BNode( ... ) which currently is not recognized by the Ontop mapping parser.

2. In your mondial_rel database, there are multi schemas, the generated SQLs do not contain the schema part when referring to a table. Then later ontop cannot find those tables not in the default schema.

The first issue is a known issue and requires more efforts to fix. The second one should be easier to fix.

We will also check how develop branch works and how ontop-bootstrapper behaves on other databases.
