### ISSUE TITLE
Exception when setting up an endpoint with Docker using the command instead of environment variables

### ISSUE THREAD

**Issue by rossbowen** [ontop/ontop#765]
### Description

I'm following the [database and Ontop setup example](https://ontop-vkg.org/tutorial/lenses/setup.html). Upon running the example code with a docker container (and any other code making use of the `endpoint` command), Ontop will complain `ONTOP_MAPPING_FILE` is not set, even if a `--mapping` is provided.

### Steps to Reproduce

```sh
docker run ontop/ontop ontop endpoint \
    --ontology=input/ontology.ttl \
    --mapping=input/mapping.obda \
    --lenses=input/lenses.json \
    --properties=input/duckdb.properties \
    --cors-allowed-origins=http://yasgui.org # if needed
```

The `entrypoint.sh` seems to ignore whether `--mapping` is set.

https://github.com/ontop/ontop/blob/4572e6ba571d2ffb22b30ab4a8d02f2ce9e3e311/client/docker/entrypoint.sh#L47-L51

I recognise the docker container won't have any of the example files in it - but even when I've set it up to have access to those files, it throws and error about a missing environmental var.

**Expected behaviour:**
Expected the CLI to recognise the `--mapping` option.

**Actual behaviour:**

> ```ERROR: environment variable ONTOP_MAPPING_FILE is not set```

**Reproduces how often:**

Happens every time.

### Versions

Running off the latest docker image, which looks like ontop [5.1.0](https://hub.docker.com/layers/ontop/ontop/5.1.0/images/sha256-cd54901391524d1d689336e7c57d30ea787b985ead5f7b2aa6dae47c45c77c7b?context=explore).

**Comment by bcogrel** [comment]
Hi @rossbowen, thanks for reporting the issue.

To start Ontop as an endpoint, you don't need to specify a command. All the parameters can be passed as environment variables.

See for instance https://github.com/ontopic-vkg/destination-tutorial/blob/master/docker-compose.solution.yml#L19.

Best,
Benjamin
