### ISSUE TITLE
Connection test in Ontop-Protégé may wrongly say OK for Trino

### ISSUE THREAD

**Issue by bcogrel** [ontop/ontop#766]
Experienced in https://github.com/ontop/ontop/discussions/762

**Comment by bcogrel** [comment]
Bug reproduced: the Trino driver returns a Connection object (not null) even if the connection URL is invalid.
Moreover, method `Connection.isValid(timeout)` also returns true immediately, without establishing a connection.

**Comment by kontchakov** [comment]
Fixed in <https://github.com/ontop/ontop/pull/767>
