### ISSUE TITLE
With Trino, uppercase characters in columns and the table name are not supported by Ontop

### ISSUE THREAD

**Issue by BorderCloud** [ontop/ontop#773]
### Description

My Trino  query (on Mongo)  is:
`Select myField FROM mycollection`

But I have this error via Ontop when I import the r2rml: `An error occurred during reasoning: Error: Unable to find attribute myField (available attributes are [..."mongo"."mydb"."mycollection"."myfield",...]) (from myField)`

So, I have to modify the query like that to work:
`Select myfield FROM mycollection`

An idea? It's a bug?

**Comment by bcogrel** [comment]
Hi, have you tried with double quotes?

```sql
Select "myField" FROM mycollection
```
The current Ontop adapter treats the identifiers as case-sensitive

**Comment by BorderCloud** [comment]
> Hi, have you tried with double quotes?
> 
> ```sql
> Select "myField" FROM mycollection
> ```
  Yes, I see there is also a problem with the upper case in the name of collections

You can reproduce with trino/mongo:

etc/catalog/mongo.properties
```
connector.name=mongodb
mongodb.connection-url=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/
mongodb.case-insensitive-name-matching=true
```

In Mongo, you can create the collection "Test_table":
```
{
  "_id": {
    "$oid": "653ea881d25d8b67f9308008"
  },
  "testCol": "test"
}
```

In the file r2rml:
```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

[ a                      rr:TriplesMap ;
  rdfs:label "test" ;
  rr:logicalTable        [ rr:sqlQuery '''
SELECT 
  "testCol"
FROM "TEST_table"
''' ] ;
  rr:subjectMap          [ rr:template  "http://example.com/test1" ;
                           rr:graph <http://example.com/tests> ] ;

  rr:predicateObjectMap  [ rr:object        <http://example.com/Test> ;
                           rr:predicate     rdf:type ] ;

  rr:predicateObjectMap  [ rr:objectMap    [ rr:column  "\"testCol\"" ; rr:datatype  xsd:string ] ;
                           rr:predicate     :testCol ] ;
] .
```
Error with the name of the collection:
```
Caused by: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: Error: Cannot find relation "mongo"."test"."TEST_table" (available choices: [ "mongo"."test"."test_table") (from "TEST_table")
Problem location: source query of triplesMap
```
Same result with:
```
SELECT 
  testCol
FROM TEST_table
```

**Comment by bcogrel** [comment]
We fixed Ontop's adapter for Trino to treat table and column names as case-insensitive (https://github.com/ontop/ontop/commit/7b2e7b6a9f2d46de65d17e28b0a2b881ae1d9b9a).

Could you please give a try to the new RC release  https://github.com/ontop/ontop/releases/tag/5.1.1-rc3 ?

In principle SQL queries accepted by Trino should also work with Ontop.

**Comment by BorderCloud** [comment]
@bcogrel I tested. It works, now. Thanks.
