### ISSUE TITLE
Error in SQL Syntax

### ISSUE THREAD

**Issue by robertoshimizu** [ontop/ontop#776]
### Description

I have been following the university tutorial, after mapping it succesfully in protege/ontop, when trying the first sparql query below it threw an error. (Noticed that I had to eliminate double quotes in the SQL mapping for each case, exemple you proposed `SELECT *
FROM "uni1"."academic"` )
```
PREFIX : <http://example.org/voc#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?prof ?lastName {
  ?prof a :FullProfessor ; foaf:lastName ?lastName .
}
```
it does not run. There is a error:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'prof,lastName) CONSTRUCT [prof, lastName] [lastName/RDF(VARCHARToTEXT(last_name' at line 1
```
I suspect in the SQL translation is the error, since it also add double quotes in the syntax.

```
ans1(prof,lastName)
CONSTRUCT [prof, lastName] [lastName/RDF(VARCHARToTEXT(last_name2m7),xsd:string), prof/RDF(http://example.org/voc#uni1/academic/{}(INTToTEXT(a_id1m16)),IRI)]
   NATIVE [a_id1m16, last_name2m7]
SELECT v1."a_id" AS "a_id1m16", v1."last_name" AS "last_name2m7"
FROM "uni1"."academic" v1
WHERE 1 = v1."position"
```

I am using `mysql` with jdbc driver 8.2.0, protege 5.6.1 and Ontop 5.1.0

Thanks
Roberto Shimizu

### Attached material

Informations about the attachments (ontology, mappings and queries that are necessary to reproduce the problem)
Provide the log file (more information on how to obtain it in the guidelines)

### Versions

Which version of Ontop are you using and in which setting (Protege, SPARQL endpoint, Cli, Java API, ...)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by bcogrel** [comment]
Hi Roberto,

You need to use conventions of the dialect (MySQL) in the SQL queries of the mapping. The quoting character in MySQL is the backtit, not the double quote.

Please give a try to
```sql
SELECT * FROM `uni1`.`academic`
```

Best,
Benjamin

**Comment by robertoshimizu** [comment]
It worked fine.
Thank you Benjamin!
