### ISSUE TITLE
Upgrade to JQuery version 3.5.0 or later

### ISSUE THREAD

**Issue by robertd** [ontop/ontop#780]
### Description

JQuery 3.4.1 has known XSS vulnerabilities. Our scanning  software is picking it up and we are unable to publish the ontop container.

Can this get updated to the latest version, and perhaps we should use CDN instead of shipping JQuery assets directly.

### Versions

5.1.0

### Additional Information

<img width="1509" alt="image" src="https://github.com/ontop/ontop/assets/31543/4b8cdb71-1357-4e3d-8408-b72ba96c40e7">

**Comment by robertd** [comment]
On a related note, `ONTOP_DISABLE_PORTAL_PAGE` doesn't really disable SPARQL editor page.

**Comment by skomlaebri** [comment]
Hi @robertd,
we are updating jQuery to version 3.5

> On a related note, `ONTOP_DISABLE_PORTAL_PAGE` doesn't really disable SPARQL editor page.

the command ONTOP_DISABLE_PORTAL_PAGE, if set to true, disables the Ontop portal so that you cannot access it on the default port 8080 (or the chosen port).
However, it does not exclude the files from the building step, so the vulnerability issue remains. Is that the issue you were referring to?

**Comment by robertd** [comment]
> Hi @robertd, we are updating jQuery to version 3.5
> 
> > On a related note, `ONTOP_DISABLE_PORTAL_PAGE` doesn't really disable SPARQL editor page.
> 
> the command ONTOP_DISABLE_PORTAL_PAGE, if set to true, disables the Ontop portal so that you cannot access it on the default port 8080 (or the chosen port). However, it does not exclude the files from the building step, so the vulnerability issue remains. Is that the issue you were referring to?

Setting the `ONTOP_DISABLE_PORTAL_PAGE` variable didn’t disable the portal page for me. SPARQL editor is still active and can be accessed with this env variable set to `true`.

**Comment by bcogrel** [comment]
Hi @robertd, I just merged Sarah's PR. Please give a try to the latest snapshot: [5.2.0-SNAPSHOT](https://hub.docker.com/layers/ontop/ontop/5.2.0-SNAPSHOT/images/sha256-c5b553ae9dfbd22e81953e922a58ef8c42c9f1f5163d318c8c4f211b76b2f07f?context=explore).

`ONTOP_DISABLE_PORTAL_PAGE: "true"` in my Docker compose file worked fine with me with that version. No portal page is shown (`/` and `/portal` return a 404 error).

**Comment by bcogrel** [comment]
We don't have agreed on a date yet. Likely at the end of Q1.

**Comment by bcogrel** [comment]
Hi @robertd , we backported the JQuery fix to 5.1 and just released 5.1.2.
