### ISSUE TITLE
SPARQL query doesnt return any results after changing the mappings

### ISSUE THREAD

**Issue by batoulhaydar** [ontop/ontop#789]
I have created a mapping where when the SQL is executed I get the attribute target. It is not available explicitly in the database. The SQL works fine, but when I want to query it using SPARQL, I don't get any results and the query keeps running.

**Comment by batoulhaydar** [comment]
This is the SQL :
SELECT
pipe.idcana,
node.idouvrage
FROM
croquis.wastewatercanalisation pipe
JOIN
croquis.wastewaterregard node ON ST_Equals(ST_StartPoint(pipe.geom), node.geom);

**Comment by apano-on** [comment]
Does the same SQL query above run fine in your database query editor but the very same translation via Ontop does not? Could you please tell us more i.e. confirm the translation is identical, by setting the logs at the debug level?

- On Docker, set the environment variable ONTOP_DEBUG
- With the CLI, set the error level to DEBUG in the file log/logback.xml

In particular it would be useful to check what the SQL translation is compared to your expected translation. 

Moreover, it looks like you are running a geospatial query. What database are you using: PostgreSQL + PostGIS? Have you added spatial indexes to your geometry columns?

**Comment by apano-on** [comment]
It depends on your SPARQL query. If you are only using one mapping with indexes and keys are defined correctly, the time should be the same. Can you check what is the SQL translation of your SPARQL query through the logs? Could it be different compared to your expected SQL translation?

For optimally designed mappings query execution time should be the same.

**Comment by batoulhaydar** [comment]
This is the SQL translation, I think it is the same. The SPARQLis using only one mapping and the time difference is really big.
ans1(pipe, initial)
CONSTRUCT [initial, pipe] [initial/RDF(http://www.starwars.com/UrbanWaterOntology#croquis/wastewaterregard/{}(VARCHARToTEXT(idouvrage1m33)),IRI), pipe/RDF(http://www.starwars.com/UrbanWaterOntology#croquis/wastewatercanalisation/{}(VARCHARToTEXT(idcana6m1)),IRI)]
   NATIVE [idcana6m1, idouvrage1m33]
SELECT DISTINCT v1."idcana" AS "idcana6m1", v2."idouvrage" AS "idouvrage1m33"
FROM "croquis"."wastewatercanalisation" v1, "croquis"."wastewaterregard" v2
WHERE (v1."idcana" IS NOT NULL AND ST_EQUALS(ST_STARTPOINT(v1."geom"),v2."geom") AND v2."idouvrage" IS NOT NULL)

**Comment by apano-on** [comment]
The important difference which is causing the slow performance is the presence of the _DISTINCT_ clause which is introduced by Ontop to the SQL translation to ensure the RDF triples are unique.

You need to ensure that the appropriate primary and foreign keys are present in your database so that Ontop knows not to introduce a DISTINCT.

Are idcana and idouvrage unique? If so defining them as PKs/UNIQUE in your database should resolve the issue. Then you can double check whether the DISTINCT clause is removed. Otherwise the DISTINCT clause remains indispensable.

**Comment by batoulhaydar** [comment]
Thank you for the help. This is the new SQL translation after defining them as UNIQUE:
ans1(pipe, initial)
CONSTRUCT [initial, pipe] [initial/RDF(http://www.starwars.com/UrbanWaterOntology#croquis/wastewaterregard/{}(VARCHARToTEXT(idouvrage1m33)),IRI), pipe/RDF(http://www.starwars.com/UrbanWaterOntology#croquis/wastewatercanalisation/{}(VARCHARToTEXT(idcana1m1)),IRI)]
   NATIVE [geom1m1, geom2m1, idcana1m1, idouvrage1m33, typeregard1m33]
SELECT v2."geom" AS "geom1m1", v1."geom" AS "geom2m1", v2."idcana" AS "idcana1m1", v1."idouvrage" AS "idouvrage1m33", v1."typeregard" AS "typeregard1m33"
FROM "croquis"."wastewaterregard" v1, "croquis"."wastewatercanalisation" v2
WHERE ((v1."typeregard" = 'Regard' OR v1."typeregard" = 'Regard Grille' OR v1."typeregard" = 'Fictif') AND v2."idcana" IS NOT NULL AND ST_EQUALS(ST_STARTPOINT(v2."geom"),v1."geom") AND v1."idouvrage" IS NOT NULL)

Still the time for SPARQL query times 3 of the time of SQL in the database.

**Comment by batoulhaydar** [comment]
I tried to optimize the SQL and rewrite it since it would be faster. It worked on the database, but when I run the SPARQL I get the error:
org.postgresql.util.PSQLException:ERROR:syntax error at or near ";"
Position :343 

SELECT
    pipe.idcana,
    node.idouvrage
FROM
    croquis.wastewatercanalisation pipe
JOIN
    croquis.wastewaterregard node
ON
    ST_DWithin(ST_StartPoint(pipe.geom), node.geom, 0);

**Comment by batoulhaydar** [comment]
I used     ST_AsText(ST_StartPoint(pipe.geom)) = ST_AsText(node.geom); instead of ST_Equals and it is much better for both SQL and SPARQL

**Comment by kontchakov** [comment]
If `idcana` and `idouvrage` cannot contain `NULL`, then they should also be made non-nullable in the database. That would simplify the generated SQL query.

**Comment by batoulhaydar** [comment]
Will do thank you.

Another question is regarding Geosparql, Can you please tell me what's could be wrong with this geosparql. I am getting empty results.

SELECT ?node
WHERE {
  ?node a :Manhole ;
        :hasGeometry ?nodeGeom .
  ?pipe a :Pipe ;
        :hasGeometry ?pipeGeom .
  FILTER(geof:sfIntersects(?nodeGeom, ?pipeGeom))
  }
