### ISSUE TITLE
Can I use GeoSPARQL functions if I defined hasGeometry?

### ISSUE THREAD

**Issue by batoulhaydar** [ontop/ontop#790]
I created a domain ontology and I defined a data property hasGeometry. I want to use this property to execute GeoSPARQL queries however I didn't import the GeoSPARQL ontology. Can I use geosparql functions such as geof:sfWithin in this case?
I am still new to all this stuff :).

**Comment by ghxiao** [comment]
Hi, you don't have to import the GeoSPARQL ontology, although it is a good practice and strongly recommended. 
What is important is to map the geometries into the WKT literals.

Please look at this tutorial where we have extensively used GeoSPARQL functions.
https://github.com/ontopic-vkg/destination-tutorial

In particular, this is the mapping file
https://github.com/ontopic-vkg/destination-tutorial/blob/master/vkg/dest-solution.obda

**Comment by batoulhaydar** [comment]
I tried using geo:asWKT in the query, but it didn't work. Below is the query:

SELECT ?node ?wkt
WHERE {

   ?node a :Manhole .
   ?node :hasGeometry ?geometry.
   ?geometry geo:asWKT ?wkt .
  
}
I then used ST_AsText(geom) in the SQL mapping. But still, when I try to use any GeoSPARQL function I get empty results.

**Comment by ghxiao** [comment]
Does this query work? Can you show some results (can be anonymized)?

```
SELECT ?node ?wkt
WHERE {
?node a :Manhole .
?node :hasGeometry ?geometry.
?geometry geo:asWKT ?wkt .
}
```

**Comment by batoulhaydar** [comment]
It shows empty results.
ans1(node, wkt)
EMPTY [node, wkt]

**Comment by batoulhaydar** [comment]
What is the problem here, haven't figured it out yet.

**Comment by batoulhaydar** [comment]
I didn't use the GeoSparql :hasGeometry because it is a data property in my ontology. So I imported :asWKT instead. 
Target: 
:croquis/wastewatercanalisation/{idcana} a :SewerPipe ; geo:asWKT {wkt}^^geo:wktLiteral . 
Source:
SELECT  ST_AsText(geom) AS wkt
FROM croquis.wastewatercanalisation;
It works fine this SQL, however when I try to use GeoSparql function such as :
`SELECT ?pipe1 ?pipe2
WHERE {
  ?pipe1 a :Pipe;
         geo:asWKT ?geom1.

  ?pipe2 a :Pipe;
         geo:asWKT ?geom2.
  

  FILTER(?pipe1 != ?pipe2)
  FILTER(geof:sfCrosses(?geom1, ?geom2))
}`
I receive this error message
Caused by: it.unibz.inf.ontop.exception.OntopUnsupportedKGQueryException: The expression FunctionCall (http://www.opengis.net/def/function/geosparql/#sfCrosses)
   Var (name=geom1)
   Var (name=geom2)
 is not supported yet!
	... 21 common frames omitted

**Comment by apano-on** [comment]
There seems to be an issue with your IRI namespace prefixes. The namespace prefix for geof should be
```http://www.opengis.net/def/function/geosparql/```
as per https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_namespaces

Therefore the FunctionCall should not be ```http://www.opengis.net/def/function/geosparql/#sfCrosses``` but ```http://www.opengis.net/def/function/geosparql/sfCrosses```, otherwise Ontop will not recognize it.

**Comment by batoulhaydar** [comment]
Thank you so much, this solved the issue.
