### ISSUE TITLE
SPARQL Query Transformation to SQL for N-columns results in N-1 Self Joins or Left Joins, Extremely Slow Query Performance

### ISSUE THREAD

**Issue by thomasjtaylor** [ontop/ontop#800]
### Description

I have a Microsoft SQL Server table with 117 columns - 2 key columns. 

As I add more columns, Ontop adds self-joins for each non-key column, resulting in 115 self joins if I include all columns.

With OPTIONAL variables, Ontop adds LEFT JOINS for each non-key column, resulting in 115 left joins if I include all columns.

A simple query on a database with 100,000 rows for all columns takes 5 minutes in Ontop. Using direct SQL, query takes 10 seconds.

### Steps to Reproduce

1. Deploy [mssql-vw-database.txt](https://github.com/ontop/ontop/files/14965309/mssql-vw-database.txt) to Microsoft SQL Server.
2. Generate a R2RML Mapping [mssql-vw-mapping-pretty.txt](https://github.com/ontop/ontop/files/14965311/mssql-vw-mapping-pretty.txt)
3. Generate RDF/XML Ontology `mssql-vw-ontology.rdf`
4. Execute a query using multiple non-key columns
### Example SPARQL query:

```sparql
SELECT  (?vw2_1_iD AS ?ID) (?vw2_1_iD2 AS ?ID2) (?vw2_1_col1 AS ?col1) (?vw2_1_col2 AS ?col2) (?vw2_1_col3 AS ?col3) (?vw2_1_col4 AS ?col4)
FROM <http://rdb/vw>
WHERE
  { ?_cls_vw2  a                    <http://rdb/vw2> ;
              <http://rdb/vw2#ID>   ?vw2_1_iD ;
              <http://rdb/vw2#ID2>  ?vw2_1_iD2 ;
              <http://rdb/vw2#col1>  ?vw2_1_col1 ;
              <http://rdb/vw2#col2>  ?vw2_1_col2 ;
              <http://rdb/vw2#col3>  ?vw2_1_col3 ;
              <http://rdb/vw2#col4>  ?vw2_1_col4
  }
```

**Expected behavior:** 

### Simple SQL SELECT query

```sql
SELECT ID, ID2, col1, col2, col3, col4
FROM vw2;
```

**Actual behavior:** 

### Complex SQL SELECT with multiple self joins:
```sql
SELECT DISTINCT v1."ID" AS "ID1m137", v1."ID2" AS "ID21m137", v1."col1" AS "col11m93", v2."col2" AS "col21m91", v3."col3" AS "col31m96", v4."col4" AS "col41m95"
FROM "vw2" v1, "vw2" v2, "vw2" v3, "vw2" v4
WHERE (v1."col1" IS NOT NULL AND v2."col2" IS NOT NULL AND v3."col3" IS NOT NULL AND v4."col4" IS NOT NULL AND v1."ID" = v2."ID" AND v1."ID2" = v2."ID2" AND v1."ID" = v3."ID" AND v1."ID2" = v3."ID2" AND v1."ID" = v4."ID" AND v1."ID2" = v4."ID2")
```

 ### Or, if using SPARQL Optionals:
```sql
SELECT DISTINCT v2."col1" AS "col11m93", v3."col2" AS "col21m91", v4."col3" AS "col31m96", v1."ID" AS "v1", v1."ID2" AS "v11"
FROM "vw2" v1
 LEFT OUTER JOIN
"vw2" v2 ON (v2."col1" IS NOT NULL AND v1."ID" = v2."ID" AND v1."ID2" = v2."ID2")
 LEFT OUTER JOIN
"vw2" v3 ON (v3."col2" IS NOT NULL AND v1."ID" = v3."ID" AND v1."ID2" = v3."ID2")
 LEFT OUTER JOIN
"vw2" v4 ON (v4."col3" IS NOT NULL AND v1."ID" = v4."ID" AND v1."ID2" = v4."ID2")
```

**Reproduces how often:** 

Always

### Attached material

DDL to create MSSQL Database (.SQL):
[mssql-vw-database.txt](https://github.com/ontop/ontop/files/14965309/mssql-vw-database.txt)

R2RML Mapping (.TTL):
[mssql-vw-mapping-pretty.txt](https://github.com/ontop/ontop/files/14965311/mssql-vw-mapping-pretty.txt)

Ontop Query Execution Log: (6 columns)
[mssql-vw-query-log-6col.txt](https://github.com/ontop/ontop/files/14965312/mssql-vw-query-log-6col.txt)

Ontop Query Execution Log (5 columns, with OPTIONAL):
[mssql-vw-query-log-5col-optionals.txt](https://github.com/ontop/ontop/files/14965315/mssql-vw-query-log-5col-optionals.txt)

### Versions

5.2.0-SNAPSHOT (built 3/10/2024)

**Comment by bcogrel** [comment]
Hi @thomasjtaylor, this is the expected behaviour in the absence of unique constraints. Most optimization techniques cannot be applied and the left joins and the distincts remain. 

See for instance https://ontop-vkg.org/tutorial/mapping/primary-keys (with inner joins instead of left joins).

I suggest adding unique constraints to your DDL or, if it is not possible, using a [basic lens](https://ontop-vkg.org/guide/advanced/lenses.html#basiclens) to do so.

**Comment by thomasjtaylor** [comment]
Thank you @bcogrel 

To clarify, there's nothing I can do in the R2RML/ODBA mapping file, I either need to modify the underlying database to add unique constraints to the table, or provide a LENS defining the unique constraint.

For a lens, would this be the _minimum_ information I would need to provide for a single table?
```
"relations": [
  {
    "name": "vw2_lense",
    "baseRelation": "\"dbo\".\"vw2\"",
    "uniqueConstraints": {
      "added": [
        {
          "name": "vw2_key",
          "determinants": [ "\"ID\"", "\"ID2\"" ]
        }
    ]
  }
]
```

Would there be any problem if the lens duplicated a `uniqueConstraint` that already exists in the database? (or was added later by a DBA)

I understand that a lens may also specify `foreignKeys`. Does Ontop perform any optimizations with these relationships? For example, if I queried:

```
SELECT v1.*, v2.*
FROM vw1 v1, vw2.v2
WHERE v1.ID = v2.ID
```

Would there be any advantage to creating a `foreignKey` in the lens for the relationship between `vw1` and `vw2`? (presuming `vw1` also has a lens with `uniqueConstraints` for `vw1.ID`)

**Comment by bcogrel** [comment]
You need to add the entry `"type": "BasicLens"` to your lens, otherwise it looks good.

In principle duplication of unique constraint should not cause any problem. If it does, just let us know, that would be a bug.

Yes, foreign keys are important as well for optimizing. They are used for removing unions in the mapping (after saturating it using the ontology), for reducing left joins into inner joins and eliminating inner joins. In your example, the inner join will indeed be eliminated thanks to the foreign key.

**Comment by thomasjtaylor** [comment]
@bcogrel when I add unique constraints directly to the tables, Ontop removes the self/left joins.

However, I can't seem to get the Ontop Lens to work correctly (on tables with no keys)... it is still running the query with multiple self joins.

### Ontop Lens
[mssql-vw-lens.json](https://github.com/ontop/ontop/files/14969501/mssql-vw-lens.json)
```json
{
  "relations": [
    {
      "baseRelation": [
        "[dbo]",
        "[vw2]"
      ],
      "foreignKeys": {
        "added": [
          {
            "from": [
              "[ID]"
            ],
            "name": "vw1",
            "to": {
              "columns": [
                "[ID]"
              ],
              "relation": [
                "[dbo]",
                "[vw1]"
              ]
            }
          }
        ]
      },
      "name": [
        "lenses",
        "dbo",
        "vw2"
      ],
      "type": "BasicLens",
      "uniqueConstraints": {
        "added": [
          {
            "determinants": [
              "[ID]",
              "[ID2]"
            ],
            "name": "ID_ID2"
          }
        ]
      }
    },
    {
      "baseRelation": [
        "[dbo]",
        "[vw1]"
      ],
      "name": [
        "lenses",
        "dbo",
        "vw1"
      ],
      "type": "BasicLens",
      "uniqueConstraints": {
        "added": [
          {
            "determinants": [
              "[ID]"
            ],
            "name": "ID"
          }
        ]
      }
    }
  ]
}
```

### Ontop Query Execution Log
[mssql-vw-lens-query-log-4col.txt](https://github.com/ontop/ontop/files/14969512/mssql-vw-lens-query-log-4col.txt)
```sparql
SELECT  (?vw2_1_iD AS ?ID) (?vw2_1_iD2 AS ?ID2) (?vw2_1_col1 AS ?col1) (?vw2_1_col2 AS ?col2)
FROM <http://rdb/vw>
WHERE
  { ?_cls_vw2  a                    <http://rdb//vw2> ;
              <http://rdb//vw2#ID>  ?vw2_1_iD ;
              <http://rdb//vw2#ID2>  ?vw2_1_iD2
    OPTIONAL
      { ?_cls_vw2  <http://rdb//vw2#col1>  ?vw2_1_col1}
    OPTIONAL
      { ?_cls_vw2  <http://rdb//vw2#col2>  ?vw2_1_col2}
  }
```
```sql
SELECT DISTINCT v1."ID" AS "ID1m275", v1."ID2" AS "ID21m275", v2."col1" AS "col11m179", v3."col2" AS "col21m178"
FROM "vw2" v1
 LEFT OUTER JOIN 
"vw2" v2 ON (v2."col1" IS NOT NULL AND v1."ID" = v2."ID" AND v1."ID2" = v2."ID2") 
 LEFT OUTER JOIN 
"vw2" v3 ON (v3."col2" IS NOT NULL AND v1."ID" = v3."ID" AND v1."ID2" = v3."ID2") 
```

**Comment by bcogrel** [comment]
@thomasjtaylor, the mapping needs to be adapted to point to the lenses instead of the database tables.

Recording quoting, double-quotes should work fine with SQL Server. I haven't tested recently squared brackets, but I guess they work too. Anyway, Ontop should throw an exception if no table or column matches.

**Comment by thomasjtaylor** [comment]
I had thought Ontop would use the Lens `baseRelation` to add the `uniqueConstraints` to the underlying table when planning the query.

I've updated the R2RML Mapping `mssql-vw-mapping.ttl` to replace: `rr:tableName "\"dbo\""."\"vw1\""` with: `rr:tableName "\"lenses\""."\"vw1\""`, (the matches the `relations/name` value in the Lens) but the Ontop configuration fails to load with the below Exception.

It seems I'm missing something in the documentation, examples, and tutorials to get this working.

```
 it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: Error: Cannot find relation "mssql_vw"."lenses"."vw2" (available choices: ["mssql_vw"."dbo"."vw1", "mssql_vw"."dbo"."vw2"]) (from "lenses"."vw2") 
Problem location: source query of triplesMap 
[id: mapping-1570583125
target atoms: triple(s, p, o) with s/RDF(urn://rdb/vw2/ID={};ID2={}(TmpToNVARCHAR("ID"),TmpToNVARCHAR("ID2")),IRI), p/<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, o/<urn://rdb/vw2>, quad(s, p, o, g) with s/RDF(urn://rdb/vw2/ID={};ID2={}(TmpToNVARCHAR("ID"),TmpToNVARCHAR("ID2")),IRI), p/<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, o/<urn://rdb/vw2>, g/<http://rdb/vw>,
...
source query: SELECT * FROM "lenses"."vw2"]
	at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.getRAExpression(SQLPPMappingConverterImpl.java:162) ~[ontop-mapping-sql-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:64) ~[ontop-mapping-sql-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:248) ~[ontop-mapping-sql-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:219) ~[ontop-mapping-sql-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:188) ~[ontop-mapping-sql-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:153) ~[ontop-mapping-sql-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:108) ~[ontop-mapping-sql-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:51) ~[ontop-mapping-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:140) ~[ontop-mapping-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:93) ~[ontop-mapping-sql-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:55) ~[ontop-mapping-sql-all-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:42) ~[ontop-system-sql-owlapi-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44) ~[ontop-obda-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20) ~[ontop-system-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository.initializeInternal(OntopVirtualRepository.java:72) ~[ontop-rdf4j-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
```

**Comment by thomasjtaylor** [comment]
@bcogrel for the Lens `foreignKeys`, does the `to` also need to refer to the Lens relation if it is defined?

I currently have:
```json
"to": {
  "columns": [
    "\"ID\""
  ],
  "relation": [
-    "\"dbo\"",
    "\"vw1\""
  ]
```
but I'm thinking I also need to change it to:
```json
"to": {
  "columns": [
    "\"ID\""
  ],
  "relation": [
+   "\"lenses\"",
    "\"vw1\""
  ]
```
I haven't yet tested the query optimization across object properties.

**Comment by bcogrel** [comment]
@thomasjtaylor, yes it is probably better to have it pointing to the lens as a general practice.

Ontop has a mechanism for inheriting foreign keys defined over the base relations to the lenses, which may be active in your case. So changing the target of the foreign key may not make any difference here, but this needs to be tested.

**Comment by thomasjtaylor** [comment]
Thanks @bcogrel my question/issue has been resolved. I will do some tests with the foreign keys and if I find anything, I'll open a new issue for it.
