### ISSUE TITLE
update link to `ofn` functions

### ISSUE THREAD

**Issue by VladimirAlexiev** [ontop/ontop#806]
https://ontop-vkg.org/guide/compliance.html#time-functions links to 
https://graphdb.ontotext.com/documentation/10.0/devhub/time-functions.html#durations-expressed-in-certain-units.
Can you please update this link to
https://graphdb.ontotext.com/documentation/10.6/sparql-ext-functions-reference.html#date-and-time-function-extensions

Thanks! (If you point me to the documentation source, I'll submit a PR)

**Comment by bcogrel** [comment]
Thanks @VladimirAlexiev ! I updated it. 

For editing the documentation source, there is a link at the bottom of page called `Edit this page`, which brings you directly to the right page to edit.
