### ISSUE TITLE
Incorrect time zone format in xsd:dateTime for Redshift's TIMESTAMP data type

### ISSUE THREAD

**Issue by jindrichmynarz** [ontop/ontop#807]
Ontop 5.1.2 produces syntactically invalid [`xsd:dateTime`](https://www.w3.org/TR/xmlschema11-2/#dateTime) literals from Redshift's [`TIMESTAMP`](https://docs.aws.amazon.com/redshift/latest/dg/c_Supported_data_types.html) data type. 

Ontop maps the timestamp `1984-03-28 00:00:00.0` to `"1984-03-28T00:00:00+00"^^xsd:dateTime`. The [time zone fragment](https://www.w3.org/TR/xmlschema11-2/#nt-tzFrag) of this literal is invalid. The syntactically correct literal is `"1984-03-28T00:00:00+00:00"^^xsd:dateTime`.

**Comment by bcogrel** [comment]
Thanks @jindrichmynarz for reporting the issue. We faced a similar issue with DuckDB recently, where we had to use a regexp_replace to add the minutes of the time zone when they were implicitly 00.

See the changes on the  class `DuckDBDBFunctionSymbolFactory` in the commit [6216b5](https://github.com/ontop/ontop/commit/6216b518f37425a670ec29f4a02fd409e1b8c9f8#diff-568a55c786120e3fab4dc84daf245e7de2e4e91bd9a58749eac6bdf1e0725333)

**Comment by bcogrel** [comment]
Fixed by https://github.com/ontop/ontop/tree/bugfix/order-by-values
