### ISSUE TITLE
URI in string value replaced with prefix

### ISSUE THREAD

**Issue by daghovland** [ontop/ontop#81]
Hi!

If you in a mapping put a string into a data value that has a substring which happens to be one of the defined prefixes, then this is replaced with the prefix.

For example:

target        :Wellbore-{WELLBORE_ID} :wikiURL {wikiURL} .
source        select 'http://example.com/resource/?repository=repo&uri=http://www.example2.org/ontology/stuff/Wellbore-' || WELLBORE_ID as wikiURL, WELLBORE_ID from WELLBORE

In the ontology, : is a prefix for http://www.example2.org/ontology/stuff and in the results when you ask for wikiURL this is replaced. For the intended use, this doesn't work, since the string is supposed to become a web address, and this prefix is not defined or doesn't work at the web server.

This probably only happens in weird cases that it might be ok not to support. But it's probably not correct.

Cheers,

Dag

**Comment by skomlaebri** [comment]
Fixed in e50e8dc1a6f0c1ac23793a2fc23241d12a25765d
