### ISSUE TITLE
Ontop can only materialize one Triplesmap out of a mapping file

### ISSUE THREAD

**Issue by remiColletGG** [ontop/ontop#813]
### Description

When I have a file with multiple rr:TriplesMap in it, ontop only materializes the first one.

### Steps to Reproduce

1. Have test.r2rml.ttl file :
```
@prefix rr:     <http://www.w3.org/ns/r2rml#> .
@prefix era:	<http://data.europa.eu/949/> .
@prefix skos:	<http://www.w3.org/2004/02/skos/core#> .
@prefix prov:   <http://www.w3.org/ns/prov#> .


#Base
<https://data.infrabel.be/mapping/rinf/SectionOfLine/1>
  skos:comment "Maps the RINF database with the ERA vocabulary";
  prov:used <https://data.infrabel.be/data/Source/RINF/>;
  a prov:Activity,
    rr:TriplesMap;

  rr:logicalTable [rr:tableName "s1390.rinf_section_of_line"; ];

  rr:subjectMap [
    rr:template "https://data.infrabel.be/data/SectionOfLine/{linesectionid}";
    rr:class era:SectionOfLine ; 
    rr:termtype rr:IRI ];

  rr:predicateObjectMap [
    rr:predicate era:opStart;
    rr:objectMap [ rr:template "https://data.infrabel.be/data/OperationalPoint/{solopstart}";
                  rr:termtype rr:IRI ]] ; 

  rr:predicateObjectMap [
    rr:predicate era:opEnd;
    rr:objectMap [ rr:template "https://data.infrabel.be/data/OperationalPoint/{solopend}";
                  rr:termtype rr:IRI ]].

<https://data.infrabel.be/mapping/rinf/Link/SectionOfLine/NationalRailwayLine/>
  skos:comment "Maps the link between SectionOfLine and NationalRailwkayLine ";
  prov:used <https://data.infrabel.be/mapping/rinf/Link/SectionOfLine/OperationalPoint/>;
  a prov:Activity,
    rr:TriplesMap;

  rr::logicalTable [rr:tableName "s1390.rinf_section_of_line"; ];

  rr:subjectMap [
    rr:template "https://data.infrabel.be/data/SectionOfLine/{linesectionid}" ; 
    rr:termtype rr:IRI  ];

  rr:predicateObjectMap [
    rr:predicate era:lineNationalId;
    rr:objectMap [ rr:template "https://data.infrabel.be/data/Line/{line_id}" ;
                  rr:termType rr:IRI ;
                  rr:class era:NationalRailwayLine ] ].
``` 
2. Materialize it  :
`docker run --rm -v "%cd%":/data -v "%cd%/jdbc":/opt/ontop/jdbc ontop/ontop ontop materialize -m /data/src/test.r2rml.ttl -p /data/src/rinf.properties -o /data/output/test.ttl -f turtle`

**Expected behavior:** 
I should get a test.ttl file with both TriplesMaps mapped.

**Actual behavior:**
I only get a test.ttl file with the first TriplesMap mapped. 

**Reproduces how often:**
Everytime

### Attached material

For safety reasons, I cannot give access to the internal database I am querying. But I suspect the behaviour would be similar with any other database ?
There are no errors, the log file does not show anything past the mapping of the first TriplesMap.

### Versions

Latest

### Additional Information

I am fairly new to this, so I might have missed something, somewhere in the documentation. Thanks in advance for your help !

**Comment by LorenzBuehmann** [comment]
Your second triples map isn't being parsed because you have a typo: `rr::logicalTable` - see the double colon.

Also, in your case it didn't hurt, but the URIs are case-sensitive in Semantic Web. It has to be `rr:termType` in all places, not sometimes  `rr:termtype`

**Comment by remiColletGG** [comment]
Thanks a lot for your answer, and sorry for opening a issue that is not an actual issue !
