### ISSUE TITLE
Error "No suitable driver found for" even after adding JDBC driver

### ISSUE THREAD

**Issue by fishfree** [ontop/ontop#821]
![image](https://github.com/user-attachments/assets/456b85df-5b73-4c2e-8d94-b0562f9bd671)

But I've already added here:
![image](https://github.com/user-attachments/assets/24cbbddd-31f8-4604-88e3-e7185221a15d)

My Protege: 5.6.3, Ontop plugin 5.2.0, JDK 11.

**Comment by apano-on** [comment]
Have you input the correct parameters in the "Connection Parameters" tab and then checked they are complete before starting the reasoner? The message seems to indicate all 3 fields are empty. For example (NOTE: modify the connection URL, username and password as needed):
![mysql_connection](https://github.com/user-attachments/assets/e32ae55f-7932-40a3-8cb2-b642dcc3f12a)

I just ran a test with the same JDK and MySQL jdbc driver version in Linux, and for Ontop v. 5.2.0 the bootstrapper command in Protege worked correctly.

**Comment by fishfree** [comment]
No wonder. The doc has no description for this step. Thank you very much!@apano-on
