### ISSUE TITLE
Swapping in construction nodes results in invalid queries

### ISSUE THREAD

**Issue by samdus** [ontop/ontop#822]
### Description

During the saturating process, Ontop reuses query definitions defined for an object property to define any inverseOf object property. It usually works as intended, but I ran across a specific use case where the generated query is not bound correctly. 

The method it.unibz.inf.ontop.spec.mapping.transformer.impl.TMappingSaturatorImpl.MappingAssertionConstructionNodeTransformer#updateConstructionNodeIri will generate a ConstructionNode that simply swaps the subject and object of the child tree. However, as I understand the definition of ConstructionNode, it is illegal to have a variable in the domain and range of the Substitution. In my use case, it causes the childVariables to be empty. Therefore, every variable is considered as not required and is removed by it.unibz.inf.ontop.iq.node.normalization.impl.NotRequiredVariableRemoverImpl.

I'm not so sure that my proposition goes in the spirit of the rest of the code base, but I would change the ConstructionNode constructor to permit the specific case when the construction node is used to make a swap. I made a [Pull Request](https://github.com/ontop/ontop/pull/823) for an example of this proposition.

### Steps to Reproduce

1. I defined [a test in my fork](https://github.com/samdus/ontop/blob/48f32e2e20812ebb3f80d5d5c191038f5e0792f4/core/model/src/test/java/it/unibz/inf/ontop/iq/NotRequiredVariableRemoverTest.java) to illustrate the behaviour.
2. An example of Tree that are currently invalid is :
```
CONSTRUCT [s, p, o] [s/o, p/<http://example.org/iri>, o/s]
   UNION [s, o]
      CONSTRUCT [s, o] [s/RDF(http://example.org/dom1/{}(v0),IRI), o/RDF(http://example.org/range1/{}(v1),IRI)]
         VALUES [v0, v1] ("1"^^STRING,"2"^^STRING)
      CONSTRUCT [s, o] [s/RDF(http://example.org/dom2/{}(v2),IRI), o/RDF(http://example.org/range2/{}(v3),IRI)]
         VALUES [v2, v3] ("3"^^STRING,"4"^^STRING)
```

**Expected behavior:** [What you expect to see]

The tree should be valid and, therefore, could be optimized as follows:
```
CONSTRUCT [s, p, o] [p/<http://example.org/iri>, s/RDF(v1,IRI), o/RDF(v0,IRI)]
   VALUES [v0, v1] ("http://example.org/dom1/1"^^STRING,"http://example.org/range1/2"^^STRING) ("http://example.org/dom2/3"^^STRING,"http://example.org/range2/4"^^STRING)
```
**Actual behavior:** [What actually happens]

The tree is invalid, and the required variables are not considered. Therefore, they are deleted during the optimization :
```
CONSTRUCT [s, p, o] [s/o, p/<http://example.org/iri>, o/s]
   VALUES [] () ()
```

**Reproduces how often:** [Does it happen every time?]
Every time.

### Versions
Ontop version5 (5.2.0) on commit f46dabab12aa1e0f0ab9a2b78b16393bee49b9c5

**Comment by bcogrel** [comment]
Hi @samdus,

Thanks for reporting the issue with the mapping saturator and proposing a solution.

The example tree is indeed invalid for several reasons:
  - There is a circular dependency between `s` and `o` (i.e. which one provides a definition to the other?)
  - A variable definition in the substitution of a construction node cannot be present in the subtree (there is no notion of overriding a column in this algebra).
  - It is also self-contradicting: the union sub-tree produces values for `s` and `o` that are always different while the top construction node is supposed to build the same values for `s` and `o`.

Such a tree clearly violates the IQ semantics and should never be produced. It is a bug.

If you could provide us with a high-level test (mapping + ontology + SPARQL query) reproducing it, that would be great.

Benjamin

**Comment by samdus** [comment]
Thank you for the rapid answer! I'm surprised that this is considered a circular dependency because I understood the substitution like multiple assignments (i.e., where the assignments are made in parallel independently of one another). This would make the right end-side of the substitution always calculated solely from the subtree, and therefore, it would not represent a circular dependency. That says, your explanation clears this up for me.

I don't think the situation that generates this bug can be reproduced only with Ontop. It happens in my project because I am working on a derivation of Ontop generating relational tuples rather than RDF. I will not go into more detail since it is not relevant to the conversation.  I will change my implementation so the variable is renamed in the subtree, and this case will not happen. 

Thank you again for your time!

**Comment by bcogrel** [comment]
If you have questions related to IQs, please do not hesitate to contact me.

If you want to read more about it, I suggest the following two publications:
  - Guohui Xiao, Davide Lanti, Roman Kontchakov, Sarah Komla-Ebri, Elem Güzel-Kalayci, Linfang Ding, Julien Corman, Benjamin Cogrel, Diego Calvanese, and Elena Botoeva. [The Virtual Knowledge Graph System Ontop](https://research.bcgl.fr/pdfs/ontop-iswc20.pdf). International Semantic Web Conference (Resource Track), 2020.
  - Guohui Xiao, Roman Kontchakov, Benjamin Cogrel, Diego Calvanese, and Elena Botoeva. [Efficient Handling of SPARQL OPTIONAL for OBDA](https://link.springer.com/chapter/10.1007/978-3-030-00671-6_21).  International Semantic Web Conference (Research Track), 2018.

There is also a [documentation page]( https://ontop-vkg.org/dev/internals/iq.html) giving an overview on IQs.

**Comment by samdus** [comment]
Thank you very much for your time!
