### ISSUE TITLE
Query Manager: Wrong text at mouse-over

### ISSUE THREAD

**Issue by BenGruber** [ontop/ontop#83]
When you move the mouse over the buttons to add/delete  a new query the text is wrong. It should say add/delete query, whereas it currently says "Remove the selected data source".
![ontop bug](https://cloud.githubusercontent.com/assets/445610/11865432/4d13b3d4-a4a4-11e5-8222-6771c7e22ee7.PNG)

**Comment by ghxiao** [comment]
Hi, @daghovland In order to close an issue via push. You need to use "Close" instead of "Closes" in your commit message :)
