### ISSUE TITLE
suggestion: adding java_home detection in the run.bat for protégé bundle

### ISSUE THREAD

**Issue by reijin90** [ontop/ontop#93]
We could add:
```
set JAVA=java

if exist "%JAVA_HOME%\bin\java.exe" set JAVA="%JAVA_HOME%\bin\java"

%JAVA% -Xmx500M -Xms200M -DentityExpansionLimit=100000000 -Dlog...
```

To make it easier to run Ontop with the Java version you want to. The only thing a user has to do now to make it run with a specific java version is by setting the JAVA_HOME variable.

**Comment by ghxiao** [comment]
Hi,

Reasonable suggestion. 

I would suggest that you upstream your request to the protege team, since we would like to take the files from protege as it is.

**Comment by reijin90** [comment]
will do!

**Comment by ghxiao** [comment]
@reijin90 I close the issue. Free feel to reopen it if you have some updates.
