### ISSUE TITLE
R2RML Bootstraping? 

### ISSUE THREAD

**Issue by eschwert** [ontop/ontop#96]
Is it possible to generate R2RML-Mapping? I can see r2rml description (only for R2RML mapping) in the docu but I get only OBDA-files [https://github.com/ontop/ontop/wiki/OntopCLI#ontop-bootstrap](url)

**Comment by ghxiao** [comment]
Hi, you can covert the boostrapped .obda file to an R2RML .ttl file using CLI.

https://github.com/ontop/ontop/wiki/OntopCLI#ontop-mapping-to-r2rml

Let us know if you have any issue.
