### ISSUE TITLE
Special characters (e.g. ä,ö,ü,ß) will make the CLI version and fail

### ISSUE THREAD

**Issue by reijin90** [ontop/ontop#98]
Hi!

I've encountered this issue when having those types of characters in my mappings. Protégé would work fine, but the CLI version would not load the mappings. Using my IDE and the OWLAPI example it would work again, but after creation of a .jar and running it with 
"java -jar Prototyp.jar"
I would end up with the same exception. I was able to track the issue down to a missing commandline parameter to enable UTF-8 Encoding. By running my .jar with
"java -jar -Dfile.encoding=UTF-8 Prototyp.jar"
It would read the mappings without issue. I the same holds true for the CLI version. So I guess it would be useful to add the "-Dfile.encoding=UTF-8" parameter to the "ontop.bat" and "ontop.sh".

Thoughts?

**Comment by ghxiao** [comment]
Thanks for the suggestion. I think it makes sense.

**Comment by skomlaebri** [comment]
Hi,
we had a closer look to the issue and we prefer to keep the settings as they are know. 
Adding the -Dfile.encoding=UTF-8 would generate problem to all our users that work with different encoding in their files. In case a similar issue appears, (a file encoding different from the locale one) the user can add the parameter -Dfile.encoding=fileEncoding to the settings.
I will add the information in our wiki.

**Comment by skomlaebri** [comment]
References in the wiki:
https://github.com/ontop/ontop/wiki/ObdalibPluginTroubleshooting#command-line-interface
